### ISSUE TITLE
why? AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by littleguyy** [secdev/scapy#1017]
# I use pythone32 3.6.3 on windows7 64bit
import socket
from scapy.all import *
i=IP()
i.dst="192.168.1.1"
i.display()
    
ic=ICMP()
ic.display()

reply=sr1(i/ic)
========================= RESTART: I:/scapy网络练习.py =========================
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
###[ IP ]###
  version   = 4
  ihl       = None
  tos       = 0x0
  len       = None
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = ip
  chksum    = None
WARNING: No route found (no default route?)
  src       = 0.0.0.0
  dst       = 192.168.1.1
  \options   \
###[ ICMP ]###
  type      = echo-request
  code      = 0
  chksum    = None
  id        = 0x0
  seq       = 0x0
Traceback (most recent call last):
  File "I:/scapy网络练习.py", line 68, in <module>
    scapy测试()
  File "I:/scapy网络练习.py", line 30, in scapy测试
    reply=sr1(i/ic)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\sendrecv.py", line 344, in sr1
    s=conf.L3socket(filter=filter, nofilter=nofilter, iface=iface)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\arch\pcapdnet.py", line 321, in __init__
    self.ins = open_pcap(iface, 1600, 0, 100)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\arch\windows\__init__.py", line 237, in <lambda>
    pcapdnet.open_pcap = lambda iface,*args,**kargs: _orig_open_pcap(pcap_name(iface),*args,**kargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\arch\pcapdnet.py", line 251, in <lambda>
    open_pcap = lambda *args,**kargs: _PcapWrapper_pypcap(*args,**kargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\arch\pcapdnet.py", line 215, in __init__
    self.iface = create_string_buffer(device.encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by gpotter2** [comment]
Hi,
Please download the latest dev version at https://github.com/secdev/scapy/archive/master.zip
Then install it via `python setup.py install`
