### ISSUE TITLE
DNSRR issue

### ISSUE THREAD

**Issue by bartex80** [secdev/scapy#1084]
I am testing newest scapy with python3 and I've found a problem with DNSRR packet:

```python
p = DNS(qr=1, qd=DNSQR(qtype='A', qname='example.com'), an=DNSRR(type='A', rdata='1.2.3.4'))
bytes(p)

```
```
Traceback (most recent call last):
  File "src/scapy/scapy/compat.py", line 96, in raw
    return bytes(x)
  File "src/scapy/scapy/packet.py", line 338, in __bytes__
    return self.build()
  File "src/scapy/scapy/packet.py", line 436, in build
    p = self.do_build()
  File "src/scapy/scapy/packet.py", line 418, in do_build
    pkt = self.self_build()
  File "src/scapy/scapy/packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "src/scapy/scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "src/scapy/scapy/layers/dns.py", line 256, in i2m
    x = len(rdataf.i2m(pkt, pkt.rdata))
  File "src/scapy/scapy/layers/dns.py", line 227, in i2m
    s = inet_aton(s)
TypeError: inet_aton() argument 1 must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/scapy/scapy/packet.py", line 338, in __bytes__
    return self.build()
  File "src/scapy/scapy/packet.py", line 436, in build
    p = self.do_build()
  File "src/scapy/scapy/packet.py", line 418, in do_build
    pkt = self.self_build()
  File "src/scapy/scapy/packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "src/scapy/scapy/fields.py", line 408, in addfield
    return s + self.i2m(pkt, val)
  File "src/scapy/scapy/layers/dns.py", line 140, in i2m
    return raw(x)
  File "src/scapy/scapy/compat.py", line 98, in raw
    return bytes(x, encoding="utf8")
TypeError: encoding without a string argument
```

**Comment by guedou** [comment]
Confirmed.

**Comment by guedou** [comment]
Here is a smaller case triggering this issue:
`raw(DNSRR(type='A', rdata='1.2.3.4'))`

**Comment by guedou** [comment]
Does #1089 fix your issue ?

**Comment by bartex80** [comment]
Yes, #1089 fixes my issue. Thanks
