### ISSUE TITLE
sniff() is broken on Linux

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#110]
I ran into two different sniff() related bugs today. I am not confident in my fixes, so I prefer to open this issue to discuss them.

The first one occurs when pressing CTRL+C during sniff():
```python
>>> sniff()
^CTraceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/sendrecv.py", line 621, in sniff
    s.close()
UnboundLocalError: local variable 's' referenced before assignment
```

The following patch fixes the issue:
```diff
--- a/scapy/sendrecv.py
+++ b/scapy/sendrecv.py
@@ -618,7 +618,7 @@ interfaces)
     except KeyboardInterrupt:
         pass
     if opened_socket is None:
-        s.close()
+        [s.close() for s in sniff_sockets]
     return plist.PacketList(lst,"Sniffed")
```

After applying this patch, the second issue occurs during sniff():
```python
>>> sniff()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/sendrecv.py", line 599, in sniff
    p = s.recv()
  File "scapy/arch/linux.py", line 539, in recv
    pkt.direction = sa_ll[2]
  File "scapy/packet.py", line 217, in __setattr__
    return object.__setattr__(self, attr, val)
AttributeError: 'Ether' object has no attribute 'direction'
```

Adding the direction variable to __slots__ fixes the issue. However, I wonder if this is the best way to fix this second issue.
 ```diff
--- a/scapy/layers/l2.py
+++ b/scapy/layers/l2.py
@@ -141,6 +141,7 @@ class ARPSourceMACField(MACField):
 
 class Ether(Packet):
     name = "Ethernet"
+    __slots__ = ["direction"]
     fields_desc = [ DestMACField("dst"),
                     SourceMACField("src"),
                     XShortEnumField("type", 0x9000, ETHER_TYPES) ]

```

**Comment by p-l-** [comment]
@guedou both fixes are related to #73.

Your first fix seems OK, but you don't need to create a list:
```diff
--- a/scapy/sendrecv.py
+++ b/scapy/sendrecv.py
@@ -618,7 +618,8 @@ interfaces)
     except KeyboardInterrupt:
         pass
     if opened_socket is None:
-        s.close()
+        for s in sniff_sockets:
+            s.close()
     return plist.PacketList(lst,"Sniffed")
 
 
```

Your second fix is also correct, but should be done at `Packet()` level, since pretty much anything can be used as link layer. After reading again #73, `sniffed_on` will also be needed:

```diff
--- a/scapy/packet.py
+++ b/scapy/packet.py
@@ -46,6 +46,8 @@ class Packet(BasePacket):
         "name",
         # used for sr()
         "_answered",
+        # used when sniffing
+        "direction", "sniffed_on",
     ]
     __metaclass__ = Packet_metaclass
     name = None
```

Sorry I missed these two bugs...
