### ISSUE TITLE
raw/Raw doesn't work - centos, python2.7

### ISSUE THREAD

**Issue by senaps** [secdev/scapy#1123]
version: `(2.3.3)`
os: `centos 7`
python: `2.7.5`

what i do:

    >>> s = IP(src="192.168.88.128")
    >>> s
    <IP  src=192.168.88.128 |>
    >>> raw(s)
    Traceback (most recent call last):
     File "<console>", line 1, in <module>
     NameError: name 'raw' is not defined

    >>> Raw(s)
    Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/usr/lib/python2.7/site-packages/scapy/base_classes.py", line 223, in __call__
    i.__init__(*args, **kargs)
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 95, in __init__
    self.dissect(_pkt)
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 619, in dissect
    s = self.do_dissect(s)
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 593, in do_dissect
    assert(raw.endswith(s))
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 192, in __getattr__
    fld,v = self.getfield_and_val(attr)
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 189, in getfield_and_val
    return self.payload.getfield_and_val(attr)
    File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 1125, in getfield_and_val
    raise AttributeError(attr)
    AttributeError: endswith

**Comment by gpotter2** [comment]
Hi !
Let's clarify:
- `raw()` turns a packet into bytes. It is only available with 2.4.0+ (we started to support Python 3). It means that you need to update scapy (for now, it's a Release Candidate)
- `Raw()` is a layer that contains some unknown content.

examples:
- `raw(IP())`
- `Raw("data")`

**Comment by senaps** [comment]
so we don't have this raw() in python 2, scapy 2.3.3 ?

im creating a packet subclass, it only contains a fields_desc .
i want the binary representation of it to be sent on the line using twisted.

so i'm thinking that i may need `raw(Packet_Subclass())`

is that even what i need? or i should use something like `i2m(elemnt_of_packet_subclass)` ?

**Comment by p-l-** [comment]
Not clear what you are asking.

You do **not** have `raw()` in Scapy <= 2.3.3, you only have `str()`.

With Scapy >= 2.4.0rc*, you have `raw()`, which becomes the preferred API to convert a packet to its raw form. `str()` will still work, but only with Python 2.

If you have other questions, please open other issues.
