### ISSUE TITLE
lldp fails to decode messages containing organisation specific options

### ISSUE THREAD

**Issue by speakinghedge** [secdev/scapy#1151]
affected version: master

- org specific TLV currently not handled 
- remaining payload is not decoded (guess_payload() in LLDPDU needs a proper default - currently it just returns None for TLV-type 127), LLDPDUEndOfLLDPDU is lost
- LLDP struct integrity test catches in (if not disabled = default) and throws an exception

```
Traceback (most recent call last):
  File "send-frames.py", line 28, in <module>
    sniff(iface='eth2', timeout=20, prn=frame_handler)
  File "/tmp/wtf/scapy/sendrecv.py", line 744, in sniff
    p = s.recv()
  File "/tmp/wtf/scapy/arch/linux.py", line 606, in recv
    pkt = cls(pkt)
  File "/tmp/wtf/scapy/base_classes.py", line 240, in __call__
    i.__init__(*args, **kargs)
  File "/tmp/wtf/scapy/packet.py", line 132, in __init__
    self.dissection_done(self)
  File "/tmp/wtf/scapy/packet.py", line 161, in dissection_done
    self.payload.dissection_done(pkt)
  File "/tmp/wtf/scapy/contrib/lldp.py", line 277, in dissection_done
    LLDPDU._frame_structure_check(LLDPDU.LAYER_STACK)
  File "/tmp/wtf/scapy/contrib/lldp.py", line 216, in _frame_structure_check
    ' '.join(standard_frame_structure)))
scapy.contrib.lldp.LLDPInvalidFrameStructure: Invalid frame structure.
got: LLDPDUChassisID LLDPDUPortID LLDPDUTimeToLive LLDPDUPortDescription LLDPDUSystemDescription LLDPDUSystemCapabilities LLDPDUManagementAddress
expected: LLDPDUChassisID LLDPDUPortID LLDPDUTimeToLive <...> LLDPDUEndOfLLDPDU
```

Sample:
[lldp-with-org-specific-types.zip](https://github.com/secdev/scapy/files/1725955/lldp-with-org-specific-types.zip)

Fix is on its way.

**Comment by speakinghedge** [comment]
now the output for org specific TLVs looks like...

```
###[ Ethernet ]### 
  dst       = 01:80:c2:00:00:0e
  src       = 00:1b:1b:b0:f3:d7
  type      = 0x88cc
###[ LLDPDU ]### 
... <stripped> ...
###[ LLDPDUManagementAddress ]### 
                          _type     = management address
                          _length   = 20
                          _management_address_string_length= 5
                          management_address_subtype= IPv4
                          management_address= 0a0a0066
                          interface_numbering_subtype= ifIndex
                          interface_number= 1000
                          _oid_string_length= 8
                          object_id = 2b0601040181c06e
###[ LLDPDUGenericOrganisationSpecific ]### 
                             _type     = organisation specific TLV
                             _length   = 8
                             org_code  = PROFIBUS International (PNO)
                             subtype   = 2
                             data      = 00000000
###[ LLDPDUGenericOrganisationSpecific ]### 
                                _type     = organisation specific TLV
                                _length   = 10
                                org_code  = PROFIBUS International (PNO)
                                subtype   = 5
                                data      = 001b1bb0f3d5
###[ LLDPDUGenericOrganisationSpecific ]### 
                                   _type     = organisation specific TLV
                                   _length   = 9
                                   org_code  = IEEE 802.3
                                   subtype   = 1
                                   data      = 0363000010
###[ LLDPDUGenericOrganisationSpecific ]### 
                                      _type     = organisation specific TLV
                                      _length   = 6
                                      org_code  = IEEE 802.3
                                      subtype   = 4
                                      data      = 05f2
###[ LLDPDUEndOfLLDPDU ]### 
                                         _type     = end of LLDPDU
                                         _length   = 0
```
