### ISSUE TITLE
Add attribute to scapy.packet.Packet

### ISSUE THREAD

**Issue by karotak** [secdev/scapy#1230]
First of all thanks for developing & maintaining scapy, it's a really great tool!

Now to my problem at hand. I want to add a history attribute to my scapy packet `p` that works with `p.copy()`. That means whenever I modify  `p` I would add something like `"Ether.src changed"` to `p.history` and if I copy `p`, the new packet should have the same history. Since scapy does not support new packet attributes I tried monkey patching  scapy.packet.Packet. But even without adding anything a get a TypeError. My current workaround is to abuse p.time and changing it to a tuple.

Is there a better way to reach my goal? I'm using python3.6 and scapy2.4.0rc5.

```
import scapy.packet, scapy.layers.l2
from scapy import *

class AAA(scapy.packet.Packet):
    def __init__(self, _pkt=b"", post_transform=None, _internal=0, _underlayer=None, **fields):
        super().__init__(_pkt, post_transform, _internal, _underlayer, **fields)

scapy.packet.Packet = AAA
"""
Traceback (most recent call last):
  File "/media/tep/hub/code/scapy/history/a.py", line 27, in <module>
    p = scapy.layers.l2.Ether()
  File "/usr/local/lib/python3.6/dist-packages/scapy/base_classes.py", line 231, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 119, in __init__
    self.payload = NoPayload()
  File "/usr/local/lib/python3.6/dist-packages/scapy/base_classes.py", line 230, in __call__
    i = cls.__new__(cls, cls.__name__, cls.__bases__, cls.__dict__)
  File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 1243, in __new__
    Packet.__init__(singl)
  File "/media/tep/hub/code/scapy/history/a.py", line 6, in __init__
    super().__init__(_pkt, post_transform, _internal, _underlayer, **fields)
TypeError: super(type, obj): obj must be an instance or subtype of type
"""

if __name__ == '__main__':
    p = scapy.layers.l2.Ether()

    # usecase:  add attr history to a packet and modify it whenever the packet get's altered,
    #           should get copied if packet is copied
    p.history = []
    p["Ether"].src = "AA:BB:CC:DD:EE:FF"
    p.history.append("Ether.src changed")

    # workaround, abuse p.time, but breaks p.sprintf("%time%")
    p.time = (p.time, [])
    p["Ether"].src = "AA:BB:CC:DD:EE:FF"
    p.time[1].append("Ether.src changed")

    # monkey patching does not work, see traceback (9-24)
```

**Comment by guedou** [comment]
You cannot do that without modifying `Packet.__slots__`
