### ISSUE TITLE
rror "TeX didn't respond as expected within the timeout period " at calling pdfdmump() 

### ISSUE THREAD

**Issue by bedweather** [secdev/scapy#1252]
Pathon: 2.7
Scapy:2.4

When I try demo calling rdpcap() , error has been happened

`>>>import shlex`
`>>> a=rdpcap("/home/zhangqiang/test.pacap")`
`>>> a[423].pdfdump(layer_shift=1)`
`still waiting for tex after 5 (of 60) seconds...
still waiting for tex after 10 (of 60) seconds...
still waiting for tex after 15 (of 60) seconds...
still waiting for tex after 20 (of 60) seconds...
still waiting for tex after 25 (of 60) seconds...
still waiting for tex after 30 (of 60) seconds...
still waiting for tex after 35 (of 60) seconds...
still waiting for tex after 40 (of 60) seconds...
still waiting for tex after 45 (of 60) seconds...
still waiting for tex after 50 (of 60) seconds...
still waiting for tex after 55 (of 60) seconds...
the timeout of 60 seconds expired and tex did not respond.
We try to finish the dvi due to an unhandled tex error
still waiting for tex after 5 (of 60) seconds...
still waiting for tex after 10 (of 60) seconds...
still waiting for tex after 15 (of 60) seconds...
still waiting for tex after 20 (of 60) seconds...
still waiting for tex after 25 (of 60) seconds...
still waiting for tex after 30 (of 60) seconds...
still waiting for tex after 35 (of 60) seconds...
still waiting for tex after 40 (of 60) seconds...
still waiting for tex after 45 (of 60) seconds...
still waiting for tex after 50 (of 60) seconds...
still waiting for tex after 55 (of 60) seconds...
the timeout of 60 seconds expired and tex did not respond.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/zhangqiang/.local/lib/python2.7/site-packages/scapy/packet.py", line 413, in pdfdump
    canvas = self.canvas_dump(**kargs)
  File "/home/zhangqiang/.local/lib/python2.7/site-packages/scapy/packet.py", line 524, in canvas_dump
    pt = pyx.text.text(XSTART, (YTXT-y)*YMUL, r"\font\cmssfont=cmss10\cmssfont{%s}" % proto.name, [ pyx.text.size.Large])
  File "/usr/lib/python2.7/dist-packages/pyx/text.py", line 1201, in text
    raise e
TexResultError: TeX didn't respond as expected within the timeout period (60 seconds).
The expression passed to TeX was:
  \ProcessPyXBox{\Large{}\font\cmssfont=cmss10\cmssfont{Ethernet}%
  }{83}%
  \PyXInput{87}%
After parsing the return message from TeX, the following was left:
  *! Interruption.
  <*>

  ? Type <return> to proceed, S to scroll future error messages,
  R to run without stopping, Q to run quietly,
  (cut after 5 lines, increase errordebug for more output)`

**Comment by guedou** [comment]
Could you share the content of your packet with `a[243].command()` ?

**Comment by gpotter2** [comment]
Please also report any warning/error messages when you are starting scapy

**Comment by guedou** [comment]
Close due to no activity. Please reopen if you can answer our queries.
