### ISSUE TITLE
Get-WMIObject -class Win32_NetworkAdapter Timeout with Realtek PCIe GBE Family Controller

### ISSUE THREAD

**Issue by Sean2379607955** [secdev/scapy#1267]
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/testrouter/common/sniffer.py", line 3, in <module>
    from scapy.all import *
  File "C:\Users\Administrator\PycharmProjects\testrouter\venv\lib\site-packages\scapy\all.py", line 16, in <module>
    from .arch import *
  File "C:\Users\Administrator\PycharmProjects\testrouter\venv\lib\site-packages\scapy\arch\__init__.py", line 95, in <module>
    from .windows import *
  File "C:\Users\Administrator\PycharmProjects\testrouter\venv\lib\site-packages\scapy\arch\windows\__init__.py", line 212, in <module>
    ifaces.load_from_powershell()
  File "C:\Users\Administrator\PycharmProjects\testrouter\venv\lib\site-packages\scapy\arch\windows\__init__.py", line 163, in load_from_powershell
    for i in get_windows_if_list():
  File "C:\Users\Administrator\PycharmProjects\testrouter\venv\lib\site-packages\scapy\arch\windows\__init__.py", line 78, in get_windows_if_list
    stdout, stdin = ps.communicate(timeout = 10)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Lib\subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Lib\subprocess.py", line 1094, in _communicate
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['powershell', '-NoProfile', 'Get-WMIObject -class Win32_NetworkAdapter', '|', 'select Name, @{Name="InterfaceIndex";Expression={$_.InterfaceIndex}}, @{Name="InterfaceDescription";Expression={$_.Description}},@{Name="InterfaceGuid";Expression={$_.GUID}}, @{Name="MacAddress";Expression={$_.MacAddress.Replace(":","-")}} | where InterfaceGuid -ne $null', '|', 'fl']' timed out after 10 seconds

It can work with wireless interface, but fail with Realtek PCIe GBE interface.

**Comment by gpotter2** [comment]
This is not our implementation: it’s scapy3k

**Comment by Sean2379607955** [comment]
You are right. I have installed scapy again, but there is no module in pycharm. How to install module of scapy into pycharm?

**Comment by gpotter2** [comment]
https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html
![image](https://user-images.githubusercontent.com/10530980/37677125-62c18dc2-2c7a-11e8-808a-b5616ad371cd.png)

**Comment by Sean2379607955** [comment]
Yes. Issue resolved.
Thanks.
