### ISSUE TITLE
sniff()ed packets do not contain Dot1Q - using libpcap, exception occurs

### ISSUE THREAD

**Issue by vklimmek** [secdev/scapy#1289]
Linux, python3.4/python3.6
Packets, that are Dot1Q vlan tagged on wire, are not sniffed with Dot1Q tag. Due to that, I used:

conf.use_pcap = True
import scapy.arch.pcapdnet
pkt = sniff(iface="lan3", count=1)

Got:
<L2pcapListenSocket: read packets at layer 2 using libpcap>
Traceback (most recent call last):
  File "./test_vk.py", line 9, in <module>
    pkt = sniff(iface="lan3", count=1)
  File "/opt/scapy_secdev/scapy/sendrecv.py", line 741, in sniff
    ins = _select(sniff_sockets)
  File "/opt/scapy_secdev/scapy/sendrecv.py", line 729, in _select
    return select(sockets, [], [], remain)[0]
  File "/opt/scapy_secdev/scapy/supersocket.py", line 49, in fileno
    return self.ins.fileno()
  File "/opt/scapy_secdev/scapy/arch/pcapdnet.py", line 434, in fileno
    self.__class__.__name__)
RuntimeError: _PcapWrapper_pcapy has no fileno. Please report this bug.

My fix is:
```
$ git diff
diff --git a/scapy/sendrecv.py b/scapy/sendrecv.py
index 416cdbe4..4539bf63 100644
--- a/scapy/sendrecv.py
+++ b/scapy/sendrecv.py
@@ -738,7 +738,7 @@ Examples:
         from scapy.arch.bpf.supersocket import bpf_select
         def _select(sockets):
             return bpf_select(sockets, remain)
-    elif WINDOWS:
+    elif WINDOWS or conf.use_pcap:
         from scapy.arch.pcapdnet import PcapTimeoutElapsed
         read_allowed_exceptions = (PcapTimeoutElapsed,)
         def _select(sockets):
```

**Comment by guedou** [comment]
Thanks for the report. Which version of Scapy and which pcap Python modules are you using ?

**Comment by vklimmek** [comment]
I currently use scapy version 2.4.0rc5.dev64 (https://github.com/secdev/scapy)

pcapy (0.11.1)

net-libs/libpcap
   Latest version available: 1.8.1-r2

Python 3.4.6 (default, Mar 23 2018, 03:41:33)
[GCC 5.4.0] on linux
or
Python 3.6.1 (default, Mar 11 2018, 12:43:54)
[GCC 5.4.0] on linux

**Comment by gpotter2** [comment]
The bug is a well-known pcapy bug.
https://github.com/CoreSecurity/pcapy/pull/22
The function is still unimplemented in the latest releases, so we have not implemented it in scapy.

**Comment by guedou** [comment]
@vklimmek PR #1315 fixes your issue. I still need to work on the unit tests, but the patch works fine when using pcapy >= 0.11.3
