### ISSUE TITLE
Issue when dissecting IP() packet

### ISSUE THREAD

**Issue by g-mahieux** [secdev/scapy#1324]
Hello,

This issue came up while testing PR #1310, but is apparently unrelated to it.

Executing:
```
IP(bytearray.fromhex("0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30313233340001"))
````
By running Scapy directly:
```
>>> IP(bytearray.fromhex("0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30313233340001"))
<IP  version=0 ihl=15 tos=0x10 len=4370 id=4884 flags= frag=5398 ttl=23 proto=24 chksum=0x191a src=27.28.29.30 dst=31.32.33.34 options=[<Raw  load="#$%&'()*+,-./01234\x00\x01" |>] |>
```

In the travis test environment:
```
>>> IP(bytearray.fromhex("0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30313233340001"))
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/osboxes/scapy/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/home/osboxes/scapy/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/home/osboxes/scapy/scapy/packet.py", line 756, in dissect
    s = self.do_dissect(s)
  File "/home/osboxes/scapy/scapy/packet.py", line 718, in do_dissect
    s, fval = f.getfield(self, s)
  File "/home/osboxes/scapy/scapy/fields.py", line 760, in getfield
    p = self.m2i(pkt, remain)
  File "/home/osboxes/scapy/scapy/fields.py", line 615, in m2i
    return self.cls(m)
  File "/home/osboxes/scapy/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/home/osboxes/scapy/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/home/osboxes/scapy/scapy/packet.py", line 756, in dissect
    s = self.do_dissect(s)
  File "/home/osboxes/scapy/scapy/packet.py", line 718, in do_dissect
    s, fval = f.getfield(self, s)
  File "/home/osboxes/scapy/scapy/fields.py", line 972, in getfield
    s, v = self.field.getfield(pkt, s)
  File "/home/osboxes/scapy/scapy/fields.py", line 93, in getfield
    return  s[self.sz:], self.m2i(pkt, struct.unpack(self.fmt, s[:self.sz])[0])
error: unpack requires a string argument of length 4
```
Not sure how to debug further, thank you for your help.

**Comment by g-mahieux** [comment]
Indeed, this is a "dummy" packet extracted from the MACsec specification (reference test vectors) and they apparently did not care enough to use valid IP packets as payloads.
If this behavior is expected when the IP length field is incorrect, then please feel free to close this issue, and sorry for the trouble. :-)
