### ISSUE TITLE
Having issues with count

### ISSUE THREAD

**Issue by hyhilman** [secdev/scapy#1368]
I'm writing some script to make simple icmp flood on ipv6 and ipv4 through wlan( and 6lowpan for future). And I'm going to write this script with scapy. IPv4 is good. but i get difference behaviour when I'm using interactive console(ipython) and python script with ipv6. when I'm execute this script i get following errors:
```
from scapy.all import *
...
ip = IPv6(dst="#")
protocol = ICMPv6EchoRequest()
packet = ip / protocol
send(packet, iface="#", count=100)
...
```
> WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
> ERROR: [Errno -9] Address family for hostname not supported
> .ERROR: [Errno -9] Address family for hostname not supported
> .Traceback (most recent call last):
>   File "/root/.local/lib64/python3.5/site-packages/scapy/supersocket.py", line 102, in send
>     self.outs.sendto(sx,(x.dst,0))
> socket.gaierror: [Errno -9] Address family for hostname not supported
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "simple_flood.py", line 48, in <module>
>     send(packet, iface="#", count=100)
>   File "/root/.local/lib64/python3.5/site-packages/scapy/sendrecv.py", line 255, in send
>     __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
>   File "/root/.local/lib64/python3.5/site-packages/scapy/sendrecv.py", line 238, in __gen_send
>     s.send(p)
>   File "/root/.local/lib64/python3.5/site-packages/scapy/supersocket.py", line 104, in send
>     log_runtime.error(msg)
>   File "/usr/lib64/python3.5/logging/__init__.py", line 1314, in error
>     self._log(ERROR, msg, args, **kwargs)
>   File "/usr/lib64/python3.5/logging/__init__.py", line 1421, in _log
>     self.handle(record)
>   File "/usr/lib64/python3.5/logging/__init__.py", line 1430, in handle
>     if (not self.disabled) and self.filter(record):
>   File "/usr/lib64/python3.5/logging/__init__.py", line 716, in filter
>     result = f.filter(record)
>   File "/root/.local/lib64/python3.5/site-packages/scapy/error.py", line 42, in filter
>     record.msg = "more "+record.msg
> TypeError: Can't convert 'gaierror' object to str implicitly

but when I write it with ipython i got success message. 
> In [14]: send(  IPv6(dst="#") / ICMPv6EchoRequest(), count=100, iface="vboxnet0")
> WARNING: No route found for IPv6 destination # (no default route?). This affects only IPv6
> .WARNING: No route found for IPv6 destination # (no default route?). This affects only IPv6
> .WARNING: more No route found for IPv6 destination # (no default route?). This affects only IPv6
> ..................................................................................................
> Sent 100 packets.

I already modifying routing table for ipv6, and the packed sended succesfuly when using ipython. and im googled but nothing i got. could you help me what I'm missing? the script is work when im only sending packets below 3, but i still get this error : **ERROR: [Errno -9] Address family for hostname not supported**. i think this error happen because this error looped and my script didnt handle it? anyway thanks for anyone who reading this. it might not easy to understand as this is my first time creating issues on github.

**Comment by hyhilman** [comment]
sorry, miracle is exist.
i compare all of attribute on both conf in ipython and script. then i understand what im missing.
maybe some ppl gonna need this. 

**_this problem exist because im not using right **L3socket**._**

you can check it by typing `conf.L3socket()`. 
instead using L3RawSocket6 im using L3RawSocket. you can using L3PacketSocket too but im prefer using L3RawSocket. for frther information you can check on [this](http://swoolley.org/man.cgi/2/socket)

to set it write it
`conf.L3socket = L3RawSocket6` _np: you can using different socket_
