### ISSUE TITLE
RecursionError: maximum recursion depth exceeded upon get PacketList object from multiprocessing SimpleQueue

### ISSUE THREAD

**Issue by zlatdev** [secdev/scapy#1369]
#### Brief description
script execution interrupted with "RecursionError: maximum recursion depth exceeded". This happened when object PacketList is passed between processes of multiprocessing module.

< describe the main issue in one sentence >
RecursionError: maximum recursion depth exceeded 
scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)

#### Environment

- Scapy version: scapy Version: 2.4.0
- Python version: python3.6
- Operating System: Ubuntu 16.04

#### How to reproduce

`from scapy.all import *
from multiprocessing import Process, SimpleQueue

IFACE_IN = "docker0"
IFACE_OUT = "docker0"

def mysniff(c):
    print("sniffing...")
    s = sniff(iface=IFACE_OUT, count=2, timeout=10)
    c.put(s)

q = SimpleQueue()
p = Process(target=mysniff, args=(q,))
p.start()

p_zero_req = Ether()
p_zero_req.dst = "FF:FF:FF:FF:FF:FF"
p_zero_req.src = "00:00:00:00:00:00"
p_zero_req.type = int("0xff", base=16)

p_ether = p_zero_req / Padding(b"\x00" * 50)

sendp(p_ether, iface=IFACE_IN, count=2)

pkt = q.get()
print(pkt)`

#### Actual result

:~/Projects/scapy/scripts$ sudo ./sendrecive.py 
sniffing...
..
Sent 2 packets.
Traceback (most recent call last):
  File "./sendrecive.py", line 30, in <module>
    pkt = q.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  [Previous line repeated 328 more times]
RecursionError: maximum recursion depth exceeded

#### Expected result
result of PacketList summary method

#### Related resources
Traceback (most recent call last):
  File "./sendrecive.py", line 30, in <module>
    pkt = q.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  File "/home/bykov/usr/vpython/scapy/lib/python3.6/site-packages/scapy/plist.py", line 81, in __getattr__
    return getattr(self.res, attr)
  [Previous line repeated 328 more times]
RecursionError: maximum recursion depth exceeded

**Comment by guedou** [comment]
Please answer my message on gitter.
