### ISSUE TITLE
ZigbeeSecurityHeader layer interpreted as raw

### ISSUE THREAD

**Issue by raissim** [secdev/scapy#1455]
Reading a .pcap of Zigbee packets with Zigbee Security Header on top of Zigbee Network Layer is interpreted as layers ZigbeeNWK + Raw instead of ZigbeeNWK + ZigbeeSecurityHeader.

    >>> pkts[53].flags
    <Flag 18 (security+extended_src)>
    >>> pkts[53]
    <Dot15d4FCS  fcf_reserved_1=0 fcf_panidcompress=True fcf_ackreq=False fcf_pending=False fcf_security=False fcf_frametype=Data fcf_srcaddrmode=Short fcf_framever=0 fcf_destaddrmode=Short fcf_reserved_2=0 seqnum=69 |<Dot15d4Data  dest_panid=0x1ff dest_addr=0xffff src_addr=0x0 |<ZigbeeNWK  discover_route=0 proto_version=2 frametype=command flags=security+extended_src destination=0xfffc source=0x0 radius=1 seqnum=220 ext_src=00:0d:6f:00:00:0d:c5:58 |<Raw  load='(\x11\x00\x00\x00X\xc5\r\x00\x00o\r\x00\x00j\x8c\x9b\x98\xea\xb2:\x96\x11' |>>>>  

The Raw load should be ZigbeeSecurityHeader because the flags field is set to security. 
In dot15d4.py line 570, the guess_payload() function of ZigbeeNWK did in fact return ZigbeeSecurityHeader for pkt, but despite that the packet isn't dissected correctly.

#### How to reproduce

Put [zigbee-join-authenticate.pcap.gz](https://github.com/secdev/scapy/files/2067483/zigbee-join-authenticate.pcap.gz) in local folder and launch the Python interpreter  

    from scapy.layers.dot15d4 import *
    bind_layers(Dot15d4Data, ZigbeeNWK)
    pkts = rdpcap("zigbee-join-authenticate.pcap.gz")
    pkts[53].flags
    pkts[53]  

#### Expected result

`pkts[53]` should display a <ZigbeeSecurityHeader layer instead of <Raw load
This issue applies to every other packet with a Zigbee Security Header (you can verify on Wireshark)

**Comment by gpotter2** [comment]
Hello !
When packets are dissected as Raw, it often means that their dissection fails.

Could you please:
- retry with `conf.debug_dissector = True` set
- share a pcap so that we can fix the issue ?

Thanks !

**Comment by raissim** [comment]
The pcap is [zigbee-join-authenticate.pcap.gz](https://github.com/secdev/scapy/files/2067483/zigbee-join-authenticate.pcap.gz)

After setting debug_dissector = True in config.py the previous output is now :  
```
from scapy.layers.dot15d4 import *
bind_layers(Dot15d4Data, ZigbeeNWK)
pkts = rdpcap("zigbee-join-authenticate.pcap.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 778, in rdpcap
    return fdesc.read_all(count=count)
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 961, in read_all
    res = RawPcapReader.read_all(self, count)
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 909, in read_all
    p = self.read_packet()
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 949, in read_packet
    p = self.LLcls(s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 760, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 738, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 760, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 738, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 760, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 738, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 239, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 134, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 755, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 718, in do_dissect
    s, fval = f.getfield(self, s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 868, in getfield
    l = self.length_from(pkt)
TypeError: <lambda>() missing 1 required positional argument: 's'
```

**Comment by gpotter2** [comment]
Does https://github.com/secdev/scapy/pull/1456 fixes it for you ?
You don't need to call
`bind_layers(Dot15d4Data, ZigbeeNWK)`

**Comment by gpotter2** [comment]
Actually the provided PR isn't a correct fix, I'll search for a better one

**Comment by raissim** [comment]
Not calling ```bind_layers(Dot15d4Data, ZigbeeNWK)``` will result in Scapy not dissecting the ZigbeeNWK header because the Dot15d4Data layer isn't bound to it. An example of this:  

```
>>> from scapy.layers.dot15d4 import *
>>> pkts = rdpcap("./zigbee-join-authenticate.pcap.gz")
>>> pkts[53]
<Dot15d4FCS  fcf_reserved_1=0 fcf_panidcompress=True fcf_ackreq=False fcf_pending=False fcf_security=False fcf_frametype=Data fcf_srcaddrmode=Short fcf_framever=0 fcf_destaddrmode=Short fcf_reserved_2=0 seqnum=69 |<Dot15d4Data  dest_panid=0x1ff dest_addr=0xffff src_addr=0x0 |<Raw  load='\t\x12\xfc\xff\x00\x00\x01\xdcX\xc5\r\x00\x00o\r\x00(\x11\x00\x00\x00X\xc5\r\x00\x00o\r\x00\x00j\x8c\x9b\x98\xea\xb2:\x96\x11' |>>>
```  
The ZigbeeNWK is replaced by a Raw layer.  

The bind layer line is decommented in dot15dy.py (l 1348) because there is still no way to choose between SixLoWPAN and ZigbeeNWK.

**Comment by raissim** [comment]
I still have the same problem (no Sec Header detected during dissection, raw instead)
```
>>> from scapy.layers.dot15d4 import *
>>> from scapy.layers.zigbee import *
>>> from scapy.utils import *
>>> conf.dot15d4_protocol = "zigbee"
>>> pkts = rdpcap("zigbee-join-authenticate.pcap.gz")
>>> pkts[53].flags
<Flag 18 (security+extended_src)>
>>> pkts[53]
<Dot15d4FCS  fcf_reserved_1=0 fcf_panidcompress=True fcf_ackreq=False fcf_pending=False fcf_security=False fcf_frametype=Data fcf_srcaddrmode=Short fcf_framever=0 fcf_destaddrmode=Short fcf_reserved_2=0 seqnum=69 fcs=0x1196 |<Dot15d4Data  dest_panid=0x1ff dest_addr=0xffff src_addr=0x0 |<ZigbeeNWK  discover_route=0 proto_version=2 frametype=command flags=security+extended_src destination=0xfffc source=0x0 radius=1 seqnum=220 ext_src=00:0d:6f:00:00:0d:c5:58 |<Raw  load='(\x11\x00\x00\x00X\xc5\r\x00\x00o\r\x00\x00j\x8c\x9b\x98\xea\xb2:' |>>>>
```  
  
After setting debug_dissector to True, I have a similar error with rdpcap

```
>>> pkts = rdpcap("zigbee-join-authenticate.pcap.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 841, in rdpcap
    return fdesc.read_all(count=count)
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 1024, in read_all
    res = RawPcapReader.read_all(self, count)
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 972, in read_all
    p = self.read_packet()
  File "/usr/local/lib/python3.5/dist-packages/scapy/utils.py", line 1012, in read_packet
    p = self.LLcls(s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 252, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 137, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 767, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 745, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 252, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 137, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 767, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 745, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 252, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 137, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 767, in dissect
    self.do_dissect_payload(payl)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 745, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 252, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 137, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 762, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 723, in do_dissect
    s, fval = f.getfield(self, s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 1135, in getfield
    l = self.length_from(pkt)
TypeError: <lambda>() missing 1 required positional argument: 's'
```

**Comment by gpotter2** [comment]
Ok, the latest PR fixes it.

Please note that the pcap you have provided is using `DLT_IEEE802_15_4_WITHFCS` (=195) as DLT, whereas the packet do not really contain a FCS, which causes a crash.

Here is the same pcap, re-written using `DLT_IEEE802_15_4_NOFCS` (=230)
[zigbee-join-authenticate-rewritten.zip](https://github.com/secdev/scapy/files/2072899/zigbee-join-authenticate-rewritten.zip)

**Comment by raissim** [comment]
Thanks! The problem is solved :)
I had issues with pcap earlier but I couldn't put my finger on it. Did you use tcprewrite to change the DLT?

**Comment by gpotter2** [comment]
I used
```
filename = ...
wrpcap(filename, rdpcap(filename), linktype=230)
```

**Comment by gpotter2** [comment]
I'll keep it open FTR until #1456 is merged

**Comment by raissim** [comment]
@AdamLaurie Sorry, the [wireshark](https://wiki.wireshark.org/IEEE_802.15.4) website where I found the pcap didn't specify the crypto keys.

This configuration (ZigbeeNWK layer / ZigbeeAppDataPayload without ZigbeeSecurityHeader) seems to be expected behaviour (if the security field of FCF is set to False), but this is the only time I've seen it too.
