### ISSUE TITLE
 AttributeError when unpack buffer from pcap in version 2.3.1 and 2.3.2 but not 2.2.0-dev or master

### ISSUE THREAD

**Issue by WilenceYao** [secdev/scapy#15]
Use scapy 2.3.1 & 2.3.2, I can not unpacket from pcap buffer, the test code and error output are below:

```
#!/usr/bin/env python

import pcap
import time
from scapy import all as scapy

iface = 'eth0'

def make_listener(iface):
    listener = pcap.pcap(iface)
    listener.setfilter('(tcp and port 22)')
    return listener

listener = make_listener(iface)
time.sleep(3)
listener.setnonblock()
for pkt in listener.readpkts():
    print scapy.Ether(pkt[1]).src
```

Exception Output:

```
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "test19.py", line 18, in <module>
    print scapy.Ether(pkt[1]).src
  File "/usr/lib/python2.7/site-packages/scapy/base_classes.py", line 196, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 85, in __init__
    self.dissect(_pkt)
  File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 618, in dissect
    s = self.do_dissect(s)
  File "/usr/lib/python2.7/site-packages/scapy/packet.py", line 589, in do_dissect
    assert(raw.endswith(s))
AttributeError: 'buffer' object has no attribute 'endswith'
```

But if I install version 2.2.0-dev or master, test code can output correct result:

```
WARNING: No route found for IPv6 destination :: (no default route?)
fa:16:3e:73:e9:e7
fa:16:3e:6f:1a:9d
fa:16:3e:73:e9:e7
fa:16:3e:73:e9:e7
fa:16:3e:6f:1a:9d
fa:16:3e:73:e9:e7
fa:16:3e:73:e9:e7
fa:16:3e:6f:1a:9d
fa:16:3e:73:e9:e7
```

**Comment by p-l-** [comment]
Hi,

Thanks for this report. Can you try with `scapy.Ether(str(pkt[1])).src`?

**Comment by WilenceYao** [comment]
Thx, your suggestion solve my problem.

**Comment by p-l-** [comment]
OK. I think it's fair to assume that `_pkt` argument to `Packet` (and subclasses') constructor is a string object.

While we could call `str()`, that would add one more function call per layer parsed, which could slow down network sniff operations and PCAP file parsing.
