### ISSUE TITLE
Scapy can't see/use some Ethernet interfaces on Windows

### ISSUE THREAD

**Issue by brianbienvenu** [secdev/scapy#1542]
#### Brief description

`get_windows_if_list()` shows a USB Ethernet interface, but I can't bind to it, and it doesn't appear in `IFACES`.

#### Environment

- Scapy version: Just pulled from GitHub, 1fc08e01f9d88c226e6a2132d6dec2a43eb660dd
- Python version: 3.7.0
- Operating System: Windows 10, up to date

#### How to reproduce
```
>>> from scapy.all import *
>>> get_windows_if_list()
[{'name': 'Realtek USB GbE Family Controller', 'win_index': '55', 'description': 'Ethernet', 'guid': '{F4AFC618-34E4-4E43-93E9-610C1E15FADD}', 'mac': '3C:18:A0:70:03:88', 'netid': 'Ethernet'}, {'name': 'VirtualBox Host-Only Ethernet Adapter', 'win_index': '19', 'description': 'VirtualBox Host-Only Network', 'guid': '{B26872D7-6040-4CFE-A192-3F3F28E205CC}', 'mac': '0A:00:27:00:00:13', 'netid': 'VirtualBox Host-Only Network'}, {'name': 'ExpressVPN Tap Adapter', 'win_index': '15', 'description': 'Ethernet 5', 'guid': '{863C7C2E-BC51-4281-BCBC-51D307B3ACF6}', 'mac': '00:FF:86:3C:7C:2E', 'netid': 'Ethernet 5'}, {'name': 'Bluetooth Device (Personal Area Network)', 'win_index': '13', 'description': 'Bluetooth Network Connection', 'guid': '{79C3535D-6FA9-4E01-865A-553503FDC6EF}', 'mac': '9C:B6:D0:E4:38:40', 'netid': 'Bluetooth Network Connection'}, {'name': 'Killer Wireless-n/a/ac 1535 Wireless Network Adapter', 'win_index': '12', 'description': 'Wi-Fi', 'guid': '{6E10F117-4870-4E98-B113-63F30BE08BFD}', 'mac': '9C:B6:D0:E4:38:3F', 'netid': 'Wi-Fi'}]
>>> s = conf.L2socket(iface='Realtek USB GbE Family Controller')
Traceback (most recent call last):
  File "C:\Users\Brian\Dropbox\TIGER\scapy\scapy\arch\windows\__init__.py", line 873, in dev_from_name
    return next(iface for iface in six.itervalues(self)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Brian\Dropbox\TIGER\scapy\scapy\arch\pcapdnet.py", line 449, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100, monitor=monitor)  # noqa: E501
  File "C:\Users\Brian\Dropbox\TIGER\scapy\scapy\arch\windows\__init__.py", line 979, in open_pcap
    iface_pcap_name = pcapname(iface)
  File "C:\Users\Brian\Dropbox\TIGER\scapy\scapy\arch\windows\__init__.py", line 948, in pcapname
    return IFACES.dev_from_name(dev).pcap_name
  File "C:\Users\Brian\Dropbox\TIGER\scapy\scapy\arch\windows\__init__.py", line 876, in dev_from_name
    raise ValueError("Unknown network interface %r" % name)
ValueError: Unknown network interface 'Realtek USB GbE Family Controller'
>>> s = conf.L2socket(iface='Killer Wireless-n/a/ac 1535 Wireless Network Adapter')
>>> # that one worked!
...
>>> IFACES
INDEX  IFACE                                                 IP             MAC
12     Killer Wireless-n/a/ac 1535 Wireless Network Adapter  138.12.71.39  9C:B6:D0:E4:38:3F
13     Bluetooth Device (Personal Area Network)                             9C:B6:D0:E4:38:40
>>> # interface 55 (my Realtek USB Ethernet) isn't shown (?)
```
#### Actual result

Scapy can't see, bind or use the interface.

#### Expected result

Scapy can see, bind and use the interface.

**Comment by gpotter2** [comment]
Hi !

`get_windows_if_list()` returns all interfaces by using Windows mechanics. It gives us all the data we need to set up the routes.

`get_if_list()` returns the interfaces available through Winpcap/Npcap. Those are the interfaces we are able to use, but we need the other infos to make it work.

Please try `get_if_list()` you will certainly see that the interface you are looking for isn’t available from Winpcap/Npcap, even if it is listed in Windows interfaces. It means that scapy cannot use it.

That’s not scapy’s fault, have a look at the compatibility between your adapter and Npcap/Winpcap.

You can try switching to Npcap if you are using Winpcap, or the opposite (which is less likely to work and less recommanded)

**Comment by Alokadev** [comment]
1. python 2.7.2 from python.org
2. Microsoft Visual C++ Compiler for Python 2.7 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266.
3. pip install scapy==2.4.3rc1
4. winpcap 

Install python 2.7.2 and then install Microsoft Visual C++ Compiler for Python 2.7

**Comment by daven238** [comment]
On Windows with pcap installed...

If you need to generate a list of interface names that scapy will accept from the information provided by get_if_list() and get_windows_if_list(), here is the python code I use:

```
winList = get_windows_if_list()
intfList = get_if_list()

# Pull guids and names from the windows list
guidToNameDict = { e["guid"]: e["name"] for e in winList}

# Extract the guids from the interface list
guidsFromIntfList = [(e.split("_"))[1] for e in intfList]

# Using the interface list of guids, pull the names from the
# Windows map of guids to names
namesAllowedList = [guidToNameDict[e] for e in guidsFromIntfList]
```
