### ISSUE TITLE
Exception raised when ._fix() is called on fuzzed TCP flags

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#1576]
#### Brief description

An exception raised when ._fix() is called on fuzzed TCP flags. 

TCP is affected by this. 

#### Environment

- Scapy version: 2.4.0.dev115
- Python version: Python 3.6.5rc1
- Operating System: Kali Linux

#### How to reproduce

```
ubuntu:/$ scapy
... (welcome info omitted)
>>> p = IP()/TCP()
>>> p = fuzz(p)
>>> p["IP"].show()
###[ IP ]###
  version= <RandNum>
  ihl= None
  tos= 98
  len= None
  id= <RandShort>
  flags= DF+evil
  frag= 0
  ttl= <RandByte>
  proto= tcp
  chksum= None
  src= 127.0.0.1
  dst= 127.0.0.1
  \options\
###[ TCP ]###
     sport= <RandShort>
     dport= <RandShort>
     seq= <RandInt>
     ack= <RandInt>
     dataofs= None
     reserved= <RandNum>
     flags= SAUC
     window= <RandShort>
     chksum= None
     urgptr= <RandShort>
     options= []
# You can query flags repeatedly to see that it's indeed a random value
>>> p["TCP"].flags
<Flag 163 (FSUC)>
>>> p["TCP"].flags
<Flag 414 (SRPACN)>
# But if you try to _fix() it, like you can with other parts of the packet:
>>> p["TCP"].flags._fix()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scapy/fields.py", line 1497, in __getattr__
    for flag in attr)
  File "/usr/local/lib/python3.6/dist-packages/scapy/fields.py", line 1497, in <genexpr>
    for flag in attr)
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/scapy/fields.py", line 1499, in __getattr__
    return super(FlagValue, self).__getattr__(attr)
AttributeError: 'super' object has no attribute '__getattr__'
```

#### Actual result

AttributeError/ValueError is raised.

#### Expected result

The expected result is just a fixed integer or string value, representing what a random flag value is. 

Let me know if I'm just doing something stupid, or if there's any other info I can provide!

**Comment by p-l-** [comment]
The problem is `p.flags` should return a volatile value instead of a value. I'll have a look.

**Comment by p-l-** [comment]
Thanks @Kkevsterrr for this report
