### ISSUE TITLE
Exception raised when a payload is given for the TCP payload on .show()

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#1578]
#### Brief description

An exception is raised if .show() is called on a packet with a TCP payload manually defined. 

TCP is affected.
#### Environment

- Scapy version: 2.4.0
- Python version: 3.6
- Operating System: Mac OS, Kali Linux (can reproduce on both)

#### How to reproduce

``` 
# scapy
>>>
>>> p = IP()/TCP() # Define a new IP/TCP packet
>>> p[TCP]  # Check that packet has a TCP layer 
<TCP  |>
>>> p[TCP].payload # Check the TCP payload is empty

>>> p[TCP].payload = 444 # Assign a new TCP payload
>>> p.show()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 1067, in show
    return self._show_or_dump(dump, indent, lvl, label_lvl)
  File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 1049, in _show_or_dump
    s += self.payload._show_or_dump(dump=dump, indent=indent, lvl=lvl + (" " * indent * self.show_indent), label_lvl=label_lvl, first_call=False)
  File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 1049, in _show_or_dump
    s += self.payload._show_or_dump(dump=dump, indent=indent, lvl=lvl + (" " * indent * self.show_indent), label_lvl=label_lvl, first_call=False)
AttributeError: 'int' object has no attribute '_show_or_dump'
>>> # ^Exception
```
I can reproduce this if I give a bytes() payload, a string payload, or an integer payload. 
```
>>> p = IP()/TCP()
>>> p[TCP].payload = b"testing"
>>> p.show()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 1102, in show
    return self._show_or_dump(dump, indent, lvl, label_lvl)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 1084, in _show_or_dump
    s += self.payload._show_or_dump(dump=dump, indent=indent, lvl=lvl + (" " * indent * self.show_indent), label_lvl=label_lvl, first_call=False)  # noqa: E501
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 1084, in _show_or_dump
    s += self.payload._show_or_dump(dump=dump, indent=indent, lvl=lvl + (" " * indent * self.show_indent), label_lvl=label_lvl, first_call=False)  # noqa: E501
AttributeError: 'bytes' object has no attribute '_show_or_dump'
>>>
```
#### Actual result

AttributeError is raised. 

#### Expected result

TCP payload is set and displayed. 

Can the TCP payload not be used anymore?

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/issues/1579
