### ISSUE TITLE
Exception raised when a payload is given for the TCP payload on str(packet)

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#1579]
#### Brief description

This is likely related to #1578 - thank you all in advance for your patience and help! An exception is raised if str() is called on a packet that has had a TCP payload assigned. 

TCP is affected. 

#### Environment

- Scapy version: 2.4.0
- Python version: 3.6
- Operating System: Mac OS, Kali Linux

#### How to reproduce

```
# scapy
>>> p = IP()/TCP() # create a new empty packet
>>> str(p) # check the string representation 
"b'E\\x00\\x00(\\x00\\x01\\x00\\x00@\\x06|\\xcd\\x7f\\x00\\x00\\x01\\x7f\\x00\\x00\\x01\\x00\\x14\\x00P\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00P\\x02 \\x00\\x91|\\x00\\x00'"
>>> p[TCP].payload = b"testing" # assign a bytes payload 
>>> str(p) # get the new string representation 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 353, in __str__
    return str(self.build())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 463, in build
    p = self.do_build()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 444, in do_build
    self = next(iter(self))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 842, in loop
    for payl in payloads:
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 847, in loop
    pkt = self.clone_with(payload=payl, **done2)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 820, in clone_with
    pkt.add_payload(payload)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/packet.py", line 194, in add_payload
    raise TypeError("payload must be either 'Packet' or 'bytes', not [%s]" % repr(payload))  # noqa: E501
TypeError: payload must be either 'Packet' or 'bytes', not [116]
>>>
```

#### Actual result

TypeError is raised. 

#### Expected result

The payload is printed with the payload.

**Comment by gpotter2** [comment]
The payload is not correct.
Indeed, the `payload` means the Packet class below the current layer.

It could be `Raw(b'abc')` or (but not a string or an int).

Anyway except if you know what you are doing, you are NOT supposed to assign ˋpayload` manually, but instead use the `/` operator

```python
a = IP()/TCP()
a = a/b”data”
```

**Comment by Kkevsterrr** [comment]
Thanks for the quick response @gpotter2 . I'm looking at packets over the wire, and trying to replace the packet payload. I see many TCP packets that don't have a Raw layer, but have a payload assigned (and it reports the type of that payload as bytes(), not as Raw().) Might be worth updating some documentation to identify packet[TCP].payload as an anomalous field, since it's the only field you can't directly assign to (to my knowledge)
