### ISSUE TITLE
error: cannot convert argument to integer

### ISSUE THREAD

**Issue by sgeto** [secdev/scapy#1587]
#### Things to consider

1. Please check that you are using the latest scapy version, e.g. installed via:

   `pip install https://github.com/secdev/scapy`

2. If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: https://gitter.im/secdev/scapy

3. Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

#### Brief description

Generating DHCP Discoveries using [DHCPig](https://github.com/kamorin/DHCPig) errors in "recent" versions of scapy.

#### Environment

- Scapy version: 2.3.3.dev1757 and earlier
- Python version: tried python 2.7.12 and 3.5.2/3.6.0
- Operating System: Ubuntu 16.04 and Windows 10

#### How to reproduce

1. get/install scapy
2. clone/install [DHCPig](https://github.com/kamorin/DHCPig)
3. run [DHCPig](https://github.com/kamorin/DHCPig): python pig.py -c eth0 
#### Actual result

```
root@CALCULANO:~/projects/DHCPig# python pig.py -c eth0
[ -- ] [INFO] - using interface eth0
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "pig.py", line 527, in run
    sendPacket(dhcp_discover)
  File "pig.py", line 423, in sendPacket
    sendp(pkt, iface=conf.iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 374, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)  # noqa: E501
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 333, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 524, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/supersocket.py", line 45, in send
    sx = raw(x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/compat.py", line 93, in raw
    return x.__bytes__()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 368, in __bytes__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 475, in build

    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 460, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 447, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 460, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 447, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 460, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 447, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 460, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 447, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 457, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 438, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 895, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dhcp.py", line 281, in i2m
    oval = b"".join(lval)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dhcp.py", line 278, in <genexpr>
    lval = (f.addfield(pkt, b"", f.any2i(pkt, val)) for val in lval)  # noqa: E501
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 1263, in addfield
    s = self.field.addfield(pkt, s, v)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 132, in addfield
    return s + struct.pack(self.fmt, self.i2m(pkt, val))
error: cannot convert argument to integer
```
#### Expected result
```
root@CALCULANO:~/projects/DHCPig# python pig.py -c eth0
[ -- ] [INFO] - using interface eth0
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
...you get the idea
```
#### Related resources

https://github.com/kamorin/DHCPig

**Comment by guedou** [comment]
Please report this issue to DHCPig, or reduce the issue to something that we can handle without reading DHCPig source code. Thanks.
