### ISSUE TITLE
"Layer [Dot11] not found" error

### ISSUE THREAD

**Issue by sa7mon** [secdev/scapy#1590]
#### Brief description

Attempting to get the MAC address from a Dot11 packet raises an IndexError. 

#### Environment

- Scapy version: 2.4.0.dev422
- Python version: 3.6.6
- Operating System: Kali Linux 2018-01-08

#### How to reproduce

* In a virtualenv, run `pip install scapy` which should grab 2.4.0.
* Run the following code, editing the interface for your own:

```python
from scapy.all import *

# process unique sniffed Beacons and ProbeResponses.
def sniffAP(p):
    if p.haslayer(Dot11Beacon) or p.haslayer(Dot11ProbeResp):
        mac = p[Dot11].addr3
        print(mac)

# Start the sniffer
sniff(iface='wlan0mon', prn=sniffAP, store=0)
```
* This should start printing tons of MAC addresses.
* Now `pip uninstall scapy` and then `pip install git+https://github.com/secdev/scapy.git`
* Run the script again and observe the following error:
```python
Traceback (most recent call last):
  File "./scapyTest.py", line 12, in <module>
    sniff(iface='wlan0mon', prn=sniffAP, store=0)
  File "/root/scapy-venv3/lib/python3.6/site-packages/scapy/sendrecv.py", line 944, in sniff
    r = prn(p)
  File "./scapyTest.py", line 8, in sniffAP
    mac = p[Dot11].addr3
  File "/root/scapy-venv3/lib/python3.6/site-packages/scapy/packet.py", line 1065, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Dot11] not found
```

Has the syntax for packets changed since the 2.4.0 tagged release?

Thanks!

**Comment by guedou** [comment]
Please provide an example for the packet triggering the error. Your code seems incomplete, you need to check that the packet as a Dot11 layer before trying to access its field.

**Comment by sa7mon** [comment]
Whoops, sorry about that. The check for Dot11 is working just fine, here's an example packet:

```
###[ RadioTap dummy ]### 
  version   = 0
  pad       = 0
  len       = 36
  present   = TSFT+Flags+Rate+Channel+dBm_AntSignal+RXFlags+RadiotapNS+Ext
  \Ext       \
   |###[ RadioTap Extended presence mask ]### 
   |  present   = b5+b11
  mac_timestamp= 9910055600027336704
  Flags     = FCS
  Rate      = 2
  Channel   = 2432
  ChannelFlags= CCK+2GHz
  dBm_AntSignal= -71dBm
  notdecoded= '\x00\x00\x00\xb9\x00'
###[ 802.11-FCS ]### 
     subtype   = 8
     type      = Management
     proto     = 0
     FCfield   = 
     ID        = 0
     addr1     = ff:ff:ff:ff:ff:ff
     addr2     = 26:a4:3c:04:da:0f
     addr3     = 26:a4:3c:04:da:0f
     SC        = 9200
     fcs       = 0x637e1e18
###[ 802.11 Beacon ]### 
        timestamp = 2577274777984
        beacon_interval= 100
        cap       = short-slot+ESS+privacy+short-preamble
###[ 802.11 Information Element ]### 
           ID        = SSID
           len       = 0
           info      = ''
###[ Rates ]### 
              ID        = 1
              len       = 8
              rates     = [0x82, 0x84, 0x8b, 0x96, 0x8c, 0x12, 0x98, 0x24]
###[ 802.11 Information Element ]### 
                 ID        = DSset
                 len       = 1
                 info      = '\x06'
###[ 802.11 Information Element ]### 
                    ID        = TIM
                    len       = 4
                    info      = '\x01\x03\x00\x00'
###[ 802.11 Information Element ]### 
                       ID        = ERPinfo
                       len       = 1
                       info      = '\x00'
###[ 802.11 Information Element ]### 
                          ID        = ESRates
                          len       = 4
                          info      = '\xb0H`l'
###[ 802.11 Information Element ]### 
                             ID        = 11
                             len       = 5
                             info      = '\x00\x00\x81\x00\x00'
###[ 802.11 Information Element ]### 
                                ID        = HTCapabilities
                                len       = 26
                                info      = '\xac\x01\x03\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Information Element ]### 
                                   ID        = 61
                                   len       = 22
                                   info      = '\x06\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Information Element ]### 
                                      ID        = ExtendendCapatibilities
                                      len       = 8
                                      info      = '\x00\x00\x00\x00\x00\x00\x00@'
###[ Vendor Specific ]### 
                                         ID        = 221
                                         len       = 24
                                         oui       = 0x50f2
                                         info      = "\x02\x01\x01\x00\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00"
###[ Vendor Specific ]### 
                                            ID        = 221
                                            len       = 9
                                            oui       = 0x37f
                                            info      = '\x01\x01\x00\x00\xff\x7f'
###[ Vendor Specific ]### 
                                               ID        = 221
                                               len       = 24
                                               oui       = 0x156d
                                               info      = '\x00\x01\x01\x08\x01\x02\x07\xe5\x81\x06$\xa4<\x02\xda\x0f\x82\x01\x00\x83\x00'
###[ RSN information ]### 
                                                  ID        = 48
                                                  len       = 20
                                                  version   = 1
                                                  \group_cipher_suite\
                                                   |###[ Cipher suite ]### 
                                                   |  oui       = 0xfac
                                                   |  cipher    = CCMP
                                                  nb_pairwise_cipher_suites= 1
                                                  \pairwise_cipher_suites\
                                                   |###[ Cipher suite ]### 
                                                   |  oui       = 0xfac
                                                   |  cipher    = CCMP
                                                  nb_akm_suites= 1
                                                  \akm_suites\
                                                   |###[ AKM suite ]### 
                                                   |  oui       = 0xfac
                                                   |  suite     = PSK
                                                  pre_auth  = 0
                                                  no_pairwise= 0
                                                  ptksa_replay_counter= 0
                                                  gtksa_replay_counter= 0
                                                  mfp_required= 0
                                                  mfp_capable= 0
                                                  reserved  = 0
```

**Comment by gpotter2** [comment]
The problem is quite simple. Since the latest versions, `Dot11` may also be `Dot11FCS` depending on if there is a FCS or not.

This is considered as a regression, which we could consider fixing by re-uniting the two classes

**Comment by guedou** [comment]
@gpotter2 I agree. I did not find time to do it =/
