### ISSUE TITLE
SNMP decode/encode broken

### ISSUE THREAD

**Issue by bsloane1650** [secdev/scapy#1608]
#### Brief description

Scapy throws an exception on decoding/encoding packet.

The packet in question is a (possibly malformed?) SNMP packet.

#### Environment

- Scapy version: 4d00d637e054341f34cbfeb47d93d7ef479369c6
- Python version: 2.7.15rc1
- Operating System: 18.04

#### How to reproduce

Run scapy in same directory as attached pcap file, then either:

str(rdpcap('snmp_breakScapy.pcap')[0])
or
send(rdpcap('snmp_breakScapy.pcap')[0])

#### Actual result
(for str(...))

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/ram/scapy/scapy/packet.py", line 365, in __str__
    return str(self.build())
  File "/ram/scapy/scapy/packet.py", line 483, in build
    p = self.do_build()
  File "/ram/scapy/scapy/packet.py", line 468, in do_build
    pay = self.do_build_payload()
  File "/ram/scapy/scapy/packet.py", line 455, in do_build_payload
    return self.payload.do_build()
  File "/ram/scapy/scapy/packet.py", line 468, in do_build
    pay = self.do_build_payload()
  File "/ram/scapy/scapy/packet.py", line 455, in do_build_payload
    return self.payload.do_build()
  File "/ram/scapy/scapy/packet.py", line 468, in do_build
    pay = self.do_build_payload()
  File "/ram/scapy/scapy/packet.py", line 455, in do_build_payload
    return self.payload.do_build()
  File "/ram/scapy/scapy/packet.py", line 465, in do_build
    pkt = self.self_build()
  File "/ram/scapy/scapy/asn1packet.py", line 30, in self_build
    return self.ASN1_root.build(self)
  File "/ram/scapy/scapy/asn1fields.py", line 380, in build
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 380, in <lambda>
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 133, in build
    return self.i2m(pkt, getattr(pkt, self.name))
  File "/ram/scapy/scapy/asn1fields.py", line 559, in i2m
    s = raw(x)
  File "/ram/scapy/scapy/compat.py", line 93, in raw
    return x.__bytes__()
  File "/ram/scapy/scapy/packet.py", line 368, in __bytes__
    return self.build()
  File "/ram/scapy/scapy/packet.py", line 483, in build
    p = self.do_build()
  File "/ram/scapy/scapy/packet.py", line 465, in do_build
    pkt = self.self_build()
  File "/ram/scapy/scapy/asn1packet.py", line 30, in self_build
    return self.ASN1_root.build(self)
  File "/ram/scapy/scapy/asn1fields.py", line 380, in build
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 380, in <lambda>
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 430, in build
    s = b"".join(raw(i) for i in val)
  File "/ram/scapy/scapy/asn1fields.py", line 430, in <genexpr>
    s = b"".join(raw(i) for i in val)
  File "/ram/scapy/scapy/compat.py", line 93, in raw
    return x.__bytes__()
  File "/ram/scapy/scapy/packet.py", line 368, in __bytes__
    return self.build()
  File "/ram/scapy/scapy/packet.py", line 483, in build
    p = self.do_build()
  File "/ram/scapy/scapy/packet.py", line 465, in do_build
    pkt = self.self_build()
  File "/ram/scapy/scapy/asn1packet.py", line 30, in self_build
    return self.ASN1_root.build(self)
  File "/ram/scapy/scapy/asn1fields.py", line 380, in build
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 380, in <lambda>
    s = reduce(lambda x, y: x + y.build(pkt), self.seq, b"")
  File "/ram/scapy/scapy/asn1fields.py", line 133, in build
    return self.i2m(pkt, getattr(pkt, self.name))
  File "/ram/scapy/scapy/asn1fields.py", line 109, in i2m
    s = x.enc(pkt.ASN1_codec)
  File "/ram/scapy/scapy/asn1/asn1.py", line 220, in enc
    return self.tag.get_codec(codec).enc(self.val)
  File "/ram/scapy/scapy/asn1/ber.py", line 395, in enc
    lst = [int(x) for x in oid.strip(b".").split(b".")]
ValueError: invalid literal for int() with base 10: ''

#### Expected result

Original packet bytes would be reconstructed.

#### Related resources

[snmp_breakScapy.pcap.gz](https://github.com/secdev/scapy/files/2397623/snmp_breakScapy.pcap.gz)

**Comment by guedou** [comment]
Thanks for reporting this issue. This could be triggered with: `raw(ASN1_OID(""))`
