### ISSUE TITLE
Exceptions when .scapy_history is not readable/writable

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1637]
When `/home/user/.scapy_history` is not readable/writable, Scapy throws exception instead of an error message:
```WARNING: No route found for IPv6 destination :: (no default route?)
[TerminalIPythonApp] ERROR | Failed to create history session in /home/user/.scapy_history. History will not be saved.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 549, in __init__
    self.new_session()
  File "<decorator-gen-22>", line 2, in new_session
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 575, in new_session
    NULL, "") """, (datetime.datetime.now(),))
OperationalError: attempt to write a readonly database
```

To reproduce change the permissions on `.scapy_history`.

**Comment by gpotter2** [comment]
![dd3da38f-a1f0-4c7c-ad2c-7f7188116929](https://user-images.githubusercontent.com/10530980/46904848-0cab7600-ceeb-11e8-9dea-c3e6ec58c2c9.jpeg)

I doubt we have any action on how IPython handles the history :/ On my end however it’s not as messy as on yours

**Comment by guedou** [comment]
You are correct. Newer versions of IPython handles the error more nicely!
