### ISSUE TITLE
Dataofs change can break packet.show2() if checksum is recalculated

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#1665]
#### Brief description

After a packet is created with TCP options, if the dataofs field is reduced, the packet is re-parsed, and checksum deleted, scapy will break. It's not clear to me at all why this happens. This was the result of me trying to write code using scapy to verify packet checksums that arrive on my container. 

TCP is affected by this.

#### Environment

- Scapy version: 2.4.0
- Python version: 3..52
- Operating System: Ubuntu 16.04

Just sending these packets between docker containers when this broke, and I recreated the example below without networking. 

#### How to reproduce

I have pickled the packet I'm looking at so you can play with the exact same object. 

Simple example below: 
```
>>> p = pickle.loads( b'\x80\x03cscapy.layers.inet\nIP\nq\x00)Rq\x01C<E\x00\x00<\xa8\xab@\x00@\x069\xe8\xac\x11\x00\x0x10\x87\xe4\x00\x00\x02\x04\x05\xb4\x04\x02\x08\n\xf7\xa26C\x00\x00\x00\x00\x01\x03\x03\x07q\x02\x85q\x03b.')
>>> p.show()
###[ IP ]### 
  version= 4
  ihl= 5
  tos= 0x0
  len= 60
  id= 43179
  flags= DF
  frag= 0
  ttl= 64
  proto= tcp
  chksum= 0x39e8
  src= 172.17.0.2
  dst= 172.17.0.4
  \options\
###[ TCP ]### 
     sport= 43320
     dport= 21094
     seq= 3330672087
     ack= 0
     dataofs= 10
     reserved= 0
     flags= S
     window= 29200
     chksum= 0x87e4
     urgptr= 0
     options= [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4154603075, 0)), ('NOP', None), ('WScale', 7)]
>>> p["TCP"].dataofs = 8 
>>> p2 = IP(bytes(p))
>>> del p2["TCP"].chksum
>>> p2.show2()
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 1071, in show2
    return self.__class__(raw(self)).show(dump, indent, lvl, label_lvl)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/compat.py", line 96, in raw
    return bytes(x)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/layers/inet.py", line 308, in i2m
    oval = struct.pack(ofmt, *oval)
struct.error: pack expected 2 items for packing (got 1)
>>> raw(p2)
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/compat.py", line 96, in raw
    return bytes(x)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/layers/inet.py", line 308, in i2m
    oval = struct.pack(ofmt, *oval)
struct.error: pack expected 2 items for packing (got 1)
```

#### Actual result

Scapy breaks.

#### Expected result

Scapy shouldn't break.

**Comment by p-l-** [comment]
Sorry, your packet seems wrong:

```
>> p = pickle.loads( b'\x80\x03cscapy.layers.inet\nIP\nq\x00)Rq\x01C<E\x00\x00<\xa8\xab@\x00@\x069\xe8\xac\x11\x00\x0x10\x87\xe4\x00\x00\x02\x04\x05\xb4\x04\x02\x08\n\xf7\xa26C\x00\x00\x00\x00\x01\x03\x03\x07q\x02\x85q\x03b.')
  File "<ipython-input-14-9bf9f0f26567>", line 1
    p = pickle.loads( b'\x80\x03cscapy.layers.inet\nIP\nq\x00)Rq\x01C<E\x00\x00<\xa8\xab@\x00@\x069\xe8\xac\x11\x00\x0x10\x87\xe4\x00\x00\x02\x04\x05\xb4\x04\x02\x08\n\xf7\xa26C\x00\x00\x00\x00\x01\x03\x03\x07q\x02\x85q\x03b.')
                     ^
SyntaxError: (value error) invalid \x escape at position 91
```

Can you fix it?

**Comment by Kkevsterrr** [comment]
Hmm weird that the pickling isn't working. I can reproduce on scapy 2.4.0 with just the following:

```
>>> p = IP()/TCP(options=[('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4154603075, 0)), ('NOP', None), ('WScale', 7)])
>>> p.show2()
###[ IP ]### 
  version= 4
  ihl= 5
  tos= 0x0
  len= 60
  id= 1
  flags= 
  frag= 0
  ttl= 64
  proto= tcp
  chksum= 0x7cb9
  src= 127.0.0.1
  dst= 127.0.0.1
  \options\
###[ TCP ]### 
     sport= ftp_data
     dport= http
     seq= 0
     ack= 0
     dataofs= 10
     reserved= 0
     flags= S
     window= 8192
     chksum= 0xfbb3
     urgptr= 0
     options= [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4154603075, 0)), ('NOP', None), ('WScale', 7)]

>>> p[TCP].dataofs=8
>>> p2 = IP(bytes(p))
>>> del p2["TCP"].chksum
>>> p2.show2()
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 1071, in show2
    return self.__class__(raw(self)).show(dump, indent, lvl, label_lvl)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/compat.py", line 96, in raw
    return bytes(x)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/home/kbock/.local/lib/python3.5/site-packages/scapy/layers/inet.py", line 308, in i2m
    oval = struct.pack(ofmt, *oval)
struct.error: pack expected 2 items for packing (got 1)
>>> 
```

**Comment by p-l-** [comment]
You're right, Scapy should probably issue a waring, and only raise the exception if/when `conf.debug_dissector` is `True`

**Comment by guedou** [comment]
This works as expected with Python2 but fail with Python3:
```
cat test_1665.py 
from scapy.all import *

p = IP()/TCP(options=[('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4154603075, 0)), ('NOP', None), ('WScale', 7)])
p.show2()
p[TCP].dataofs=8
p2 = IP(bytes(p))
del p2["TCP"].chksum

try:
    p2.show2()
except Exception as e:
    sys.stderr.write("Got %s\n" % e)

python3 test_1665.py > /dev/null 
Got pack expected 2 items for packing (got 1)

python2 test_1665.py > /dev/null 
```

**Comment by guedou** [comment]
I submitted #1950. The issue is a missing check in Python3. Thanks for reporting!
