### ISSUE TITLE
Error thrown by cryptography module when calling MACsecSA.decrypt(packet)

### ISSUE THREAD

**Issue by charelF** [secdev/scapy#1676]
Concerns: https://github.com/secdev/scapy/blob/master/scapy/contrib/macsec.py

#### Brief description

Using MACsecSA, I want to simulate the encryption and decryption of a macsec frame. I have so far managed to encrypt a frame, but when decrypting it with the same SA, I get an error message from the cryptography module.

#### Environment

-   Scapy version: `2.4.0`
-   Python version: `3.6.3`
-   Operating System: `Windows 10`

#### How to reproduce

```
from scapy.contrib.macsec import *
from scapy.all import *

sci = b"0x12345678"
an = 0b11
pn = 0x000001
key = b'gG_EqlvD-J4euCPkurDRfx57pqIOyXGr'
icvlen = 16
encrypt = True
send_sci = True

sa = MACsecSA(sci, an, pn, key, icvlen, encrypt, send_sci)

packet = sa.encap(Ether()/Raw("AAAAAAAAAAAAA"))

# packet.show()

encryptedPacket = sa.encrypt(packet)

# encryptedPacket.show()

decryptedPacket = sa.decrypt(encryptedPacket) # causes the problem

# decryptedPacket.show()
```

Running this throws the following error:

#### Actual result

```
Traceback (most recent call last):
  File "D:/GOOGLE DRIVE/School/sem-3-2018/BSP-3/BSP3/Code/anotherTest.py", line 22, in <module>
    decryptedPacket = sa.decrypt(encryptedPacket) # causes the problem
  File "C:\Code\Python\lib\site-packages\scapy\contrib\macsec.py", line 178, in decrypt
    pt += decryptor.finalize()
  File "C:\Code\Python\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 198, in finalize
    data = self._ctx.finalize()
  File "C:\Code\Python\lib\site-packages\cryptography\hazmat\backends\openssl\ciphers.py", line 164, in finalize
    raise InvalidTag
cryptography.exceptions.InvalidTag
```

#### Expected result

I expect that `decryptedPacket `should be the same as `packet`, at least when calling `show()` on them, both should look similar.

#### Related resources

Source code of error throwing library.
https://github.com/pyca/cryptography/blob/3bab819c558ead888825e33f8df3f17707ff2c20/src/cryptography/hazmat/backends/openssl/ciphers.py

**Comment by charelF** [comment]
I don't know if this is too much of a Stackoverflow-like request for help than an actual issue, but I have been trying to look what it could be and could not find the error source. I don't know if my initialisation of the MACsecSA class is incorrect (as there is no documentation detailing which values to input) or If there is a problem with the actual code of the MACsec implementation.

**Comment by charelF** [comment]
Solution:
use this sci: `sci = b'\x52\x54\x00\x13\x01\x56\x00\x01'`

Reasoning by @qsn 

> Your SCI is not the correct length. An SCI must be 8 bytes, yours is 10.
> For example:
> sci=b'\x52\x54\x00\x13\x01\x56\x00\x01'
> (the SCI is typically composed of a MAC address and a "port number",
> in this example 52:54:00:13:01:56 and 0x0001)
> You can find some examples in the regression test I submitted:  scapy/contrib/macsec.uts
