### ISSUE TITLE
scapy send icmp error

### ISSUE THREAD

**Issue by sevck** [secdev/scapy#1677]
I download releease version
system: mac os 10.13.2
python version: python2.7 \python3

Download and install is success.
but, use:
running install_scripts
```
copying build/scripts-3.6/scapy -> /Library/Frameworks/Python.framework/Versions/3.6/bin
copying build/scripts-3.6/UTscapy -> /Library/Frameworks/Python.framework/Versions/3.6/bin
changing mode of /Library/Frameworks/Python.framework/Versions/3.6/bin/scapy to 755
changing mode of /Library/Frameworks/Python.framework/Versions/3.6/bin/UTscapy to 755
running install_data
copying doc/scapy.1.gz -> /Library/Frameworks/Python.framework/Versions/3.6/share/man/man1
running install_egg_info
Writing /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy-git_archive.devae348f861-py3.6.egg-info
 xxx@MacBook-Pro  ~/Downloads/chrome-dowload/scapy-2.4.0  sudo scapy
WARNING: Cannot read wireshark manuf database
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
WARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.

                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version git-archive.devae348f861
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | To craft a packet, you have to be a
       scccccp///pSP///p          p//Y   | packet, and learn how to swim in
      sY/////////y  caa           S//P   | the wires and in the waves.
       cayCyayP//Ya              pY/Ya   |        -- Jean-Claude Van Damme
        sY/PsY////YCc          aC//Yp    |
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs

>>> send(IP(dst="10.6.18.79",options=[IPOption("A"*8)])/TCP(dport=2323,options=[(19,"1"*18),(19,"2"*18)]))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/sendrecv.py", line 300, in send
    socket = conf.L3socket(*args, **kargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/arch/bpf/supersocket.py", line 58, in __init__
    (self.ins, self.dev_bpf) = get_dev_bpf()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scapy/arch/bpf/core.py", line 98, in get_dev_bpf
    raise Scapy_Exception("No /dev/bpf handle is available !")
scapy.error.Scapy_Exception: No /dev/bpf handle is available !
>>>
```

tools tips scapy.error.Scapy_Exception:No /dev/bpf handle is available !

look /dev/bpf
```
xxx@MacBook-Pro  ~  ls -al /dev|grep bpf
crw-rw-r--   1 root   admin           23,   0  9 11 14:27 bpf0
crw-rw-r--   1 root   admin           23,   1  9 11 14:27 bpf1
crw-rw----   1 root   admin           23,  10  9 26 09:49 bpf10
crw-rw-r--   1 root   admin           23,   2  9 25 13:56 bpf2
crw-rw-r--   1 root   admin           23,   3  9 24 22:14 bpf3
crw-rw-r--   1 root   admin           23,   4  9 13 11:07 bpf4
crw-rw-r--   1 root   admin           23,   5  9 25 18:39 bpf5
crw-rw-r--   1 root   admin           23,   6  9 25 18:39 bpf6
crw-rw-r--   1 root   admin           23,   7  9 25 18:39 bpf7
crw-rw-r--   1 root   admin           23,   8 10 30 21:58 bpf8
crw-rw----   1 root   admin           23,   9 10 23 09:59 bpf9
```

**Comment by guedou** [comment]
Could you try with current master? A similar issue was already fixed.

**Comment by guedou** [comment]
I did not manage to reproduce this issue on 10.14.1w with the current master.
