### ISSUE TITLE
Setting IP flags to '' directly raises an exception

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#1680]
#### Brief description

If you set IP flags directly to an empty string (should be 0, no flags), scapy raises an exception.
IP is affected by this. 

#### Environment

-   Scapy version: 2.4.0
-   Python version: 3.5.2
-   Operating System: Ubuntu 16.04

#### How to reproduce

```
>>> p[IP].flags = ""
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/packet.py", line 264, in __setattr__
    return self.setfieldval(attr,val)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/packet.py", line 249, in setfieldval
    self.fields[attr] = any2i(self, val)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1362, in any2i
    return self._fixup_val(super(FlagsField, self).any2i(pkt, x))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1359, in _fixup_val
    return x if x is None or isinstance(x, FlagValue) else FlagValue(x, self.names)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1246, in __init__
    self.value = self._fixvalue(value)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1240, in _fixvalue
    y |= 1 << self.names.index(i)
ValueError: '' is not in list
>>> p[IP].flags = 0                    # BUT, you can set it to zero to achieve the same effect.
>>> str(p[IP].flags)
''
>>> p = IP()/TCP()
>>> p[IP].flags = 1                   # And other numerical values work
>>> str(p[IP].flags)
'MF'
>>> setattr(p[IP], "flags", "")    # Going through setattr also does not work
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/packet.py", line 264, in __setattr__
    return self.setfieldval(attr,val)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/packet.py", line 249, in setfieldval
    self.fields[attr] = any2i(self, val)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1362, in any2i
    return self._fixup_val(super(FlagsField, self).any2i(pkt, x))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1359, in _fixup_val
    return x if x is None or isinstance(x, FlagValue) else FlagValue(x, self.names)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1246, in __init__
    self.value = self._fixvalue(value)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scapy/fields.py", line 1240, in _fixvalue
    y |= 1 << self.names.index(i)
ValueError: '' is not in list 
```
#### Actual result

Scapy throws an exception.

#### Expected result

Scapy should not throw an exception.

**Comment by gpotter2** [comment]
This behavior is expected. Flags are not strings in the real world, they are numeral. When you assign a string to a flag, you expect scapy to do name-resolution for you.

It is expected to return an error if the name resolution failed. If you wanted to set an invalid value, use the numeral assignment

**Comment by Kkevsterrr** [comment]
The name resolution should not fail - empty string is a valid string representation of a lack of flags (or an all 0 flags field). Existing behavior already partially supports this, right?

```
>>> p[IP].flags = 0                   
>>> str(p[IP].flags)
''
```

**Comment by gpotter2** [comment]
Ok, I guess we could allow that. I especially didn’t liked how we handled `None` before, so it needed a fix anyways.

Thanks for the report

https://github.com/secdev/scapy/pull/1681/files
