### ISSUE TITLE
Error with ./run_tests_py2

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1712]
run_tests_py2 crashes with an error:

```
cd test ; PYTHONPATH=../ ./run_tests_py2 -n 1-5 -t regression.uts -f HTML -o /tmp/scapy.html -l
### Booting scapy...
### Starting tests...
### Loading: regression.uts
passed 97666AA5 Test module version detection
passed 19EC7768 List layers
passed FE0F029B List layers - advanced
passed B614219C List commands
passed AD124E63 List contribs
Campaign CRC=BEEF6A18  SHA=2BC3E89113B29117492B8BC0C11C8EFD1D4411D0
PASSED=5 FAILED=0
### Writing output...
Traceback (most recent call last):
  File "./../scapy/tools/UTscapy.py", line 989, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./../scapy/tools/UTscapy.py", line 957, in main
    glob_output = pack_html_campaigns(runned_campaigns, glob_output, LOCAL, glob_title)
  File "./../scapy/tools/UTscapy.py", line 628, in pack_html_campaigns
    External_Files.UTscapy_js.write(os.path.dirname(test_campaign.output_file.name))  # noqa: E501
AttributeError: 'str' object has no attribute 'name'
```

**Comment by gpotter2** [comment]
Is that the whole error ? Seems like the bottom is missing :/

**Comment by guedou** [comment]
@gpotter2 I modified the output of the command. We can now see the AttributError.
