### ISSUE TITLE
unable to set Advertising Data

### ISSUE THREAD

**Issue by ygtat** [secdev/scapy#1743]
Hi,
I can't set Advertising Data (HCI_Cmd_LE_Set_Advertising_Data) and Scan Response Data (HCI_Cmd_LE_Set_Scan_Response_Data) with scapy.  and I got the error message:

```
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    sock.send_command(HCI_Hdr()/HCI_Command_Hdr()/HCI_Cmd_LE_Set_Advertising_Data("\x02\x01\x02\x06\x09\x41\x41\x41\x41\x00"))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/bluetooth.py", line 1120, in send_command
    raise BluetoothCommandError("Command %x failed with %x" % (opcode, r.status))
scapy.layers.bluetooth.BluetoothCommandError: Command 2008 failed with 12
```
I got the same error when testing on multiple systems. Is this a bug in scapy? Or..my code is wrong？

My  code for test is as below:

```
import os
import sys
from fcntl import ioctl
import logging as log
import time
import socket as s
from scapy.layers.bluetooth import *
from select import select


class HCIConfig(object):
    @staticmethod
    def down(iface):
        # 31 => PF_BLUETOOTH
        # 0 => HCI_CHANNEL_USER
        # 0x400448ca => HCIDEVDOWN
        sock = s.socket(31, s.SOCK_RAW, 1)
        ioctl(sock.fileno(), 0x400448ca, iface)
        sock.close()
        return True

    @staticmethod
    def up(iface):
        sock = s.socket(31, s.SOCK_RAW, iface)
        # TODO
        # ioctl(sock.fileno(), HCIDEVUP, 0)
        sock.close()
        return False

def get_socket(adapter):
    try:
        return BluetoothUserSocket(adapter)
    except BluetoothSocketError as e:
        log.debug("[!] Creating socket failed: %s\n" % (repr(e)))
        if os.getuid() > 0:
            log.error("[!] Are you definitely root? detected uid: %d\n" % (os.getuid()))
        else:
            log.debug("[+] have root, attempting to take iface down\n")
            HCIConfig.down(adapter)
            try:
                return BluetoothUserSocket(adapter)
            except BluetoothSocketError as e:
                print e
                log.error("[!] Failed to create socket: %s" % repr(e))
                log.error("[!] Giving up.\n")
    sys.exit(1)



sock=get_socket(0)

sock.send_command(HCI_Hdr()/HCI_Command_Hdr()/HCI_Cmd_LE_Set_Advertising_Data("\x02\x01\x02\x06\x09\x41\x41\x41\x41\x00"))
sock.send_command(HCI_Hdr()/HCI_Command_Hdr()/HCI_Cmd_LE_Set_Advertise_Enable(enable=True))

time.sleep(10000)
```

**Comment by gpotter2** [comment]
The `send_command` waits for an answer, and raises an error if the command sent was rejected. See it’s sourcecode below.
```python
def send_command(self, cmd):
        opcode = cmd.opcode
        self.send(cmd)
        while True:
            r = self.recv()
            if r.type == 0x04 and r.code == 0xe and r.opcode == opcode:
                if r.status != 0:
                    raise BluetoothCommandError("Command %x failed with %x" % (opcode, r.status))  # noqa: E501
                return r
```

I’m guessing the command you asked isn’t supported by the device

**Comment by ygtat** [comment]
Thanks! 

At first, I also thought it was a problem with the bluetooth device. But there is no problem if I send HCI_Cmd_LE_Set_Advertise_Enable command , and it can enable ble advertising. It just doesn't support send HCI_Cmd_LE_Set_Advertising_Data  and HCI_Cmd_LE_Set_Scan_Response_Data command.

And if my bluetooth adaptor is not supported, is there any supported Bluetooth adapter recommended? I have tried three bluetooth adapter.

**Comment by gpotter2** [comment]
There is no recommandés adapter as of Scapy. We rely on other softwares / Python to provide the sockets to devices, such don’t have any effect on that.

The Bluetooth stack is being extensively reworked by an amazing job by @ micolous . That might help
