### ISSUE TITLE
Scapy all import fails on FreeBSD

### ISSUE THREAD

**Issue by ykvch** [secdev/scapy#1793]
scapy version initially reproduced: 2.4.1
OS: FreeBSD 12

**Steps:**
1. Run code `from scapy.all import *`

**Expected:**
1. Modules imported

**Actual:**  
Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venv/lib/python3.6/site-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/home/user/venv/lib/python3.6/site-packages/scapy/arch/__init__.py", line 63, in <module>
    conf.use_bpf = True
  File "/home/user/venv/lib/python3.6/site-packages/scapy/config.py", line 75, in __set__
    self.hook(self.name, val, *self.args, **self.kargs)
  File "/home/user/venv/lib/python3.6/site-packages/scapy/config.py", line 491, in _socket_changer
    _set_conf_sockets()
  File "/home/user/venv/lib/python3.6/site-packages/scapy/config.py", line 436, in _set_conf_sockets
    raise ScapyInvalidPlatformException("Darwin (OSX) only !")
scapy.error.ScapyInvalidPlatformException: Darwin (OSX) only !
```

**Note:** probably caused by check here:
https://github.com/secdev/scapy/blob/v2.4.1/scapy/config.py#L434
Which appears to assume that BPF is exclusively used on OSX.
**Note:** FreeBSD (not sure about other *BSD OSes) also uses _/dev/bpf_

**Comment by gpotter2** [comment]
Totally my fault :/ sorry for the inconvenience

Caused by 
https://github.com/secdev/scapy/commit/22a92a8a56de53875deb2d4bcf7e3533c5d85062

@guedou

**Comment by ykvch** [comment]
Since most bsd-like seem to have similar bpf behaviour
My quick guess would be a patch like this:
```
diff --git a/scapy/config.py b/scapy/config.py
index 7df2bdf0..12b221ab 100755
--- a/scapy/config.py
+++ b/scapy/config.py
@@ -16,7 +16,7 @@ import socket
 import sys
 
 from scapy import VERSION, base_classes
-from scapy.consts import DARWIN, WINDOWS, LINUX
+from scapy.consts import DARWIN, WINDOWS, LINUX, BSD
 from scapy.data import ETHER_TYPES, IP_PROTOS, TCP_SERVICES, UDP_SERVICES, \
     MANUFDB
 from scapy.error import log_scapy, warning, ScapyInvalidPlatformException
@@ -431,9 +431,9 @@ def _set_conf_sockets():
     """Populate the conf.L2Socket and conf.L3Socket
     according to the various use_* parameters
     """
-    if conf.use_bpf and not DARWIN:
+    if conf.use_bpf and not BSD:
         Interceptor.set_from_hook(conf, "use_bpf", False)
-        raise ScapyInvalidPlatformException("Darwin (OSX) only !")
+        raise ScapyInvalidPlatformException("BSD-like (OSX) only !")
     if conf.use_winpcapy and not WINDOWS:
         Interceptor.set_from_hook(conf, "use_winpcapy", False)
         raise ScapyInvalidPlatformException("Windows only !")
```
Have to test it though. Possibly there's more than just one check in that logic.
