### ISSUE TITLE
Catch OSError exceptions when pdflatex is not installed

### ISSUE THREAD

**Issue by martingalloar** [secdev/scapy#1801]
#### Brief description

`OSError` exceptions are not being catched in `v2.4.2` if `pdflatex` is not available.

I think this was properly solved in https://github.com/secdev/scapy/commit/0f799ca889078ae8ff1b719777f5fb450a613409 but #1740 brought it back to the code in v2.4.1/v2.4.2.

#### Environment

-   Scapy version: `v2.4.2`
-   Python version: `2.7.15rc1`
-   Operating System: `Ubuntu 18.04.1`

Running in an environment without `pdflatex` installed.

#### How to reproduce

1. `pip install scapy==2.4.2`
2. `python -c "from scapy.packet import Packet"`

#### Actual result

```
$ python -c "from scapy.packet import Packet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/martin/.virtualenvs/pysap2/local/lib/python2.7/site-packages/scapy/packet.py", line 28, in <module>
    from scapy.extlib import PYX
  File "/home/martin/.virtualenvs/pysap2/local/lib/python2.7/site-packages/scapy/extlib.py", line 54, in <module>
    if _test_pyx():
  File "/home/martin/.virtualenvs/pysap2/local/lib/python2.7/site-packages/scapy/extlib.py", line 45, in _test_pyx
    stdout=devnull, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
$
```

#### Expected result

```
$ python -c "from scapy.packet import Packet"
$
```

**Comment by gpotter2** [comment]
Thanks for the report, we’ll have a new release over the weekend (current one has a few critical bugs). Can you confirm that

https://github.com/secdev/scapy/pull/1802/files

Fixes it for you ?

FTR: this only happens when PyX is installed without its dependencies, making it unusable

**Comment by martingalloar** [comment]
Thanks for taking a look so fast, the fix seem to work OK indeed. You're right, this is a not so common scenario as I've PyX installed but without the OS dependencies.
