### ISSUE TITLE
unable to get the length of tcp packet

### ISSUE THREAD

**Issue by zhenxuanfeng** [secdev/scapy#1874]
#### Brief description
Unable to calculate the length of TCP part in a packet in python3

#### Environment

-   Scapy version: `2.4.2`
-   Python version: `3.7.`
-   Operating System: `Windows 10

#### How to reproduce
The code below works well in python2, but failed in python3. 
```python
pcapname="example.pcap'
sniff(offline=pcapname, prn=fun, store=0, count=0)

def fun(packet):
    ...
    print(len(packet['TCP'])
```
And the error information 
```
Traceback (most recent call last):
....
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 476, in __len__
    return len(self.__bytes__())
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 441, in __bytes__
    return self.build()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 556, in build
    p = self.do_build()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 541, in do_build
    pay = self.do_build_payload()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 528, in do_build_payload
    return self.payload.do_build()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 541, in do_build
    pay = self.do_build_payload()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 528, in do_build_payload
    return self.payload.do_build()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy\packet.py", line 538, in do_build
    pkt = self.self_build()
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy_http\http.py", line 179, in self_build
    return _self_build(self, field_pos_list)
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy_http\http.py", line 101, in _self_build
    val = _get_field_value(obj, f.name)
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy_http\http.py", line 74, in _get_field_value
    headers = _parse_headers(val)
  File "D:\ProgramFiles\Anaconda\lib\site-packages\scapy_http\http.py", line 18, in _parse_headers
    headers = s.split("\r\n")
TypeError: a bytes-like object is required, not 'str'
```
I know that the build-in function len() is different in python2 and python3. I've tried encode to translate it into ascii or utf-8 but it didn't work. Any way to solve it? Or any function?

**Comment by gpotter2** [comment]
Hi ! It appears that you are using the `scapy_http` plugin, which is an unofficial Scapy plugin, not included in the source by default.

Please report it over https://github.com/invernizzi/scapy-http

**Comment by zhenxuanfeng** [comment]
@gpotter2  Thank you for replying! I am confused  that whether `scapy`  can apply to analysis http packet.

**Comment by gpotter2** [comment]
It supports HTTP2.0, but has no builtin support (yet) for HTTP1.0
