### ISSUE TITLE
Perhaps a small Bug for scapy 2.4.2 python3.6

### ISSUE THREAD

**Issue by jiohb** [secdev/scapy#1895]
code:
scapy/layers/dns.py: 346
```python
        elif pkt.type == 16:  # TXT
            ret_s = b""
            for text in s:
                # The initial string must be split into a list of strings
                # prepended with theirs sizes.
                while len(text) >= 255:
                    ret_s += b"\xff" + text[:255]
                    text = text[255:]
                # The remaining string is less than 255 bytes long
                if len(text):
                    ret_s += struct.pack("!B", len(text)) + raw(text)
            s = ret_s
```
If I choose dns type=16: text in below will always be int() , so it would's have len() method. here is my error output:

```python
  File "/home/hio/.local/lib/python3.6/site-packages/scapy/layers/dns.py", line 371, in i2m
    x = len(rdataf.i2m(pkt, pkt.rdata))
  File "/home/hio/.local/lib/python3.6/site-packages/scapy/layers/dns.py", line 351, in i2m
    while len(text) >= 255:
TypeError: object of type 'int' has no len()

Process finished with exit code 1

```

You can test it by:

```python
➜  github sudo python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> an = DNSRR(rrname='aaa', type='TXT', rdata="niceday", ttl=1)
>>> send(DNS(id=1,ra=1,an=an))
Traceback (most recent call last):
  File "/home//.local/lib/python3.6/site-packages/scapy/compat.py", line 117, in raw
    return bytes(x)
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 441, in __bytes__
    return self.build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 556, in build
    p = self.do_build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 538, in do_build
    pkt = self.self_build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 519, in self_build
    p = f.addfield(self, p, val)
  File "/home//.local/lib/python3.6/site-packages/scapy/fields.py", line 134, in addfield
    return s + struct.pack(self.fmt, self.i2m(pkt, val))
  File "/home//.local/lib/python3.6/site-packages/scapy/layers/dns.py", line 371, in i2m
    x = len(rdataf.i2m(pkt, pkt.rdata))
  File "/home//.local/lib/python3.6/site-packages/scapy/layers/dns.py", line 351, in i2m
    while len(text) >= 255:
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home//.local/lib/python3.6/site-packages/scapy/compat.py", line 117, in raw
    return bytes(x)
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 441, in __bytes__
    return self.build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 556, in build
    p = self.do_build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 541, in do_build
    pay = self.do_build_payload()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 528, in do_build_payload
    return self.payload.do_build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 538, in do_build
    pkt = self.self_build()
  File "/home//.local/lib/python3.6/site-packages/scapy/packet.py", line 519, in self_build
    p = f.addfield(self, p, val)
  File "/home//.local/lib/python3.6/site-packages/scapy/fields.py", line 905, in addfield
    return s + self.i2m(pkt, val)
  File "/home//.local/lib/python3.6/site-packages/scapy/layers/dns.py", line 255, in i2m
    return raw(x)
  File "/home//.local/lib/python3.6/site-packages/scapy/compat.py", line 119, in raw
    return bytes(x, encoding="utf8")
TypeError: encoding without a string argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home//.local/lib/python3.6/site-packages/scapy/sendrecv.py", line 314, in send
    realtime=realtime, return_packets=return_packets)
  File "/home//.local/lib/python3.6/site-packages/scapy/sendrecv.py", line 287, in __gen_send
    s.send(p)
  File "/home//.local/lib/python3.6/site-packages/scapy/arch/linux.py", line 533, in send
    sx = raw(ll(x))
  File "/home//.local/lib/python3.6/site-packages/scapy/compat.py", line 119, in raw
    return bytes(x, encoding="utf8")
TypeError: encoding without a string argument
>>> 

```

**Comment by guedou** [comment]
Calling `send()` does not make sense, however, I was able to produce an error with a similar code:

```
p = DNS(raw(DNS(id=1,ra=1,an=DNSRR(rrname='aaa', type='TXT', rdata="niceday", ttl=1))))
p.show()

# Python2
###[ DNS ]### 
  id        = 1
  qr        = 0
  opcode    = QUERY
  aa        = 0
  tc        = 0
  rd        = 1
  ra        = 1
  z         = 0
  ad        = 0
  cd        = 0
  rcode     = ok
  qdcount   = 0
  ancount   = 1
  nscount   = 0
  arcount   = 0
  qd        = None
  \an        \
   |###[ DNS Resource Record ]### 
   |  rrname    = 'aaa.'
   |  type      = TXT
   |  rclass    = IN
   |  ttl       = 1
   |  rdlen     = 14
   |  rdata     = ['n', 'i', 'c', 'e', 'd', 'a', 'y']
  ns        = None
  ar        = None

# Python3
###[ DNS ]### 
  id        = 1
  qr        = 0
  opcode    = QUERY
  aa        = 0
  tc        = 0
  rd        = 1
  ra        = 1
  z         = 0
  ad        = 0
  cd        = 0
  rcode     = ok
  qdcount   = 0
  ancount   = 1
  nscount   = 0
  arcount   = 0
  qd        = None
  \an        \
   |###[ DNS Resource Record ]### 
   |  rrname    = 'aaa.'
   |  type      = TXT
   |  rclass    = IN
   |  ttl       = 1
   |  rdlen     = 740
   |  rdata     = [b'\x00\x00
-- CUT --
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
  ns        = None
  ar        = None
```

**Comment by jiohb** [comment]
yes, I check the code. Bug is in:
code:
scapy/layers/dns.py: 346
```python
        elif pkt.type == 16:  # TXT
            ret_s = b""
            for text in s:
                # The initial string must be split into a list of strings
                # prepended with theirs sizes.
                while len(text) >= 255:
                    ret_s += b"\xff" + text[:255]
                    text = text[255:]
                # The remaining string is less than 255 bytes long
                if len(text):
                    ret_s += struct.pack("!B", len(text)) + raw(text)
            s = ret_s
```
when i change the code to 2.4.0:
```python
        elif pkt.type == 16:  # TXT
            #cs change
            if s:
                s = raw(s)
                ret_s = b""
                while len(s)>=255:
                    ret_s += b"\xff" + s[:255]
                    s = s[255:]
                if len(s):
                    ret_s += struct.pack("!B", len(s)) + s
                s = ret_s
```
send function can send dns packet well.

**Comment by Koen1999** [comment]
I am experiencing a similar issue with Python3.6.7 and scapy 2.4.2 on Ubuntu.

The following code 
`    def arp_poison(host_mac, host_ip, host2_ip):
        arp = Ether() / ARP()
        arp[Ether].src = attacker_mac
        arp[ARP].hwsrc = attacker_mac
        arp[ARP].psrc = host2_ip
        arp[ARP].hwdst = host_mac
        arp[ARP].pdst = host_ip
        arp[ARP].op = 'is-at'
        sendp(arp, iface=interface, verbose=show_debug)`
triggers
`  File "main.py", line 71, in arp_poison
    sendp(arp, iface=interface, verbose=show_debug)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 328, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)  # noqa: E501
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 287, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 494, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/dist-packages/scapy/supersocket.py", line 47, in send
    sx = raw(x)
  File "/usr/local/lib/python3.6/dist-packages/scapy/compat.py", line 119, in raw
    return bytes(x, encoding="utf8")
TypeError: encoding without a string argument
`

**Comment by gpotter2** [comment]
@Koen1999 Your issue has nothing do to with this one (which is a DNS specific issue). Please open a new issue or ask on the Gitter.

**Comment by neiljerram** [comment]
@jiohb I've just hit this too, and it is not clear to me why you closed the issue.  Has a fix been merged, and if so has that been released yet?

**Comment by Spiderpig86** [comment]
Bump

**Comment by gpotter2** [comment]
Feel free to open an issue if you bump into a similar bug.
I'm not sure of the history behind this one, as there's no reproducible code exemple.
