### ISSUE TITLE
How to use scapy in jython

### ISSUE THREAD

**Issue by HelloWordCoder** [secdev/scapy#1962]
this is jython easy_install result :
D:\Jython_direction\jython2.7.0\bin>jython easy_install scapy
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:64)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.Py.newString(Py.java:641)
        at org.python.core.Py.fromIOException(Py.java:235)
        at org.python.core.Py.IOError(Py.java:210)
        at org.python.util.jython.run(jython.java:350)
        at org.python.util.jython.main(jython.java:142)

java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value

this is jython's pip install result:
D:\Jython_direction\jython2.7.0\bin>pip install scapy
Traceback (most recent call last):
  File "D:\Jython_direction\jython2.7.0\Lib\runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Jython_direction\jython2.7.0\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Jython_direction\jython2.7.0\bin\pip.exe\__main__.py", line 5, in <module>
  File "D:\Jython_direction\jython2.7.0\Lib\site-packages\pip\__init__.py", line 10, in <module>
    from pip.util import get_installed_distributions, get_prog
  File "D:\Jython_direction\jython2.7.0\Lib\site-packages\pip\util.py", line 17, in <module>
    from pip.locations import (
  File "D:\Jython_direction\jython2.7.0\Lib\site-packages\pip\locations.py", line 109, in <module>
    build_prefix = _get_build_prefix()
  File "D:\Jython_direction\jython2.7.0\Lib\site-packages\pip\locations.py", line 90, in _get_build_prefix
    if file_uid != os.geteuid():
AttributeError: 'module' object has no attribute 'geteuid'

**Comment by gpotter2** [comment]
Please fill up the issue template

**Comment by guedou** [comment]
jython is not supported and there is no plan to do so. If you can make it work, pleas submit a PR. Thanks!
