### ISSUE TITLE
scapy 2.4.2 gives ImportError: cannot import name 'NPCAP_PATH' from 'scapy.arch.pcapdnet' in windows 10

### ISSUE THREAD

**Issue by godomainz** [secdev/scapy#2014]
Environment
OS : Windows 10 Pro
Scapy version: 2.4.2

This does NOT happen in 2.4.0

This is the code I wrote

#!/usr/bin/env python3

```
import scapy.all as scapy

def scan(ip):
    scapy.arping(ip)

scan("192.168.32.0/24")

```

This is the error I got

Traceback (most recent call last):
  File "network_scanner.py", line 3, in <module>
    import scapy.all as scapy
  File "C:\Users\Akila Mendis\Anaconda3\lib\site-packages\scapy\all.py", line 18, in <module>
    from scapy.arch import *
  File "C:\Users\Akila Mendis\Anaconda3\lib\site-packages\scapy\arch\__init__.py", line 67, in <module>
    from scapy.arch.windows import *  # noqa F403
  File "C:\Users\Akila Mendis\Anaconda3\lib\site-packages\scapy\arch\windows\__init__.py", line 56, in <module>
    from scapy.arch.pcapdnet import NPCAP_PATH, get_if_raw_addr, \
ImportError: cannot import name 'NPCAP_PATH' from 'scapy.arch.pcapdnet' (C:\Users\Akila Mendis\Anaconda3\lib\site-packages\scapy\arch\pcapdnet.py)

**Comment by gpotter2** [comment]
Hi,
Could you retry using the master branch ?
See https://scapy.readthedocs.io/en/latest/installation.html#current-development-version

**Comment by godomainz** [comment]
@gpotter2 that also not working. The output I get is this --> `ARP who has ?? says ??`

**Comment by gpotter2** [comment]
This issue is unrelated :/
