### ISSUE TITLE
explore() function yields AssertionError

### ISSUE THREAD

**Issue by thehoneypotter** [secdev/scapy#2241]
I have the following environment:

Ubuntu 18.04 LTS (X86_64)
Python2/3: 2.7.15+/ 3.6.8
Scapy:  Version 2.4.3

When I try to use explore function, I get the following error. 
```
>>> explore()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 1845, in explore
    (six.text_type("Cancel"), "cancel")
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/shortcuts/dialogs.py", line 60, in button_dialog
    with_background=True)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/widgets/dialogs.py", line 32, in __init__
    assert is_formatted_text(title)
AssertionError
```
Besides that I have not found problem with any other modules that I have come across so far.

**Comment by guedou** [comment]
I was able to reproduce on Python2.7 only with:
```
virtualenv -p python2.7 venv
. venv/bin/activate
pip install scapy prompt_toolkit
scapy
>>> explore()
```

**Comment by guedou** [comment]
Could you check that #2242 fixes your issue?

**Comment by sidtechnical** [comment]
I also could reproduce the same issue with python 2.7. #2242 didn't right away resolved the issue, instead, I had to remove `python-scapy` for it to work completely fine.
