### ISSUE TITLE
"pad" byte in Dot11EltCountry is not correct sometimes.

### ISSUE THREAD

**Issue by yananet** [secdev/scapy#2248]
#### Brief description

"pad" byte in Dot11EltCountry is not correct sometimes.
the standards says "pad" byte should be added if the element length is odd number.

but if it is lucky, scapy can parse the correct padding byte,
but if it is not lucky, it detects a wrong pad byte,
thus all the other Dot11Elt after Dot11EltCountry is broken when parsed.

#### Environment

version : 2.4.0
python version : 3.7.4
Operating System : arch linux

#### How to reproduce

1. download sample beacons
https://www.cloudshark.org/captures/39944a6674ee

2. open this using rdpcap
```python
>>> from scapy.all import rdpcap, Dot11EltCountry
>>> a = rdpcap("wireless.pcap")
```
3. pick a sample, 
sample = a[8]

4. show the details, make sure that pad=42, actually there is no padding, or if there is, the padding should be 0.
```python
>>> sample.getlayer(Dot11EltCountry).show()
###[ 802.11 Country ]### 
  ID        = 7
  len       = 6
  country_string= 'US '
  \descriptors\
   |###[ 802.11 Country Constraint Triplet ]### 
   |  first_channel_number= 1
   |  num_channels= 11
   |  mtp       = 30
  pad       = 42                                              <<-- HERE!!
###[ 802.11 Rates ]### 
  ID        = 1
  len       = 6
  rates     = [0x2f, 0x1, 0x6, 0x30, 0x18, 0x1]
###[ 802.11 Information Element ]### 
  ID        = SSID
  len       = 0
  info      = ''
###[ 802.11 Information Element ]### 
  ID        = 15
  len       = 172
  info      = "\x02\x02\x00\x00\x0f\xac\x04\x00\x0f\xac\x02\x01\x00\x00\x0f\xac\x02\x0c\x002\x04\x0c\x12\x18`-\x1a\x1c\x18\x1b\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00=\x16\x06\x00\x13\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdd\t\x00\x10\x18\x02\x00\xf0,\x00\x00\xdd\x1c\x00P\xf2\x01\x01\x00\x00P\xf2\x02\x02\x00\x00P\xf2\x04\x00P\xf2\x02\x01\x00\x00P\xf2\x02\x0c\x00\xdd\x18\x00P\xf2\x02\x01\x01\x80\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00"
>>> 

```
5. make sure that the payload is broken, 
```python
>>> sample.getlayer(Dot11EltCountry).payload.show()
###[ 802.11 Rates ]### 
  ID        = 1
  len       = 6
  rates     = [0x2f, 0x1, 0x6, 0x30, 0x18, 0x1]
###[ 802.11 Information Element ]### 
  ID        = SSID
  len       = 0
  info      = ''
###[ 802.11 Information Element ]### 
  ID        = 15
  len       = 172
  info      = "\x02\x02\x00\x00\x0f\xac\x04\x00\x0f\xac\x02\x01\x00\x00\x0f\xac\x02\x0c\x002\x04\x0c\x12\x18`-\x1a\x1c\x18\x1b\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00=\x16\x06\x00\x13\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdd\t\x00\x10\x18\x02\x00\xf0,\x00\x00\xdd\x1c\x00P\xf2\x01\x01\x00\x00P\xf2\x02\x02\x00\x00P\xf2\x04\x00P\xf2\x02\x01\x00\x00P\xf2\x02\x0c\x00\xdd\x18\x00P\xf2\x02\x01\x01\x80\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00"

>>> 
```

#### Actual result

Please refer the reproduction

#### Expected result

https://www.cloudshark.org/captures/39944a6674ee
select and see packet number 8.
42 is not the padding actually, but Tag Number : ERP Information (42)

#### Related resources

https://www.cloudshark.org/captures/39944a6674ee

**Comment by yananet** [comment]
```python
class Dot11EltCountry(Dot11Elt):
    name = "802.11 Country"
    fields_desc = [
        ByteField("ID", 7),
        ByteField("len", None),
        StrFixedLenField("country_string", b"\0\0\0", length=3),
        PacketListField(
            "descriptors",
            [],
            Dot11EltCountryConstraintTriplet,
            length_from=lambda pkt: (
                pkt.len - 3 - (pkt.len % 3)
            )
        ),
        ConditionalField(
            ByteField("pad", 0),
            lambda pkt: (pkt.len + 1) % 2
        )
    ]

```
I think `ConditionalField` is the misunderstanding.
The standard says the length of the field should be even number, but `pkt.len` includes `pad` byte already.

**Comment by yananet** [comment]
I did some study,
if I redefine the pad byte as following, then it worked as expected.
`descriptors` are 3 bytes, and `pkt.len` also includes more 3 bytes of `country_string`, so I believe this makes sense.
```python
        ConditionalField(
            ByteField("pad", 0),
            lambda pkt: (len(pkt.descriptors) * 3) + 3 != pkt.len
        )
```

**Comment by kuraraneko** [comment]
After the update, Dot11EltCountry reports an error:
```
Python 2.7.15 (default, Aug 22 2018, 16:36:18)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> Dot11EltCountry()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scapy/packet.py", line 447, in __repr__
    if isinstance(f, ConditionalField) and not f._evalcond(self):
  File "scapy/fields.py", line 231, in _evalcond
    return self.cond(pkt)
  File "scapy/layers/dot11.py", line 909, in <lambda>
    lambda pkt: (pkt.len + 1) % 2
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
>>>
```

**Comment by yananet** [comment]
it is not merged yet.
I don’t think the error is related with this.
