### ISSUE TITLE
AttributeError: 'readConnState' object has no attribute 'compression'

### ISSUE THREAD

**Issue by JackYangzg** [secdev/scapy#2273]
_[WARNING] [2019-10-08 09:15:40,180] [error:warning]: [line:97] Unknown cipher suite 10928853 from ClientMasterKey
[WARNING] [2019-10-08 09:15:40,189] [error:warning]: [line:97] Unknown ciphersuite 10928853 from ClientMasterKey
[WARNING] [2019-10-08 09:15:40,195] [error:warning]: [line:97] TLS ciphersuite not usable. Is the cryptography Python module installed ?
[WARNING] [2019-10-08 09:15:40,201] [error:warning]: [line:97] TLS ciphersuite not usable. Is the cryptography Python module installed ?
[ERROR] [2019-10-08 09:15:40,209] [pcapAnalysisProcess:run]: [line:61] pcap analysis exception: 'readConnState' object has no attribute 'compression'
 Traceback (most recent call last):
  File "frameWork\pcapAnalysisProcess.py", line 54, in run
  File "steps\pcapAnalysis.py", line 91, in analysis
  File "steps\pcapAnalysis.py", line 25, in __analysis
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\sendrecv.py", line 1020, in sniff
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\sendrecv.py", line 973, in _run
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\sessions.py", line 270, in on_packet_received
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\sessions.py", line 221, in _process_packet
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\compat.py", line 52, in raw
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\layers\tls\session.py", line 921, in __bytes__
  File "site-packages\scapy-git_archive.devabb56ca88-py3.6.egg\scapy\layers\tls\session.py", line 257, in snapshot
AttributeError: 'readConnState' object has no attribute 'compression'_

**Comment by guedou** [comment]
Please use the template.
