### ISSUE TITLE
KRACK module requires python-cryptography

### ISSUE THREAD

**Issue by ria4** [secdev/scapy#2288]
When `python-cryptography` or `python3-cryptography` packages are not installed, the KRACK module cannot be loaded.

```
>>> load_module("krack")
ERROR: Loading module scapy.modules.krack
Traceback (most recent call last):
  File "/home/ria/scapy/scapy/main.py", line 150, in _load
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ria/scapy/scapy/modules/krack/__init__.py", line 28, in <module>
    from scapy.modules.krack.automaton import KrackAP  # noqa: F401
  File "/home/ria/scapy/scapy/modules/krack/automaton.py", line 7, in <module>
    from cryptography.hazmat.primitives import hashes
ModuleNotFoundError: No module named 'cryptography'
```

Calling @commial to assess whether the module could still offer functionalities with a `crypto_valid` around some blocks. But at first glance I believe a missing `cryptography` should completely prevent importing the module.

https://github.com/secdev/scapy/blob/a58e1b90a704c394216a0b5a864a50931754bdf7/scapy/modules/krack/automaton.py#L6-L10

https://github.com/secdev/scapy/blob/a58e1b90a704c394216a0b5a864a50931754bdf7/scapy/modules/krack/crypto.py#L6-L9

**Comment by commial** [comment]
Hi,

This is indeed needed to install the PMK. I'm not sure the module still has an interest without being able to compute it. So preventing the module to be imported seems the right solution to me.

**Comment by p-l-** [comment]
I do not think this is a bug: you try to use a module => you need a dependency => Python complains with an `ImportError`. What would you expect?

**Comment by ria4** [comment]
It's not a breaking bug indeed. Other modules (TLS, IPsec...) explicitly specify the dependency, I believe it's relevant to do the same here.

**Comment by p-l-** [comment]
@ria4 thanks for your answer!
