### ISSUE TITLE
there is a problem in android

### ISSUE THREAD

**Issue by nrz123** [secdev/scapy#2323]
scapy version is 2.4.3
python version is 3.7.5

my os message
```
# cat /proc/version
Linux version 3.18.66-perf+ (OnePlus@ubuntu-209) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Jun 21 18:18:35 CST 2018
# uname -a
Linux localhost 3.18.66-perf+ #1 SMP PREEMPT Thu Jun 21 18:18:35 CST 2018 aarch64 Android
```

And Libpcap and tcpdump are already installed

There is no error prompt at runtime, but my scapy cannot send any packets, and the following error will be reported at startup

``` 
# scapy
INFO: Can't open /etc/protocols file
INFO: Can't open /etc/services file
INFO: Can't import matplotlib. Won't be able to plot.
INFO: PyX dependencies are not installed ! Please install TexLive or MikTeX.
WARNING: No route found for IPv6 destination :: (no default route?)
ERROR: Loading module scapy.layers.netflow
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scapy/main.py", line 143, in _load
    mod = importlib.import_module(module)
  File "/data/data/com.termux/files/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scapy/layers/netflow.py", line 112, in <module>
    class NetflowRecordV5(Packet):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scapy/layers/netflow.py", line 127, in NetflowRecordV5
    ByteEnumField("prot", IP_PROTOS["tcp"], IP_PROTOS),
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scapy/dadict.py", line 49, in __getitem__
    return getattr(self, attr)
AttributeError: 'DADict' object has no attribute 'tcp'

                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version 2.4.3
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | We are in France, we say Skappee.
       scccccp///pSP///p          p//Y   | OK? Merci.
      sY/////////y  caa           S//P   |             -- Sebastien Chabal
       cayCyayP//Ya              pY/Ya   |
        sY/PsY////YCc          aC//Yp
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 7.9.0
>>> 
```

**Comment by nrz123** [comment]
when i read the code,i find the class DADict is build from the file /etc/protocols,but the android system has no the file,is the file necessary？

**Comment by guedou** [comment]
I don't know if Scapt is supposed to work on Androd. PR #2324 fix the issue with the DADict error.

**Comment by nrz123** [comment]
now i can send packets,because there is no default route in my system,it is ok when i use the appoint route

**Comment by nrz123** [comment]
think you.i think it is ok run on android now,there is no problem

**Comment by p-l-** [comment]
Thanks!

**Comment by Learn-Termux** [comment]
```

**Comment by Learn-Termux** [comment]
```
~ $ scapy
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't open /etc/protocols file
INFO: Can't open /etc/services file
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't import matplotlib. Won't be able to plot.
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/scapy", line 8, in <module>
    sys.exit(interact())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/main.py", line 550, in interact
    SESSION, GLOBKEYS = init_session(session_name, mydict)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/main.py", line 411, in init_session
    importlib.import_module(".all", "scapy").__dict__
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/__init__.py", line 135, in <module>
    _set_conf_sockets()  # Apply config
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/config.py", line 618, in _set_conf_sockets
    conf.ifaces.reload()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/common.py", line 87, in get_if_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied

```

**Comment by polybassa** [comment]
Have you executed Scapy with root privileges?

**Comment by Learn-Termux** [comment]
> Have you executed Scapy with root privileges?

No

**Comment by polybassa** [comment]
Does this error still exist, if you execute scapy with root?

**Comment by Learn-Termux** [comment]
> Have you executed Scapy with root privileges?

Thanks for this hint

**Comment by polybassa** [comment]
Please close this issue, since this is a bug tracker and not a forum. In the future, please ask questions on gitter and only use github issues for actual bugs.
