### ISSUE TITLE
Unable to import private key

### ISSUE THREAD

**Issue by bertouttier** [secdev/scapy#2330]
#### Brief description

Hi all, I have an issue using TLS. I run the following code:
```
from scapy.layers.tls.all import *
ch = TLSClientHello(ciphers=0x0403)
t = TLSClientAutomaton(client_hello=ch, mykey="path/to/key.der")
```

and I get the following error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/cert.py", line 374, in __call__
    privkey = RSAPrivateKey_OpenSSL(obj.der)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 604, in m2i
    p, s = self.extract_packet(self.cls, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 122, in extract_packet
    c = cls(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 101, in m2i
    return codec.dec(s, context=self.context)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 284, in dec
    return cls.do_dec(s, context, safe)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 337, in do_dec
    l, s, t = cls.check_type_check_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 256, in check_type_check_len
    l, s3 = cls.check_type_get_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 248, in check_type_get_len
    s2 = cls.check_type(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 242, in check_type
    (cls.__name__, tag, tag, cls.tag), remaining=s
scapy.asn1.ber.BER_BadTag_Decoding_Error: BERcodec_INTEGER: Got tag [4/0x4] while expecting <ASN1Tag INTEGER[2]>
### Already decoded ###
None
### Remaining ###
b"\x04 \x93\x178\x1a{\xee\x94\xe3\x90\x902\xf3\xd4\xad\xed]\xa4\x1fXc\xf9\x17\xde\xcb\x1b\xb6a=\xc7\t\x1d\xec\xa1D\x03B\x00\x04\xdc\xf5\xdb\\~\xc18]\xdaM\xb6\x04\xc4\xf6\xa5\xe0\xa4\xe2\xa3V k\xfds\xf1%9SpBg\xfd%\x14\x11e\xc2'\x8b\x9bD$\xd1\x06\xcd&!\x94i\xf2\xe7y\xca\xc6\x19\xc2\x92H\xfe\xf7\x92\xf6\x92\xa0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/cert.py", line 380, in __call__
    privkey = ECDSAPrivateKey_OpenSSL(obj.der)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 834, in do_dissect
    s, fval = f.getfield(self, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/x509.py", line 860, in getfield
    i = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 985, in m2i
    return self.cls(m)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 549, in m2i
    return self.extract_packet(choice, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 122, in extract_packet
    c = cls(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 604, in m2i
    p, s = self.extract_packet(self.cls, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 122, in extract_packet
    c = cls(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 101, in m2i
    return codec.dec(s, context=self.context)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 284, in dec
    return cls.do_dec(s, context, safe)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 337, in do_dec
    l, s, t = cls.check_type_check_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 256, in check_type_check_len
    l, s3 = cls.check_type_get_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 248, in check_type_get_len
    s2 = cls.check_type(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 242, in check_type
    (cls.__name__, tag, tag, cls.tag), remaining=s
scapy.asn1.ber.BER_BadTag_Decoding_Error: BERcodec_INTEGER: Got tag [6/0x6] while expecting <ASN1Tag INTEGER[2]>
### Already decoded ###
None
### Remaining ###
b'\x06\x08*\x86H\xce=\x03\x01\x07'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/cert.py", line 387, in __call__
    privkey = RSAPrivateKey(obj.der)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 101, in m2i
    return codec.dec(s, context=self.context)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 284, in dec
    return cls.do_dec(s, context, safe)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 337, in do_dec
    l, s, t = cls.check_type_check_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 256, in check_type_check_len
    l, s3 = cls.check_type_get_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 248, in check_type_get_len
    s2 = cls.check_type(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 242, in check_type
    (cls.__name__, tag, tag, cls.tag), remaining=s
scapy.asn1.ber.BER_BadTag_Decoding_Error: BERcodec_INTEGER: Got tag [48/0x30] while expecting <ASN1Tag INTEGER[2]>
### Already decoded ###
None
### Remaining ###
b"0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x04m0k\x02\x01\x01\x04 \x93\x178\x1a{\xee\x94\xe3\x90\x902\xf3\xd4\xad\xed]\xa4\x1fXc\xf9\x17\xde\xcb\x1b\xb6a=\xc7\t\x1d\xec\xa1D\x03B\x00\x04\xdc\xf5\xdb\\~\xc18]\xdaM\xb6\x04\xc4\xf6\xa5\xe0\xa4\xe2\xa3V k\xfds\xf1%9SpBg\xfd%\x14\x11e\xc2'\x8b\x9bD$\xd1\x06\xcd&!\x94i\xf2\xe7y\xca\xc6\x19\xc2\x92H\xfe\xf7\x92\xf6\x92\xa0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/cert.py", line 392, in __call__
    privkey = ECDSAPrivateKey(obj.der)
  File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 147, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 872, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1packet.py", line 35, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 378, in dissect
    _, x = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 370, in m2i
    s = obj.dissect(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 138, in dissect
    v, s = self.m2i(pkt, s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1fields.py", line 101, in m2i
    return codec.dec(s, context=self.context)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 284, in dec
    return cls.do_dec(s, context, safe)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 403, in do_dec
    l, s, t = cls.check_type_check_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 256, in check_type_check_len
    l, s3 = cls.check_type_get_len(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 248, in check_type_get_len
    s2 = cls.check_type(s)
  File "/usr/local/lib/python3.7/dist-packages/scapy/asn1/ber.py", line 242, in check_type
    (cls.__name__, tag, tag, cls.tag), remaining=s
scapy.asn1.ber.BER_BadTag_Decoding_Error: BERcodec_STRING: Got tag [48/0x30] while expecting <ASN1Tag STRING[4]>
### Already decoded ###
None
### Remaining ###
b"0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x04m0k\x02\x01\x01\x04 \x93\x178\x1a{\xee\x94\xe3\x90\x902\xf3\xd4\xad\xed]\xa4\x1fXc\xf9\x17\xde\xcb\x1b\xb6a=\xc7\t\x1d\xec\xa1D\x03B\x00\x04\xdc\xf5\xdb\\~\xc18]\xdaM\xb6\x04\xc4\xf6\xa5\xe0\xa4\xe2\xa3V k\xfds\xf1%9SpBg\xfd%\x14\x11e\xc2'\x8b\x9bD$\xd1\x06\xcd&!\x94i\xf2\xe7y\xca\xc6\x19\xc2\x92H\xfe\xf7\x92\xf6\x92\xa0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/automaton.py", line 810, in _do_control
    self.parse_args(*a, **k)
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/automaton_cli.py", line 75, in parse_args
    **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/automaton.py", line 72, in parse_args
    self.mykey = PrivKey(mykey)
  File "/usr/local/lib/python3.7/dist-packages/scapy/layers/tls/cert.py", line 397, in __call__
    raise Exception("Unable to import private key")
Exception: Unable to import private key
```

I know that I have my key in the correct DER format. Do you guys know what is the problem?

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7.3
-   Operating System: ubuntu 19.04

**Comment by guedou** [comment]
I did not manage to reproduce the issue using the following commands:
```
openssl rsa -inform pem -outform der -in srv_key.pem -out srv_key.der # srv_key.pem is located in the test/ directory
load_layer("tls"); der2pem(open("srv_key.der", "rb").read(), "RSA PUBLIC KEY")
```

Is your `key.der` file properly recognized by `openssl`?

**Comment by guedou** [comment]
Closed due to no answer.
