### ISSUE TITLE
ARP request fails when pdst field is passed with a CIDR notation

### ISSUE THREAD

**Issue by eckarthik** [secdev/scapy#2333]
#### Description

When i try to make an ARP request by passing network in CIDR notation, it does not work.

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7
-   Operating System: Windows 10

#### Code
```
from scapy.layers.l2 import ARP
ip = "192.168.0.3/24"
arp_request = ARP(pdst=ip)
print(arp_request.summary())
```

#### Actual result

```
ARP who has ?? says ??
```

#### Expected result

```
ARP who has Net('192.168.0.3/24') says 192.168.0.7
```
When i do 
```
print(arp_request.show())
```
I get
```
Traceback (most recent call last):
  File "C:/Users/eckar/Desktop/LearnPythonAndEthicalHacking/NetworkScanner.py", line 4, in <module>
    print(arp_request.show())
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\packet.py", line 1261, in show
    return self._show_or_dump(dump, indent, lvl, label_lvl)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\packet.py", line 1235, in _show_or_dump
    reprval = f.i2repr(self, fvalue)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\fields.py", line 376, in i2repr
    return fld.i2repr(pkt, val)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\fields.py", line 502, in i2repr
    x = self.i2h(pkt, x)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\layers\l2.py", line 136, in i2h
    iff = self.getif(pkt)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\layers\l2.py", line 132, in <lambda>
    self.getif = (lambda pkt: pkt.route()[0]) if getif is None else getif
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\layers\l2.py", line 400, in route
    fld, dst = fld._find_fld_pkt_val(self, dst)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\fields.py", line 313, in _find_fld_pkt_val
    if val == dflts_pkt[self.name] and self.name not in pkt.fields:
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\base_classes.py", line 133, in __eq__
    p2, nm2 = self._parse_net(other)
  File "C:\Users\eckar\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\base_classes.py", line 99, in _parse_net
    tmp = net.split('/') + ["32"]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by illiptic** [comment]
I have the same issue, running on Kali. Both python 2.7 and 3.
Since you closed the ticket, could you share the solution?

**Comment by nikhildr22** [comment]
facing the same issue in Version 2.4.3
