### ISSUE TITLE
Unstable automotive tests

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2350]
@KeksMassacre 
The following to GMLAN Utils-Tests aren't working with ISOTPSoftSockets after a refactoring of ISOTPUnitTests #2341

This is a reminder to fix this unit tests

https://github.com/secdev/scapy/blob/f1e632b9a78029578371d7b27f2f116945da1049/test/contrib/automotive/gm/gmlanutils.uts#L490-L491
https://github.com/secdev/scapy/blob/f1e632b9a78029578371d7b27f2f116945da1049/test/contrib/automotive/gm/gmlanutils.uts#L880-L881

**Comment by gpotter2** [comment]
Please also make sure to properly add the 
`netaccess` and `needs_root` tags in the unit tests. Running `tox` on Ubuntu without sudo will crash because of ISOTP-related tests

**Comment by polybassa** [comment]
I assumed, `vcan_socket` implies `needs_root` and `linux`

**Comment by gpotter2** [comment]
That sounds very reasonable. I'll make sure that's included in the tox files

**Comment by polybassa** [comment]
> Running `tox` on Ubuntu without sudo currently crash because of ISOTP-related tests (at least on my machine)

Did you try the latest tests? I've changed the tests in a way, that they shouldn't need `vcan` anymore. I was able to use python-can virtual interfaces for all tests. This allows the test to be performed even on windows.

**Comment by gpotter2** [comment]
I think it's as simple as: tox doesn't install can-isotp and can-utile but tries to run the tests anyways

**Comment by polybassa** [comment]
Hope this helps #2362

**Comment by gpotter2** [comment]
LGTM.com spotted a missing lambda in
https://github.com/secdev/scapy/blob/b49af41caaea124669228df68876c66007e73175/scapy/contrib/isotp.py#L1900

**Comment by polybassa** [comment]
Thanks a lot

**Comment by polybassa** [comment]
I'm still investigating this case. It seems, that some memory handling in python seem to cause a delay inside an ISOTPSoftSocket thread. This causes packet losses of the receiver thread.

**Comment by polybassa** [comment]
I'm working on this in #2392

**Comment by gpotter2** [comment]
I hope you don't mind but I'll report here each time a ISOTP test fails randomly.
Here's one
<details>

```
Regression tests for ISOTPScan
4421-- Run Sun Dec 29 01:19:16 2019 from [test/contrib/isotpscan.uts] by UTscapy
4422
4423Passed=20
4424Failed=1
4425
4426
4427######
4428## Syntax check
4429######
4430
4431
4432###(023)=[failed] Test ISOTPScan(output_format=None) random IDs
4433
4434>>> drain_bus(iface0)
4435>>> 
4436>>> rnd = RandNum(0x0, 0x100)
4437>>> 
4438>>> ids = set(rnd._fix() for _ in range(10))
4439>>> 
4440>>> def isotpserver(i):
4441...     with ISOTPSocket(new_can_socket0(), sid=0x100+i, did=i) as s:
4442...         s.sniff(timeout=100 ,count=1)
4443... 
4444>>> def make_noise(pkt):
4445...     s = new_can_socket0()
4446...     for _ in range(20):
4447...         s.send(pkt)
4448...         time.sleep(0.1)
4449... 
4450>>> pkt = CAN(identifier=0x701, length=8, data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
4451>>> thread_noise = threading.Thread(target=make_noise, args=pkt)
4452>>> thread_noise.start()
4453>>> 
4454>>> threads = [threading.Thread(target=isotpserver, args=[x]) for x in ids]
4455>>> _ = [t.start() for t in threads]
4456>>> time.sleep(0.1)
4457>>> 
4458>>> result = ISOTPScan(new_can_socket0(), range(0x000, 0x101), can_interface=new_can_socket0(), noise_listen_time=1, sniff_time=0.1, verbose=True)
4459Filtering background noise...
4460[+] Found flow-control frame from identifier 0x118 when testing identifier 0x018
4461[+] Found flow-control frame from identifier 0x12c when testing identifier 0x02c
4462[+] Found flow-control frame from identifier 0x15c when testing identifier 0x05c
4463[+] Found flow-control frame from identifier 0x189 when testing identifier 0x089
4464[+] Found flow-control frame from identifier 0x19a when testing identifier 0x09a
4465[+] Found flow-control frame from identifier 0x1c6 when testing identifier 0x0c7
4466[+] Found flow-control frame from identifier 0x1d4 when testing identifier 0x0d4
4467[+] Found flow-control frame from identifier 0x1e2 when testing identifier 0x0e2
4468[+] Found flow-control frame from identifier 0x1eb when testing identifier 0x0eb
4469[+] Found flow-control frame from identifier 0x1f5 when testing identifier 0x0f5
4470>>> result = sorted(result, key=lambda x:x.src)
4471>>> 
4472>>> cans = new_can_socket0()
4473>>> 
4474>>> for i in ids:
4475...     # This helps to close ISOTPSoftSockets
4476...     cans.send(CAN(identifier=i, data=b'\x01\xaa'))
4477... 
4478>>> _ = [t.join() for t in threads]
4479>>> thread_noise.join()
4480>>> 
4481>>> assert len(result) == len(ids)
4482>>> ids = sorted(ids)
4483>>> for i, s in zip(ids, result):
4484...     assert i == s.src
4485...     assert i+0x100 == s.dst
4486... 
4487Traceback (most recent call last):
4488  File "<input>", line 3, in <module>
4489AssertionError
```

</details>
On py27-bsd_non_root

**Comment by polybassa** [comment]
I don’t mind ;-) 

I’m really sorry about the randomly failing unit tests. I try to fix that.

**Comment by polybassa** [comment]
> I hope you don't mind but I'll report here each time a ISOTP test fails randomly.
> Here's one
> 
> On py27-bsd_non_root.
> [full logs](https://github.com/secdev/scapy/files/4008205/log.txt)

This bug is hopefully fixed through #2404

**Comment by gpotter2** [comment]
Well if you could have a look at why https://github.com/secdev/scapy/pull/2401 fails it would be really awesome.

The PR improves latency of `sr*()` and changes a few socket things, and fails on the ISOTP tests. I'm unsure if that's because of the latency improvements or because of the socket changes.

In a perfect world, we should remove all `time.sleep()` from tests and use things like `RLock`s to make sure they never fail ever again..

**Comment by polybassa** [comment]
Thats weird, that some tests with ISOTPNativeSockets are failing. Usually, the ISOTPNativeSocket is much more reliable. Could be, that this tests are timing dependant. I will try to remove as much time.sleep() calls as possible. You'll get a PR soon.

**Comment by polybassa** [comment]
Hope that helps: #2405

**Comment by gpotter2** [comment]
Another failing test

<details>

```

###(014)=[failed] Positive, hold response pending for several messages
3891
3892>>> tout = 0.3
3893>>> repeats = 4
3894>>> def ecusim():
3895...     with ISOTPSocket(new_can_socket(iface0), sid=0x642, did=0x242, basecls=GMLAN) as isotpsock2:
3896...         isotpsock2.sniff(count=1, timeout=1)
3897...         ack = GMLAN()/GMLAN_NR(requestServiceId=0x34, returnCode=0x78)
3898...         for i in range(repeats):
3899...             isotpsock2.send(ack)
3900...             time.sleep(tout)
3901...         ack = b"\x74"
3902...         isotpsock2.send(ack)
3903... 
3904>>> thread = threading.Thread(target=ecusim)
3905>>> thread.start()
3906>>> time.sleep(0.05)
3907>>> 
3908>>> with ISOTPSocket(new_can_socket(iface0), sid=0x242, did=0x642, basecls=GMLAN) as isotpsock:
3909...     starttime = time.time() # may be inaccurate -> on some systems only seconds precision
3910...     assert GMLAN_RequestDownload(isotpsock, 4, timeout=repeats*tout+0.5) == True
3911...     endtime = time.time()
3912...     assert (endtime - starttime) >= tout*repeats
3913... 
3914Timeout.
3915Traceback (most recent call last):
3916  File "<input>", line 4, in <module>
3917AssertionError
3918
3919
3920Exception TypeError: "'NoneType' object is not callable" in <bound method StreamSocket.__del__ of <scapy.supersocket.StreamSocket object at 0x104fbe1d0>> ignored
```

</details>

**Comment by polybassa** [comment]
Thanks

**Comment by polybassa** [comment]
I started another attempt to make the tests better: #2415

**Comment by polybassa** [comment]
Next to #2415 I'm working on another big refactoring of Python-can CANSockets. 
On the OSX unit test I always get this error: 
```
Traceback (most recent call last):

  File "<input>", line 3, in <module>

  File "scapy/supersocket.py", line 164, in sniff

    return sendrecv.sniff(opened_socket=self, *args, **kargs)

  File "scapy/sendrecv.py", line 1036, in sniff

    sniffer._run(*args, **kwargs)

  File "scapy/sendrecv.py", line 931, in _run

    close_pipe = ObjectPipe()

  File "scapy/automaton.py", line 209, in __init__

    self.rd, self.wr = os.pipe()

OSError: [Errno 24] Too many open files

```

Do you have an idea, why this happens?
The code, I'm testing is here: https://github.com/polybassa/scapy-1/tree/python-can-refactoring
The job which is failing is here: https://travis-ci.org/polybassa/scapy-1/jobs/639622133

**Comment by gpotter2** [comment]
That reminds me, it appears using `#flake8: noqa: EXXX` is understood as "skip the entire file", contrary to what I thought.

I have a PR incoming to fix that, but in the mean time:
- `automotive/daimler/definitions` is a mess of trailing white spaces
- `automotive/obd/scanner.py` has lots of "line too long" + other errors

If you remove the tag and `flake8` those files it'll appear clearly

**Comment by polybassa** [comment]
I will include it into the refactoring commit, if possible. 

By the way, I found the bugs witch caused the problem I described on the above message


On January 24, 2020 12:25:55 AM GMT+01:00, Gabriel <notifications@github.com> wrote:
>That reminds me, it appears using `#flake8: noqa: EXXX` is understood
>as "skip the entire file", contrary to what I thought.
>
>I have a PR incoming to fix that, but in the mean time:
>- `automotive/daimler/definitions` is a mess of trailing white spaces
>- `automotive/obd/scanner.py` has lots of "line too long" + other
>errors
>
>If you remove the tag and `flake8` those files it'll appear clearly
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/secdev/scapy/issues/2350#issuecomment-577924847

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gpotter2** [comment]
Great thanks. Sorry I missed it

**Comment by polybassa** [comment]
I think the refactoring of automotive unit tests made the tests more stable. #2428 
Please reopen this issues, if you see automotive tests failing, again.

**Comment by gpotter2** [comment]
A new issue:
```
###(011)=[failed] Simple check with different Sessions
5607
5608>>> drain_bus(iface0)
5609>>> 
5610>>> example_responses = \
5611...     [ECUResponse(session=2, security_level=0, responses=UDS() / UDS_RDBIPR(dataIdentifier=2) / Raw(b"deadbeef1")),
5612...      ECUResponse(session=range(3,5), security_level=0, responses=UDS() / UDS_RDBIPR(dataIdentifier=3) / Raw(b"deadbeef2")),
5613...      ECUResponse(session=[5,6,7], security_level=0, responses=UDS() / UDS_RDBIPR(dataIdentifier=5) / Raw(b"deadbeef3")),
5614...      ECUResponse(session=lambda x: 8 < x <= 10, security_level=0, responses=UDS() / UDS_RDBIPR(dataIdentifier=9) / Raw(b"deadbeef4"))]
5615>>> 
5616>>> with new_can_socket0() as isocan1, ISOTPSocket(isocan1, sid=0x700, did=0x600, basecls=UDS) as ecu, \
5617...         new_can_socket0() as isocan2, ISOTPSocket(isocan2, sid=0x600, did=0x700, basecls=UDS) as tester:
5618...     answering_machine = ECU_am(supported_responses=example_responses, main_socket=ecu, basecls=UDS)
5619...     sim = threading.Thread(target=answering_machine, kwargs={'count': 5})
5620...     sim.start()
5621...     try:
5622...         resp = tester.sr1(UDS()/UDS_RDBI(identifiers=[2, 3, 5, 9]), timeout=1, verbose=False)
5623...         assert resp.negativeResponseCode == 0x10
5624...         assert resp.requestServiceId == 34
5625...         answering_machine.ecu_state.current_session = 2
5626...         resp = tester.sr1(UDS() / UDS_RDBI(identifiers=[2, 3, 5, 9]), timeout=1, verbose=False)
5627...         assert resp.service == 0x62
5628...         assert resp.dataIdentifier == 2
5629...         assert resp.load == b"deadbeef1"
5630...         answering_machine.ecu_state.current_session = 4
5631...         resp = tester.sr1(UDS() / UDS_RDBI(identifiers=[2, 3, 5, 9]), timeout=1, verbose=False)
5632...         assert resp.service == 0x62
5633...         assert resp.dataIdentifier == 3
5634...         assert resp.load == b"deadbeef2"
5635...         answering_machine.ecu_state.current_session = 6
5636...         resp = tester.sr1(UDS() / UDS_RDBI(identifiers=[2, 3, 5, 9]), timeout=1, verbose=False)
5637...         assert resp.service == 0x62
5638...         assert resp.dataIdentifier == 5
5639...         assert resp.load == b"deadbeef3"
5640...         answering_machine.ecu_state.current_session = 9
5641...         resp = tester.sr1(UDS() / UDS_RDBI(identifiers=[2, 3, 5, 9]), timeout=1, verbose=False)
5642...         assert resp.service == 0x62
5643...         assert resp.dataIdentifier == 9
5644...         assert resp.load == b"deadbeef4"
5645...     finally:
5646...         sim.join(timeout=10)
5647... 
5648UDS / UDS_RDBI ==> ['UDS / UDS_NR']
5649UDS / UDS_RDBI ==> ['UDS / UDS_RDBIPR / Raw']
5650Traceback (most recent call last):
5651  File "<input>", line 18, in <module>
5652AttributeError: 'NoneType' object has no attribute 'service'
```

**Comment by polybassa** [comment]
Thanks. I hope the python-can refactoring fixes that.

-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
```
######
4298## Testing ISOTPSocket timeouts
4299######
4300
4301
4302###(100)=[failed] Check if not sending the first FC will make the socket timeout
4303
4304>>> exception = None
4305>>> isotp = ISOTP(data=dhex("01 02 03 04 05 06 07 08 09 0A"))
4306>>> 
4307>>> with new_can_socket0() as isocan, ISOTPSocket(isocan, sid=0x641, did=0x241) as s:
4308...     try:
4309...         s.send(isotp)
4310...         assert(False)
4311...     except Scapy_Exception as ex:
4312...         exception = ex
4313... 
4314>>> print(exception)
4315ISOTP send not completed in 30s
4316>>> assert(str(exception) == "TX state was reset due to timeout")
4317Traceback (most recent call last):
4318  File "<input>", line 2, in <module>
4319AssertionError
4320
4321
4322
```
This has happened a few times. Not often

**Comment by polybassa** [comment]
Thanks.

I've tested a fix in this commit https://github.com/polybassa/scapy-1/commit/974771b05124a1a6590a759290e2e184ddc67b2e
If you want you can cherry-pick it. If not I can open a PR.

**Comment by polybassa** [comment]
Fixed in #2502

**Comment by gpotter2** [comment]
```
######
6109## Simulate scanner
6110######
6111
6112
6113###(012)=[failed] Test DTC scan
6114
6115>>> drain_bus(iface0)
6116>>> 
6117>>> s3 = OBD()/OBD_S03_PR(dtcs=[OBD_DTC()])
6118>>> 
6119>>> example_responses = [ECUResponse(session=range(0,255), security_level=0, responses=s3)]
6120>>> 
6121>>> with new_can_socket0() as isocan, ISOTPSocket(isocan, 0x7e8, 0x7e0, basecls=OBD, padding=True) as ecu:
6122...     answering_machine = ECU_am(supported_responses=example_responses, main_socket=ecu, basecls=OBD)
6123...     sim = threading.Thread(target=answering_machine, kwargs={'count': 3, 'timeout': 10, 'stop_filter': lambda p: p.service == 0xff})
6124...     sim.start()
6125...     try:
6126...         result = subprocess.Popen([sys.executable, "scapy/tools/automotive/obdscanner.py"] + can_socket_string_list + ["-s", "0x7e0", "-d", "0x7e8", "-t", "0.05"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
6127...         std_out, std_err = result.communicate()
6128...         if six.PY2:
6129...             expected_output = b"Service 3:\nC\x01\x00\x00"
6130...         else:
6131...             expected_output = b"Service 3:\nb'C\\x01\\x00\\x00'"
6132... 
6133...         assert bytes_encode(expected_output) in bytes_encode(std_out)
6134... 
6135...     finally:
6136...         isocan.send(CAN(identifier=0x7e0, data=b'\x07\xff\xff\xff\xff\xff\xff\xff'))
6137...         sim.join(timeout=10)
6138... 
6139OBD ==> ['OBD / OBD_S03_PR']
6140OBD ==> ['OBD / OBD_NR']
6141OBD ==> ['OBD / OBD_NR']
6142Traceback (most recent call last):
6143  File "<input>", line 14, in <module>
6144AssertionError
```

**Comment by polybassa** [comment]
Thanks... I will investigate that in the next days. My new PRs encountered the same issue.
-- 
Viele Grüße

Nils Weiß

**Comment by polybassa** [comment]
As soon as I have free time next week, I'll fix that obd_scanner tests.

**Comment by polybassa** [comment]
#2561 Should fix the obd_scanner tests (hopefully)

**Comment by guedou** [comment]
Is this issue still valid? It seems that the test are must more stable now.

**Comment by polybassa** [comment]
The tests are still not 100% stable. I assume that race-conditions in the tests create non-deterministic failures. I'm not happy with the current situation and I'm still searching the root of the problem. Unfortunately I'm not able to reproduce the failures on my local machine, which makes it very hard to debug this failures.

**Comment by guedou** [comment]
@polybassa you could configure Travis on your own scapy repository. That will allow to get a finer control over the tests.

**Comment by polybassa** [comment]
I did. I have the impression, the latest chances improved the stability.

**Comment by guedou** [comment]
I did not restart the tests for a long time. That’s why, I think that we can Close this ticket.

**Comment by polybassa** [comment]
I will still monitor the stability of the automotive tests and will focus on improvements
