### ISSUE TITLE
len(pkt) error for some packet like CDP/VTP

### ISSUE THREAD

**Issue by duychu** [secdev/scapy#2413]
#### Brief description
I tried to test len of packet but found that python3.7+scapy does not work and raise below exception

some special packet that I have tried: CPD, VTP, 

It is ok with python2.7
```
root@trex:/tmp# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.contrib.cdp import *
>>> from scapy.all import *
>>> pkt=CDPv2_HDR(vers=2, ttl=180, msg='123')
>>> len(pkt)
7
>>> 
```

python3.7
```
root@ubuntu:/workspace/_prototype/rtg-avatar# python
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> from scapy.contrib import *
>>> pkt=CDPv2_HDR(vers=2, ttl=180, msg='123')
>>> len(pkt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 522, in __len__
    return len(self.__bytes__())
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 594, in do_build
    return self.post_build(pkt, pay)
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/cdp.py", line 371, in post_build
    cksum = checksum(self._check_len(p))
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/cdp.py", line 361, in _check_len
    if last_chr <= b'\x80':
TypeError: '<=' not supported between instances of 'int' and 'bytes'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 522, in __len__
    return len(self.__bytes__())
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 594, in do_build
    return self.post_build(pkt, pay)
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/cdp.py", line 371, in post_build
    cksum = checksum(self._check_len(p))
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/cdp.py", line 361, in _check_len
    if last_chr <= b'\x80':
TypeError: '<=' not supported between instances of 'int' and 'bytes'
>>> 
```

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.7` and `2.7`
-   Operating System: `Ubuntu18.04`

**Comment by duychu** [comment]
Hello, Can you check VTP packet also. As mentioned, same issue like CDP

```
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> from scapy.contrib.vtp import *
>>> pkt = VTP(code=2, domname='domain123456', rev=21, vlaninfo=[VTPVlanInfo(vlanname='default', dot10index=100001, vlanid=1, type=1)])
>>> len(pkt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 522, in __len__
    return len(self.__bytes__())
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 589, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 570, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 239, in addfield
    return self.fld.addfield(pkt, s, val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 1156, in addfield
    return s + b"".join(bytes_encode(v) for v in val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 1156, in <genexpr>
    return s + b"".join(bytes_encode(v) for v in val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/compat.py", line 60, in bytes_encode
    return bytes(x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 594, in do_build
    return self.post_build(pkt, pay)
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/vtp.py", line 119, in post_build
    p = chr(tmp_len & 0xff) + p[1:]
TypeError: unsupported operand type(s) for &: 'float' and 'int'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 522, in __len__
    return len(self.__bytes__())
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 589, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 570, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 239, in addfield
    return self.fld.addfield(pkt, s, val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 1156, in addfield
    return s + b"".join(bytes_encode(v) for v in val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/fields.py", line 1156, in <genexpr>
    return s + b"".join(bytes_encode(v) for v in val)
  File "/usr/local/lib/python3.7/dist-packages/scapy/compat.py", line 60, in bytes_encode
    return bytes(x)
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.7/dist-packages/scapy/packet.py", line 594, in do_build
    return self.post_build(pkt, pay)
  File "/usr/local/lib/python3.7/dist-packages/scapy/contrib/vtp.py", line 119, in post_build
    p = chr(tmp_len & 0xff) + p[1:]
TypeError: unsupported operand type(s) for &: 'float' and 'int'
>>> 
```

**Comment by guedou** [comment]
I updated the PR.
