### ISSUE TITLE
LLDP ERROR: OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by nstarke** [secdev/scapy#2432]
The attached scapy script will cause an exception.  The same script worked with version `2.4.1`.  I will be happy to submit a PR if someone can give me some guidance on what needs to be fixed; a quick git diff on the lldp history didn't reveal anything immediately obvious.

script:

```
#!/usr/bin/env python

from scapy.all import *
import time

load_contrib("lldp")
conf.contribs["LLDP"].strict_mode_disable()
l="A" * 24
c=LLDPDUChassisID.SUBTYPE_CHASSIS_COMPONENT
p=LLDPDUPortID.SUBTYPE_MAC_ADDRESS
frm = Ether(dst=LLDP_NEAREST_BRIDGE_MAC)/             \
    LLDPDUChassisID(subtype=c, id=l)/      \
    LLDPDUPortID(subtype=p, id=l)/         \
    LLDPDUTimeToLive(ttl=2)/                          \
    LLDPDUPortDescription(description=l)/  \
    LLDPDUSystemName(system_name=l)/       \
    LLDPDUSystemDescription(description=l)/\
    LLDPDUSystemCapabilities(
            two_port_mac_relay_available=1,
            s_vlan_component_available=1,
            c_vlan_component_available=1,
            station_only_available=1,
            docsis_cable_device_available=1,
            telephone_available=1,
            router_available=1,
            wlan_access_point_available=1,
            mac_bridge_available=1,
            repeater_available=1,
            other_available=1,
            two_port_mac_relay_enabled=1,
            s_vlan_component_enabled=1,
            c_vlan_component_enabled=1,
            station_only_enabled=1,
            docsis_cable_device_enabled=1,
            telephone_enabled=1,
            router_enabled=1,
            wlan_access_point_enabled=1,
            mac_bridge_enabled=1,
            repeater_enabled=1,
            other_enabled=1
            )/\
    LLDPDUManagementAddress(management_address=l, object_id=l)/\
    LLDPDUEndOfLLDPDU()

frm = frm.build()
```

Stack trace:

```
Traceback (most recent call last):
  File "lldpd/lldp-example", line 51, in <module>
    frm = frm.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 592, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 579, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/contrib/lldp.py", line 297, in do_build
    return super(LLDPDU, self).do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 592, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 579, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/contrib/lldp.py", line 297, in do_build
    return super(LLDPDU, self).do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 589, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 570, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 352, in addfield
    return fld.addfield(pkt, s, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 140, in addfield
    return s + struct.pack(self.fmt, self.i2m(pkt, val))
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 491, in i2m
    return mac2str(x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils.py", line 402, in mac2str
    return b"".join(chb(int(x, 16)) for x in plain_str(mac).split(':'))
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils.py", line 402, in <genexpr>
    return b"".join(chb(int(x, 16)) for x in plain_str(mac).split(':'))
  File "/usr/local/lib/python2.7/dist-packages/scapy/compat.py", line 39, in <lambda>
    chb = lambda x: x if isinstance(x, str) else chr(x)
OverflowError: Python int too large to convert to C long
```

**Comment by guedou** [comment]
Thanks for reporting the issue. Could you provide a shorter example that reproduce this behavior?

**Comment by nstarke** [comment]
Here is as short as I can make it: 
```
#!/usr/bin/env python

from scapy.all import *

load_contrib("lldp")
conf.contribs["LLDP"].strict_mode_disable()
l="A" * 24
c=LLDPDUChassisID.SUBTYPE_CHASSIS_COMPONENT
p=LLDPDUPortID.SUBTYPE_MAC_ADDRESS
frm = Ether(dst=LLDP_NEAREST_BRIDGE_MAC)/             \
    LLDPDUChassisID(subtype=c, id=l)/      \
    LLDPDUPortID(subtype=p, id=l)/         \
    LLDPDUTimeToLive(ttl=2)/                          \
    LLDPDUEndOfLLDPDU()

frm = frm.build()


```

**Comment by gpotter2** [comment]
> `LLDPDUPortID(subtype=p, id=l)`

You're giving it SUBTYPE_MAC_ADDRESS so it expects a MAC, but you pass it a "AAAAAAAAAAAAAA..."

**Comment by nstarke** [comment]
I would argue that this validation should either be optional or not enforced.  I have found bugs in LLDP implementations from this exact behavior: a remote LLDP daemon is expecting a MAC address and receives junk instead.  In those cases, the lack of validation present in `2.4.1` allowed me to uncover the bug.  

Again, if someone can give me a little bit of guidance on how they would like to see this implemented, I'm happy to submit a pull request.

**Comment by gpotter2** [comment]
You're right.
Let's just let people put whatever they want in `MACField` (`fields.py`).
This could simply be a length check
