### ISSUE TITLE
Still having the same scapy problem on kali

### ISSUE THREAD

**Issue by Valhrafn** [secdev/scapy#2449]
Im having the exact same problem on kali, everything works fine if I dont use an ip range...

from scapy.all import *

def scan(ip):
    arp_request = scapy.all.ARP(pdst=ip)
    broadcast = scapy.all.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = broadcast/arp_request
    print(arp_request_broadcast.summary())
    arp_request_broadcast.show()

scan("10.0.2.1")

#that all works fine but if I try:

scan("10.0.2.1/24")

I get the following errer:

Ether / ARP who has ?? says ??
Traceback (most recent call last):
  File "snet.py", line 13, in <module>
    scan("10.0.2.1/24")
  File "snet.py", line 11, in scan
    arp_request_broadcast.show()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1261, in show
    return self._show_or_dump(dump, indent, lvl, label_lvl)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1235, in _show_or_dump
    reprval = f.i2repr(self, fvalue)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 502, in i2repr
    x = self.i2h(pkt, x)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 136, in i2h
    iff = self.getif(pkt)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 132, in <lambda>
    self.getif = (lambda pkt: pkt.route()[0]) if getif is None else getif
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1185, in route
    return self.payload.route()
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 400, in route
    fld, dst = fld._find_fld_pkt_val(self, dst)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 313, in _find_fld_pkt_val
    if val == dflts_pkt[self.name] and self.name not in pkt.fields:
  File "/usr/lib/python2.7/dist-packages/scapy/base_classes.py", line 133, in __eq__
    p2, nm2 = self._parse_net(other)
  File "/usr/lib/python2.7/dist-packages/scapy/base_classes.py", line 99, in _parse_net
    tmp = net.split('/') + ["32"]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by guedou** [comment]
Please use the issue template, if you want an answer. You can reopen the issue when this is done.
