### ISSUE TITLE
ImportError: No module named dnet

### ISSUE THREAD

**Issue by lisiupython** [secdev/scapy#245]
>>> _from scapy.all import *_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\lib\site-packages\scapy\all.py", line 16, in <module>
    from arch import *
  File "E:\Anaconda\lib\site-packages\scapy\arch\__init__.py", line 80, in <module>
    from windows import *
  File "E:\Anaconda\lib\site-packages\scapy\arch\windows\__init__.py", line 23, in <module>
    from scapy.arch import pcapdnet
  File "E:\Anaconda\lib\site-packages\scapy\arch\pcapdnet.py", line 173, in <module>
    import dnet
_ImportError: No module named dnet_
Using python2.7, windows 7, could you help me?

**Comment by guedou** [comment]
Did you install the dnet Python module ?

**Comment by lisiupython** [comment]
@guedou 
Yes, now it is OK. Hard to find a suitable version dnet for win7~I found it in the issues of dnet project.
maybe work though it goes:
_WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: can't import layer ipsec: 'module' object has no attribute 'IPPROTO_AH'_
Thank you for your help.
