### ISSUE TITLE
Can't using pdfdump on osx

### ISSUE THREAD

**Issue by dark-lbp** [secdev/scapy#246]
When i use pdfdump(), i got following error.

```python
INFO: Can't import matplotlib. Won't be able to plot.
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (2.3.2-dev)
>>> pyx.__version__
'0.12'
>>> test=IP()
>>> test.pdfdump()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/pyx/text.py", line 665, in run
    raise RuntimeError("TeX/LaTeX finished unexpectedly")
RuntimeError: TeX/LaTeX finished unexpectedly

still waiting for tex after 5 (of 60) seconds...
``` 
canvas_dump can't work too.

```python
>>> test=IP()
>>> test.canvas_dump()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scapy/packet.py", line 524, in canvas_dump
    pt = pyx.text.text(XSTART, (YTXT-y)*YMUL, r"\font\cmssfont=cmss10\cmssfont{%s}" % proto.name, [ pyx.text.size.Large])
  File "/usr/local/lib/python2.7/site-packages/pyx/text.py", line 1196, in text
    self.execute(expr, self.defaulttexmessagesdefaultrun + self.texmessagesdefaultrun + texmessages)
  File "/usr/local/lib/python2.7/site-packages/pyx/text.py", line 991, in execute
    self.expectqueue.put_nowait("PyXInputMarker:executeid=%i:" % self.executeid)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 148, in put_nowait
    return self.put(item, False)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 123, in put
    raise Full
Full
```

I installed mactex, pyx Graphviz on my computer,Is there something I missed?

**Comment by dark-lbp** [comment]
I found the reason, after degrade my OSX to 10.11, the Tex path is broken. 
Old path is "/usr/texbin", to fix this problem we should follow this [document](http://www.tug.org/mactex/UpdatingForElCapitan.pdf).
