### ISSUE TITLE
Getting "Exception ignored in: <bound method SuperSocket.__del__ of ... >"

### ISSUE THREAD

**Issue by vlad-shulika** [secdev/scapy#2470]
#### Brief description

Using `sniff` method with unreal `iface` parameter leads to `Ignored exception ...`

#### Environment

-   Scapy version: `Version 2.4.3`
-   Python version: `Python 3.6.9`
-   Operating System: `Linux 5.3.0-28-generic #30~18.04.1-Ubuntu x86_64 GNU/Linux`

#### How to reproduce
```
# (module name : sample.py)
import scapy.all as scapy


def main():
    try:
        pkts = scapy.sniff(iface="mocked")
    except Exception as e:
        print("===========================================")
        print(str(e))
        print("===========================================")
        exit()


if __name__ == "__main__":
    main()
```

Ran from terminal as:
`$ sudo python ./sample.py`

#### Actual result

```
$ sudo python ./sample.py 
===========================================
[Errno 19] No such device
===========================================
Exception ignored in: <bound method SuperSocket.__del__ of <scapy.arch.linux.L2ListenSocket object at 0x7f7ca13086a0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scapy/supersocket.py", line 134, in __del__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 514, in close
    set_promisc(self.ins, self.iface, 0)
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 165, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 380, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/common.py", line 59, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
```
#### Expected result

Just a successful exit from a program without additional std::err output.

**Comment by guedou** [comment]
Thanks for reporting the issue.
