### ISSUE TITLE
Using AsyncSniff throws "Exception in thread Thread-(number)"

### ISSUE THREAD

**Issue by vlad-shulika** [secdev/scapy#2474]
#### Brief description

Using `AsyncSniffer` method with unreal `iface` parameter leads to `IException in thread Thread-(number)`

#### Environment

-   Scapy version: `Version 2.4.3`
-   Python version: `Python 3.6.9`
-   Operating System: `Linux 5.3.0-28-generic #30~18.04.1-Ubuntu x86_64 GNU/Linux`

#### How to reproduce
```
# (module name : sample.py)
import scapy.all as scapy


def main():
    print("0===========================================")
    async_sniff_obj = scapy.AsyncSniffer(iface="mocked_interface")
    print("1===========================================")
    async_sniff_obj.start()
    print("2===========================================")
    async_sniff_obj.join()
    try:
        async_sniff_obj.stop()
    except Exception as e:
        print("3===========================================")
        print(str(e))
        print("4===========================================")


if __name__ == "__main__":
    main()
```

Ran from terminal as:
`$ sudo python ./sample.py`

#### Actual result
```
$ sudo python ./sample.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vshulika/PycharmProjects/ScypyInvestigation/venv/lib/python3.6/site-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/home/vshulika/PycharmProjects/ScypyInvestigation/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 477, in __init__
    set_promisc(self.ins, self.iface)
  File "/home/vshulika/PycharmProjects/ScypyInvestigation/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 165, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/home/vshulika/PycharmProjects/ScypyInvestigation/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 380, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/home/vshulika/PycharmProjects/ScypyInvestigation/venv/lib/python3.6/site-packages/scapy/arch/common.py", line 59, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device

0===========================================
1===========================================
2===========================================
3===========================================
Unsupported (offline or unsupported socket)
4===========================================

Process finished with exit code 0
```
#### Expected result

Get exception ONLY on `async_sniff_obj.start()` method, not on `async_sniff_obj.stop()` and in start of program.

**Comment by gpotter2** [comment]
If you're using a threaded sniffer, the error will happen in the thread. How would it act otherwise ?

**Comment by vlad-shulika** [comment]
@gpotter2 Why should we start new thread if the input interface isn't exist? I expect that exception should be thrown on a  `async_sniff_obj.start()` calling

**Comment by gpotter2** [comment]
I didn't find an easy of doing that. Scapy is already handy enough to raise an exception when the interface doesn't exist.
Just make sure you use an interface included in `get_if_list()`.
