### ISSUE TITLE
ValueError: invalid literal for int() with base 16: "'b" - while computing length of an IE

### ISSUE THREAD

**Issue by UmakantKulkarni** [secdev/scapy#2485]
I'm trying to compute the length of IMSI IE; but getting following error:
```
>>> from scapy.contrib.gtp_v2 import IE_IMSI
>>> ie = IE_IMSI(ietype='IMSI', length=8, IMSI='2080112345670000')
>>> ie
<IE_IMSI  ietype=IMSI length=8 IMSI='2080112345670000' |>
>>> len(ie)
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/root/Umakant/gtpv2/scapy-master/scapy/packet.py", line 527, in __len__
    return len(self.__bytes__())
  File "/root/Umakant/gtpv2/scapy-master/scapy/packet.py", line 492, in __bytes__
    return self.build()
  File "/root/Umakant/gtpv2/scapy-master/scapy/packet.py", line 612, in build
    p = self.do_build()
  File "/root/Umakant/gtpv2/scapy-master/scapy/packet.py", line 594, in do_build
    pkt = self.self_build()
  File "/root/Umakant/gtpv2/scapy-master/scapy/packet.py", line 575, in self_build
    p = f.addfield(self, p, val)
  File "/root/Umakant/gtpv2/scapy-master/scapy/fields.py", line 1267, in addfield
    return s + struct.pack("%is" % len_pkt, self.i2m(pkt, val))
  File "/root/Umakant/gtpv2/scapy-master/scapy/contrib/gtp.py", line 179, in i2m
    ret_string += chr(int(tmp[1] + tmp[0], 16))
ValueError: invalid literal for int() with base 16: "'b"
```
Same error with IE_ServingNetwork & IE_APN.
This is from gtpv2 - https://github.com/secdev/scapy/blob/master/scapy/contrib/gtp_v2.py

**Comment by UmakantKulkarni** [comment]
This works well with python 2.7 but not with 3:
```
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scapy
>>> from scapy.contrib.gtp_v2 import IE_IMSI
>>> ie = IE_IMSI(ietype='IMSI', length=8, IMSI='2080112345670000')
>>> ie
<IE_IMSI  ietype=IMSI length=8 IMSI='2080112345670000' |>
>>> len(ie)
12
>>>
```

**Comment by gpotter2** [comment]
Thanks for the report.
Could you check that https://github.com/secdev/scapy/pull/2491 fixes your issue

**Comment by UmakantKulkarni** [comment]
Sure, let me try that.!

**Comment by UmakantKulkarni** [comment]
IMSI & Serving_Network works well now.
But still APN & MSISDN throws an error:
MSISDN -
```
>>> a = IE_MSISDN(ietype=76, CR_flag=0, instance=0, digits='17567547897068')
>>> a
<IE_MSISDN  ietype=MSISDN CR_flag=0 instance=0 digits='17567547897068' |>
>>> len(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/packet.py", line 527, in __len__
    return len(self.__bytes__())
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/packet.py", line 492, in __bytes__
    return self.build()
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/packet.py", line 612, in build
    p = self.do_build()
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/packet.py", line 594, in do_build
    pkt = self.self_build()
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/packet.py", line 575, in self_build
    p = f.addfield(self, p, val)
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/fields.py", line 1266, in addfield
    return s + self.i2m(pkt, val)
  File "/data/umakant_kulkarni/cna/misc/gtp/scapy-master/scapy/contrib/gtp.py", line 179, in i2m
    ret_string += chr(int(tmp[1] + tmp[0], 16))
ValueError: invalid literal for int() with base 16: "'b"
```
APN - 
```
>>> ie8 = IE_APN(ietype='APN', CR_flag=0, instance=0, APN='apn6.epdg-access-pi.net')
>>> ie8
<IE_APN  ietype=APN CR_flag=0 instance=0 APN='apn6.epdg-access-pi.net' |>
>>> len(ie8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 527, in __len__
    return len(self.__bytes__())
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 492, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 612, in build
    p = self.do_build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 594, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 575, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.6/site-packages/scapy/fields.py", line 1000, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/local/lib/python3.6/site-packages/scapy/contrib/gtp.py", line 502, in i2m
    s = b"".join(chb(len(x)) + x for x in s.split("."))
TypeError: a bytes-like object is required, not 'str'
>>> 
```

**Comment by UmakantKulkarni** [comment]
My bad, MSISDN works. APN still throws an error though..

**Comment by gpotter2** [comment]
It's the same issues all over the place. Let me check that

**Comment by UmakantKulkarni** [comment]
Sure, Thanks.!

**Comment by gpotter2** [comment]
Should be good now.
