### ISSUE TITLE
Cannot sniff using L2ListenTcpdump on Windows

### ISSUE THREAD

**Issue by bohmax** [secdev/scapy#2496]
#### Brief description

Using 

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.8`
-   Operating System: `Windows 10 1909`
-   Npcap `0.9987`
-   WinDump for npcap `0.3`

#### How to reproduce
```
from scapy.all import *
sniff(opened_socket=L2ListenTcpdump())
```

#### Actual result
```
C:\Windows\system32\windump.exe: listening on \Device\NPF_{8B207BA6-1E3E-4B46-8D5A-84261ED29577}
Traceback (most recent call last):
  File "C:/Users/mark/PycharmProjects/project/createPcap/getPcap.py", line 31, in <module>
    sniff(opened_socket=L2ListenTcpdump())
  File "C:\Users\mark\AppData\Local\Programs\Python\Python38\lib\site-packages\scapy\sendrecv.py", line 1036, in sniff
    sniffer._run(*args, **kwargs)
  File "C:\Users\mark\AppData\Local\Programs\Python\Python38\lib\site-packages\scapy\sendrecv.py", line 955, in _run
    sockets, read_func = select_func(sniff_sockets, remain)
  File "C:\Users\mark\AppData\Local\Programs\Python\Python38\lib\site-packages\scapy\supersocket.py", line 198, in select
    inp, _, _ = select(sockets, [], [], remain)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```
#### Expected result

Program able to analize the packet

#### Related resources

WinDump downloaded from https://github.com/hsluoyz/WinDump/releases

**Comment by gpotter2** [comment]
Thanks for the report, fixed in https://github.com/secdev/scapy/pull/2521.
Could you check the patch? Thanks

**Comment by bohmax** [comment]
Thanks it work now!
Btw thanks for yours hard work, scapy it's really helpful . Keep it up :D

**Comment by gpotter2** [comment]
Thanks. I'll just leave this open as it will automatically close itself once the fix is merged
