### ISSUE TITLE
Scapy crash when libpcap.so is not installed

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#2526]
-   Scapy version: `master branch`
-   Python version: `3.5.3`
-   Operating System: `Debian 9.12`

This is regression comparing to older Scapy version as `libpcap.so` should not be mandatory to inject packets:
```
>>> traceroute("8.8.8.8")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/scapy/scapy/layers/inet.py", line 1668, in traceroute
    timeout=timeout, filter=filter, verbose=verbose, **kargs)
  File "/home/vagrant/scapy/scapy/sendrecv.py", line 509, in sr
    iface=iface, nofilter=nofilter)
  File "/home/vagrant/scapy/scapy/arch/linux.py", line 452, in __init__
    attach_filter(self.ins, filter, iface)
  File "/home/vagrant/scapy/scapy/arch/linux.py", line 139, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/home/vagrant/scapy/scapy/arch/common.py", line 77, in compile_filter
    from scapy.libs.winpcapy import (
  File "/home/vagrant/scapy/scapy/libs/winpcapy.py", line 38, in <module>
    raise OSError("Cannot find libpcap.so library")
OSError: Cannot find libpcap.so library
```

**Comment by gpotter2** [comment]
Not sure.

We replaced the tcpdump dependency with libpcap. but libpcap is a dependency of tcpdump, so it shouldn't change anything if not improve..

It's required to filter, as was tcpdump

**Comment by guedou** [comment]
We must, at least, have the same behavior as before: not an error message instead of an uncaught exception.

**Comment by guedou** [comment]
FYI, this works fine on master:
`>>> traceroute6("www.kame.net", nofilter=True)`
