### ISSUE TITLE
Sessions can crash Scapy

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#2543]
Loading a Python3 session on a Python2 Scapy, will crash it.

```
./run_scapy -3 -s crash.session
./run_scapy -2 -s crash.session
[..]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/guedou/Projects/Scapy/scapy-issues/scapy/__main__.py", line 15, in <module>
    interact()
  File "scapy/main.py", line 573, in interact
    init_session(session_name, mydict)
  File "scapy/main.py", line 420, in init_session
    "rb"))
ValueError: unsupported pickle protocol: 4
```

**Comment by gpotter2** [comment]
Well we could pin a pickle protocol version that is python2 & 3 compatible (protocol 2), but newer protocols are much more effective..

**Comment by guedou** [comment]
Displaying an message saying that the session cannot be loaded is a good compromise.
