### ISSUE TITLE
OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by ganhw1970** [secdev/scapy#2628]
#### Brief description

in linux shell, input scapy into the scapy interactive mode, when exec the sniff() or sr1(IP(dst='192.168.1.51')/ICMP()), will prompt "OSError: [Errno 97] Address family not supported by protocol"

>>> sniff()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ganhw/.local/lib/python3.6/site-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/ganhw/.local/lib/python3.6/site-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/home/ganhw/.local/lib/python3.6/site-packages/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
>>>

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `e.g. 3.6`
-   Operating System: `win10 WSL2 ubuntu 18.04`

**Comment by gpotter2** [comment]
That's a limitation of WSL :/
