### ISSUE TITLE
ICMPv6NDOptIPAddr dissector fail at Solaris

### ISSUE THREAD

**Issue by xirs** [secdev/scapy#271]
When run scapy regression test at Solaris, there are two FAILs:
ERROR: ICMPv6 Neighbor Discovery - IP Address Option (FH for MIPv6) dissector failed
failed 90B81179 ICMPv6NDOptSrcAddrList - Dissection with specific values
ERROR: ICMPv6 Neighbor Discovery - IP Address Option (FH for MIPv6) dissector failed
failed 489F0573 ICMPv6NDOptTgtAddrList - Instantiation with specific values

both of them are because ICMPv6NDOptIPAddr dissector fail

root@x2270-brm-01:/var/tmp/scapy-2.3.2# python
Python 2.7.11 (default, May 21 2016, 11:52:58) [C] on sunos5
Type "help", "copyright", "credits" or "license" for more information.

> > > import logging
> > > logging.getLogger("scapy").setLevel(1)
> > > from scapy.all import *
> > > WARNING: Solaris must indicate a speicific network interface when recieve msg
> > > WARNING: It means sr()/sniff() need 'iface' parameter.
> > > WARNING: Otherwise, the interface which has default route will be used.

WARNING: No route found for IPv6 destination :: (no default route?)
Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.

> > > a=ICMPv6NDOptSrcAddrList('\t\x03BBBBBB\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x11\x11\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11\x11')
> > > ERROR: ICMPv6 Neighbor Discovery - IP Address Option (FH for MIPv6) dissector failed
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "scapy/base_classes.py", line 196, in **call**
> > >     i.**init**(_args, *_kargs)
> > >   File "scapy/packet.py", line 85, in **init**
> > >     self.dissect(_pkt)
> > >   File "scapy/packet.py", line 623, in dissect
> > >     self.do_dissect_payload(payl)
> > >   File "scapy/packet.py", line 601, in do_dissect_payload
> > >     p = cls(s, _internal=1, _underlayer=self)
> > >   File "scapy/base_classes.py", line 196, in __call__
> > >     i.**init**(_args, *_kargs)
> > >   File "scapy/packet.py", line 85, in **init**
> > >     self.dissect(_pkt)
> > >   File "scapy/packet.py", line 618, in dissect
> > >     s = self.do_dissect(s)
> > >   File "scapy/packet.py", line 583, in do_dissect
> > >     s, fval = f.getfield(self, s)
> > >   File "scapy/fields.py", line 73, in getfield
> > >     return  s[self.sz:], self.m2i(pkt, struct.unpack(self.fmt, s[:self.sz])[0])
> > > struct.error: unpack requires a string argument of length 16
> > > 
> > > root@x2270-brm-01:/var/tmp/scapy-2.3.2#

**Comment by guedou** [comment]
That's weird. What's the content of `s` used line 73 in `fields.py` ?

By the way, what is the output of:
`conf.route6`

**Comment by guedou** [comment]
Issue closed due to no activity.
