### ISSUE TITLE
Unsupported address family for interface teredo

### ISSUE THREAD

**Issue by shajinzheng** [secdev/scapy#274]
This error appeared when we tried to send a IPv6 packet created by Scapy. @complete46

**[Test Environment]**:
**Client**: Two default IPv6 interface, i.e. native IPv6 connection, and ipv6 tunnel `Miredo`
**Server**: Use `Tunnel Broker` as ipv6 tunnel
**Scapy**: Latest development version cloned from https://github.com/secdev/scapy

**[Source Code]**

``` python
import random
from scapy.all import *
dst = '2001:470:1f06:bbb::2' # AWS Instance
send( IPv6(dst=dst)/TCP( dport=80, sport=random.randint(10000, 20000), flags = 0x02) ) # send a SYN
```

**[Error Message]**:

```
Traceback (most recent call last):
  File "send-tcp6.py", line 106, in <module>
    print first_p.route() 
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 258, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 236, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 395, in send
    sx = str(ll(x))
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 272, in __str__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 349, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 336, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 327, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 70, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 95, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 89, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 38, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 477, in <lambda>
    conf.neighbor.register_l3(Ether, IPv6, lambda l2,l3: getmacbyip6(l3.dst))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 112, in getmacbyip6
    res = neighsol(ip6, a, iff, chainCC=chainCC)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 80, in neighsol
    p /= ICMPv6NDOptSrcLLAddr(lladdr=get_if_hwaddr(iface))
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 43, in get_if_hwaddr
    raise Scapy_Exception("Unsupported address family (%i) for interface [%s]" % (addrfamily,iff))
scapy.error.Scapy_Exception: Unsupported address family (-2) for interface [teredo]
```

**[Bug Analysis]**:
The bug was because when Scapy sends a packet, there are two invocations of `conf.route6.route()` with different parameters. 

First one is [here](https://github.com/secdev/scapy/blob/02ae08b4ad973184a167ffcfb10043dfeda1244d/scapy/arch/linux.py#L391). And the interface in its return tuple is `eth0` in our experiment.

Second one is [here](https://github.com/secdev/scapy/blob/02ae08b4ad973184a167ffcfb10043dfeda1244d/scapy/layers/inet6.py#L106). In the second invocation, we can see the extra parameter `dev=conf.iface6`, which is `teredo` in our experiment. And this caused the interface in the return tuple to be `teredo`.

**[Quick Fix]**
At [here](https://github.com/secdev/scapy/blob/02ae08b4ad973184a167ffcfb10043dfeda1244d/scapy/layers/inet6.py#L106), change from `iff,a,nh = conf.route6.route(ip6, dev=conf.iface6)
` to `iff,a,nh = conf.route6.route(ip6)`. 

It works in our local machine with environments states above, but we are still working on a more comprehensive fix. We would appreciate if you can give us some information on how you initialize `self.cache` as in `route6.py`. That might be the key to this problem.

**Comment by guedou** [comment]
Is [it](https://github.com/secdev/scapy/blob/master/test/regression.uts#L57) what you are looking for ? This line adds a fake IPv6 routing table entry.

What happends if you set `conf.iface6` to teredo ? I believe that in your setup, it will work without any modification to Scapy.

**Comment by guedou** [comment]
Also, would you mind sharing the output of `/proc/net/ipv6_route `? Thanks.

**Comment by shajinzheng** [comment]
Can we give back to you later? Our lab is shut down for a power remodeling and will be back next week. Thanks for your effort!

**Comment by guedou** [comment]
Issue closed due to no activity.
