### ISSUE TITLE
TypeError when opening malformed pcap

### ISSUE THREAD

**Issue by Google-Autofuzz** [secdev/scapy#2742]
#### Brief description

Scapy crashes when opening a malformed pcap file.

#### Environment

-   Scapy version:  scapy-2.4.4rc2.dev6 from a `pip3 install --upgrade git+git://github.com/secdev/scap`
-   Python version: 3.5
-   Operating System: Debian

#### How to reproduce

```python
$ cat test.py
import sys
import scapy
import scapy.utils

scapy.utils.rdpcap(sys.argv[1])
$ python3 test.py sample.pcap
Traceback (most recent call last):
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1139, in read_packet
    p = self.LLcls(s)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    scapy.utils.rdpcap(sys.argv[1])
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 951, in rdpcap
    return fdesc.read_all(count=count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1154, in read_all
    res = RawPcapReader.read_all(self, count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1094, in read_all
    p = self.read_packet()
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1147, in read_packet
    p = conf.raw_layer(s)
TypeError: 'NoneType' object is not callable
$
```

#### Actual result

```python
Traceback (most recent call last):
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1139, in read_packet
    p = self.LLcls(s)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    scapy.utils.rdpcap(sys.argv[1])
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 951, in rdpcap
    return fdesc.read_all(count=count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1154, in read_all
    res = RawPcapReader.read_all(self, count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1094, in read_all
    p = self.read_packet()
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1147, in read_packet
    p = conf.raw_layer(s)
TypeError: 'NoneType' object is not callable
```

#### Expected result

Not a crash.

#### Related resources

[sample.pcap.zip](https://github.com/secdev/scapy/files/5006905/sample.pcap.zip)

**Comment by gpotter2** [comment]
Thanks for the report, will be fixed in https://github.com/secdev/scapy/pull/2743
