### ISSUE TITLE
Scapy crashing on start Windows

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#277]
Hi,
I'm having this issue with the last (dev) scapy version on windows 7 (all depedencies are installed)

```
C:\Users\Utilisateur\Desktop\scapy-master>scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 96, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 21, in <module>
    from scapy.sendrecv import debug, srp1
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 15, in <module>
    from scapy import arch
ImportError: cannot import name arch
```

I'll be happy to answer any of you questions :)

BTW great soft !

**Comment by guedou** [comment]
Thanks for this PR !

`git blame` seems to indicate that line 15 in sendrecv.py was modified by [this commit](https://github.com/secdev/scapy/commit/6057906368d55634d11e1d19a5cca1f127595b11). Could you try again using [this one](https://github.com/secdev/scapy/commit/1e48e13fc594f8d925451c7e2706086d21102716).

Could you try and confirm that this is the issue ? We will then look into fixing it.

**Comment by guedou** [comment]
In Issue #217 you are referring to a fix that you did. Could you share it ? Thanks.

**Comment by gpotter2** [comment]
I'm going to check if it works that way, my "fix" is definatly not relevant because I only disabled all functions that I would not use...

**Comment by gpotter2** [comment]
I've done a pull request for a fix that worked with me
https://github.com/secdev/scapy/pull/287

**Comment by robin-jarry** [comment]
I think you can close this one too :)

**Comment by p-l-** [comment]
@robin-jarry indeed! Thanks.

**Comment by gpotter2** [comment]
Hold on !!
I did a mistake while testing the new version: i still had some of my old fixes inside it... I completly reforked my repo from the main one and it's still trigerring:
```
C:\Users\gpotter>scapy
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 96, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 599, in <module>
    import scapy.sendrecv
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 15, in <module>
    from scapy import arch
ImportError: cannot import name arch
```

Sorry for the mistake 😞

**Comment by p-l-** [comment]
@gpotter2 can you tell us whether #296 fixes your issue? Thanks a lot!

**Comment by gpotter2** [comment]
Not yet:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 12, in <module>
    from scapy.arch.consts import LINUX, OPENBSD, FREEBSD, NETBSD, DARWIN, \
  File "C:\Python27\lib\site-packages\scapy\arch\consts.py", line 18, in <module>
    uname = os.uname()
AttributeError: 'module' object has no attribute 'uname'
```

**Comment by p-l-** [comment]
Of course, I'm an idiot. PR updated. Can you test again please? Sorry about that...

**Comment by gpotter2** [comment]
Now:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 84, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 599, in <module>
    import scapy.sendrecv
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 25, in <module>
    import scapy.route
  File "C:\Python27\lib\site-packages\scapy\route.py", line 11, in <module>
    from scapy.arch import read_routes,get_if_addr,LOOPBACK_NAME
ImportError: cannot import name read_routes
```

**Comment by p-l-** [comment]
OK. That's another problem, I've tried to fix it and updated the PR.

**Comment by gpotter2** [comment]
First, thank you a lot for fixing this :)

Then, it's still crashing:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 83, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 599, in <module>
    import scapy.sendrecv
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 25, in <module>
    import scapy.route
  File "C:\Python27\lib\site-packages\scapy\route.py", line 163, in <module>
    conf.route=Route()
  File "C:\Python27\lib\site-packages\scapy\route.py", line 22, in __init__
    self.resync()
  File "C:\Python27\lib\site-packages\scapy\route.py", line 29, in resync
    from scapy.arch import read_routes
ImportError: cannot import name read_routes
```

**Comment by robin-jarry** [comment]
@p-l-, it looks like the scapy.sendrecv module should we reworked to contain some functions defined in scapy.arch.windows. That would reduce the amount of circular imports and also avoid monkey patching our own code :-)

**Comment by p-l-** [comment]
@robin-jarry totally.

**Comment by gpotter2** [comment]
I found a simple way to fix it: https://github.com/secdev/scapy/pull/298

**Comment by gpotter2** [comment]
Great, fixed !

**Comment by mkandala** [comment]
@gpotter2 I am still seeing the read_routes import error. I am using scapy2.3.3.

**Comment by p-l-** [comment]
@mkandala please upgrade to 2.4.0, and open a new issue if the bug still exists after that.

**Comment by mkandala** [comment]
@p-l-  Thank you. It works now.
