### ISSUE TITLE
Fail to build the documentation offline with the latest master doc/scapy file

### ISSUE THREAD

**Issue by tianzry** [secdev/scapy#2774]
#### Brief description

Fail to build the documentation offline with the latest master doc/scapy

#### Environment

-   Scapy version: `c03d8d4227761a369f3f449ac5dafb3e21c364dd`
-   Python version: ` 3.7.4`
-   Operating System: `Windows 10 x64 `

- Sphinx version: 3.0.1 (also try the latest Sphinx, the error was same)
- Docutils version: 0.16 release
- Jinja2 version: 2.11.2

#### How to reproduce

1. download the latest master code from url: https://github.com/secdev/scapy/archive/master.zip
2. build the doc offline as the tutorial  https://scapy.readthedocs.io/en/latest/installation.html#build-the-documentation-offline

#### Actual result

D:\scapy_20200820\doc\scapy>make.bat html
Running Sphinx v3.0.1

Exception occurred:
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system could not find the specified file

**the sphinx error log show as following:**

 Sphinx version: 3.0.1
 Python version: 3.7.4 (CPython)
 Docutils version: 0.16 release
 Jinja2 version: 2.11.2
 Last messages:

 Loaded extensions:
Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\cmd\build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\application.py", line 277, in __init__
    self._init_builder()
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\application.py", line 333, in _init_builder
    self.events.emit('builder-inited')
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "D:\scapy_20200820\doc\scapy\_ext\scapy_doc.py", line 142, in builder_inited_handler
    subprocess.call(['tox', '-e', 'apitree'])
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]

**Comment by gpotter2** [comment]
You need to install `tox` to build our doc.
