### ISSUE TITLE
Can't send packet to docker in macOS

### ISSUE THREAD

**Issue by tony1016** [secdev/scapy#279]
My docker machine got a ip 192.168.99.100.When I send a SYN packet,I got this:
```
Begin emission:
ERROR: --- Error in child 59348
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/scapy/sendrecv.py", line 89, in sndrcv
    pks.send(p)
  File "/usr/local/lib/python3.5/site-packages/scapy/arch/pcapdnet.py", line 443, in send
    iftype = self.intf.get(iff)["type"]
KeyError: 'type'
```

**Comment by tony1016** [comment]
and my code is just easy:
```
srcPort=random.randint(1024,65535)
    SYN=IP(dst=dstHost)/TCP(sport=srcPort,dport=dstPort,flags="S")
    SYNACK=sr1(SYN)
    ACK=IP(dst=dstHost)/TCP(sport=srcPort,dport=dstPort,flags="A",seq=SYNACK.ack, ack=SYNACK.seq + 1)
    send(ACK)
```

**Comment by guedou** [comment]
We do no support Python 3. 

Could you try again with the current github code and Python 2 ?
Feel free to re-open the issue is the bug is still present.
