### ISSUE TITLE
IndexError: Layer [Radius] not found

### ISSUE THREAD

**Issue by soltanabadiyan** [secdev/scapy#2876]
```
from pyrad.packet import Packet
from pyrad.dictionary import Dictionary
from scapy.all import *

def parse_packet(packet):
    radius_packet = str(packet[Radius])
    pkt = Packet(packet=radius_packet, dict=Dictionary("dictionary"))

   for key, value in pkt.iteritems():
        attr =  pkt._DecodeKey(key)
        value = pkt.__getitem__(attr)
        print (attr, value)

sniff(iface='eth0', prn=parse_packet, filter="udp", store=0)
```

in python3 i got this error :
```
sudo python3 service.py 
Traceback (most recent call last):
  File "service.py", line 14, in <module>
    sniff(iface='eth0', prn=parse_packet, filter="udp", store=0)
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.4.dev73-py3.8.egg/scapy/sendrecv.py", line 1054, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.4.dev73-py3.8.egg/scapy/sendrecv.py", line 1007, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.4.dev73-py3.8.egg/scapy/sessions.py", line 82, in on_packet_received
    result = self.prn(pkt)
  File "service.py", line 6, in parse_packet
    radius_packet = str(packet[Radius])
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.4.dev73-py3.8.egg/scapy/packet.py", line 1338, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Radius] not found
```

**Comment by guedou** [comment]
This is not a forum but a bug tracker.
