### ISSUE TITLE
cannot import name pcapdnet

### ISSUE THREAD

**Issue by daniel0720** [secdev/scapy#297]
I am using windows7, anaconda2, python 2.7, and install latest scapy. the preinquirements are all installed. When I first input 'from scapy.all import *' in ipython, I got import error, says: cannot import name read_routes.
And when I input 'from scapy.all import *' again, I got this import error, "cannot import name pcapdnet".
Does anyone has this problem?

`
 >>> from scapy.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Anaconda2\lib\site-packages\scapy\arch\__init__.py", line 83, in <mod
ule>
    from scapy.arch.windows import *
  File "C:\Anaconda2\lib\site-packages\scapy\arch\windows\__init__.py", line 599
, in <module>
    import scapy.sendrecv
  File "C:\Anaconda2\lib\site-packages\scapy\sendrecv.py", line 25, in <module>
    import scapy.route
  File "C:\Anaconda2\lib\site-packages\scapy\route.py", line 163, in <module>
    conf.route=Route()
  File "C:\Anaconda2\lib\site-packages\scapy\route.py", line 22, in __init__
    self.resync()
  File "C:\Anaconda2\lib\site-packages\scapy\route.py", line 29, in resync
    from scapy.arch import read_routes
ImportError: cannot import name read_routes
>>>
`
`>>> from scapy.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Anaconda2\lib\site-packages\scapy\arch\__init__.py", line 83, in <mod
ule>
    from scapy.arch.windows import *
  File "C:\Anaconda2\lib\site-packages\scapy\arch\windows\__init__.py", line 39,
 in <module>
    from scapy.arch import pcapdnet
ImportError: cannot import name pcapdnet
>>>`

**Comment by gpotter2** [comment]
Duplicated for windows: https://github.com/secdev/scapy/issues/277

The fact that trying to do twice will prompt "cannot import name pcapdnet" is common: it's because it could not instanciate first...
