### ISSUE TITLE
Scapy fails to set IPv6 Address

### ISSUE THREAD

**Issue by michaelschem** [secdev/scapy#3040]
#### Environment

-   Scapy version: `Version 2.4.4`
-   Python version: `python3.8`
-   Operating System: `macOS Catalina 10.15.7`

#### How to reproduce

1) Open Scapy
2) Set ipv6 address

#### Actual result

```
>>> a=IP(ttl=10)
>>> a.src
'127.0.0.1'
>>> a.dst="2607:f2c0:f002607:f2c0:f00f:b001::face:b00c"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/scapy/fields.py", line 541, in h2i
    inet_aton(x)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/scapy/packet.py", line 405, in __setattr__
    return self.setfieldval(attr, val)
  File "/usr/local/lib/python3.8/site-packages/scapy/packet.py", line 388, in setfieldval
    self.fields[attr] = any2i(self, val)
  File "/usr/local/lib/python3.8/site-packages/scapy/fields.py", line 568, in any2i
    return self.h2i(pkt, x)
  File "/usr/local/lib/python3.8/site-packages/scapy/fields.py", line 543, in h2i
    x = Net(x)
  File "/usr/local/lib/python3.8/site-packages/scapy/base_classes.py", line 108, in __init__
    self.parsed, self.netmask = self._parse_net(net)
  File "/usr/local/lib/python3.8/site-packages/scapy/base_classes.py", line 101, in _parse_net
    tmp[0] = socket.gethostbyname(tmp[0])
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
#### Expected result

I expect this to work.  Without an error, unfortunately, I get the error above.

**Comment by gpotter2** [comment]
Two things:
- you are using an `IP` packet which is IPv4 only (use `IPv6`)
- the ip you've passed is invalid.
