### ISSUE TITLE
macOS VMWare Fusion with long interface name

### ISSUE THREAD

**Issue by twodayslate** [secdev/scapy#3051]
#### Brief description

Unable to get scapy to work on macOS Big Sur when using UDP raw sockets like `sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137))` to a VMWare Fusion VM on interface bridge100. The interface is truncated to bridge1 which does not exist.

This was discussed in gitter and I am filing an official ticket. It may be a Big Sur/Python error and not related to scapy.

https://gitter.im/secdev/scapy?at=5fff2bbcdc2e4809aa1daa7f

#### Environment

```
% pip list | grep scapy
scapy                  2.4.4.dev265
% sudo python --version
Python 3.8.1
% uname -a
Darwin User-MBP 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
% sw_vers 
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

libpcap was installed via homebrew
```
% brew list libpcap
/usr/local/Cellar/libpcap/1.9.1/bin/pcap-config
/usr/local/Cellar/libpcap/1.9.1/include/pcap/ (15 files)
/usr/local/Cellar/libpcap/1.9.1/include/ (3 files)
/usr/local/Cellar/libpcap/1.9.1/lib/libpcap.1.9.1.dylib
/usr/local/Cellar/libpcap/1.9.1/lib/pkgconfig/libpcap.pc
/usr/local/Cellar/libpcap/1.9.1/lib/ (3 other files)
/usr/local/Cellar/libpcap/1.9.1/share/man/ (79 files)
% echo $LDFLAGS 
-L/usr/local/opt/libffi/lib -L/usr/local/opt/libpcap/lib
% echo $CPPFLAGS
-I/usr/local/opt/libpcap/include
% echo $PATH | awk '{split($0,a,":"); print a[1]}'          
/usr/local/opt/libpcap/bin
```

#### How to reproduce
192.168.43.5 is a Windows XP box on VMWare Fusion with 'Share with my Mac' networking selected
```
% scapy
>>> scapy.__version__
'2.4.4.dev265'
>>> conf.use_pcap
False
>>> pkt = sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137), timeout=2, verbose=0)
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 73, in __init__
    fcntl.ioctl(self.ins, BIOCSETIF, struct.pack("16s16x", self.iface.encode()))  # noqa: E501
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/sendrecv.py", line 541, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 241, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 75, in __init__
    raise Scapy_Exception("BIOCSETIF failed on %s" % self.iface)
scapy.error.Scapy_Exception: BIOCSETIF failed on bridge1
>>> conf.use_pcap = True
WARNING: No libpcap provider available ! pcap won't be used
>>> pkt = sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137), timeout=2, verbose=0)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/sendrecv.py", line 541, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/supersocket.py", line 273, in __init__
    self.outs = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_RAW)  # noqa: E501
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
```

```
% sudo scapy
>>> conf.use_pcap
False
>>> scapy.__version__
'2.4.4.dev265'
>>> pkt = sr1(IP(pkt = sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137), timeout=2, verbose=1)
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 73, in __init__
    fcntl.ioctl(self.ins, BIOCSETIF, struct.pack("16s16x", self.iface.encode()))  # noqa: E501
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/sendrecv.py", line 541, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 241, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 75, in __init__
    raise Scapy_Exception("BIOCSETIF failed on %s" % self.iface)
scapy.error.Scapy_Exception: BIOCSETIF failed on bridge1
>>> conf.use_pcap=True
WARNING: No libpcap provider available ! pcap won't be used
>>> pkt = sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137), timeout=2, verbose=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/sendrecv.py", line 541, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/scapy/supersocket.py", line 275, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
AttributeError: module 'socket' has no attribute 'AF_PACKET'

**Comment by guedou** [comment]
I just checked and I don't have any issue on Big Sur with the master branch. It seems that pip report 2.4.4 while your are testing against '2.4.4.dev265'.

Could you try with the following commands?
```
git clone --depth=1 https://github.com/secdev/scapy
cd scapy/
sudo ./run_scapy
>>> sr1(IP(dst="1.1.1.1")/ICMP())
```

**Comment by twodayslate** [comment]
Please try with `sr1(IP(dst="1.1.1.1")/UDP(sport=137, dport=137))`

**Comment by guedou** [comment]
Please answer my question.

**Comment by twodayslate** [comment]
Your above code snippet works but `sr1(IP(dst="1.1.1.1")/UDP(sport=137, dport=137))` does not. 

```
>>> sr1(IP(dst="1sr1(IP(dst="1.1.1.1")/ICMP())
Begin emission:
Finished sending 1 packets.
...*
Received 4 packets, got 1 answers, remaining 0 packets
<IP  version=4 ihl=5 tos=0x0 len=28 id=36898 flags= frag=0 ttl=55 proto=icmp chksum=0x2fc5 src=1.1.1.1 dst=192.168.1.80 |<ICMP  type=echo-reply code=0 chksum=0x0 id=0x0 seq=0x0 |>>
```

**Comment by gpotter2** [comment]
https://www.python.org/downloads/release/python-391/

```
Installer news
3.9.1 is the first version of Python to support macOS 11 Big Sur. With Xcode 11 and later it is now possible to build “Universal 2” binaries which work on Apple Silicon. 
````

**Comment by guedou** [comment]
I don't have any issue on Big Sur with Python 3.9.1:
```
>>> sys.version
'3.9.1 (default, Dec 29 2020, 08:52:17) \n[Clang 12.0.0 (clang-1200.0.32.28)]'
>>> sys.platform
'darwin'
>>> scapy.__version__
'2.4.4.dev245'
>>> sr1(IP(dst="1.1.1.1") / UDP() / DNS(qd=DNSQR()))
Begin emission:
Finished sending 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
<IP  version=4 ihl=5 tos=0x0 len=77 id=42108 flags=DF frag=0 ttl=57 proto=udp chksum=0xb04e src=1.1.1.1 dst=192.168.42.43 |<UDP  sport=domain dport=domain len=57 chksum=0x344 |<DNS  id=0 qr=1 opcode=QUERY aa=0 tc=0 rd=1 ra=1 z=0 ad=0 cd=0 rcode=ok qdcount=1 ancount=1 nscount=0 arcount=0 qd=<DNSQR  qname='www.example.com.' qtype=A qclass=IN |> an=<DNSRR  rrname='www.example.com.' type=A rclass=IN ttl=75093 rdlen=None rdata=93.184.216.34 |> ns=None ar=None |>>>

```

**Comment by twodayslate** [comment]
I believe the original issue may have been misdiagnosed. It may be a VMware Fusion issue as it seems to only effect the VM bridge interface. This is in Python 3.8 and 3.9.1

```
>>> import sys
>>> sys.version
'3.9.1 (default, Jan 14 2021, 14:05:22) \n[Clang 12.0.0 (clang-1200.0.32.28)]'
>>> scapy.__version__
'a436560'
>>> sr1(IP(dst="1sr1(IP(dst="1.1.1.1")/UDP(sport=137, dport=137))
Begin emission:
Finished sending 1 packets.
......................................................................................................................................................................^C
Received 166 packets, got 0 answers, remaining 1 packets
>>> sr1(IP(dst="192.168.43.5")/UDP(sport=137, dport=137))
Traceback (most recent call last):
  File "/Users/user/Development/scapy/scapy/arch/bpf/supersocket.py", line 73, in __init__
    fcntl.ioctl(self.ins, BIOCSETIF, struct.pack("16s16x", self.iface.encode()))  # noqa: E501
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/Development/scapy/scapy/sendrecv.py", line 541, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/Users/user/Development/scapy/scapy/arch/bpf/supersocket.py", line 241, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/user/Development/scapy/scapy/arch/bpf/supersocket.py", line 75, in __init__
    raise Scapy_Exception("BIOCSETIF failed on %s" % self.iface)
scapy.error.Scapy_Exception: BIOCSETIF failed on bridge1
>>> 
```

**Comment by guedou** [comment]
Could you share the output of `netstat -rn -f inet` and `netstat -rnW -f inet` ?

**Comment by twodayslate** [comment]
get_if_raw_addr https://github.com/secdev/scapy/blob/8d6f1dac47458d7e27ab49277cac424334a9248c/scapy/arch/bpf/core.py#L74 doesn't raise an OSError so _guess_iface_name is never called

```
% netstat -rn -f inet
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
default            10.2.2.1           UGSc           en0       
default            link#19            UCSI       bridge1      !
10.2.2/24          link#6             UCS            en0      !
10.2.2.1/32        link#6             UCS            en0      !
10.2.2.1           18:e8:29:bd:7f:4f  UHLWIir        en0   1169
10.2.2.144         8:66:98:e1:40:f1   UHLWI          en0   1054
10.2.2.231         b8:27:eb:ba:39:f6  UHLWI          en0    947
10.2.2.245/32      link#6             UCS            en0      !
127                127.0.0.1          UCS            lo0       
127.0.0.1          127.0.0.1          UH             lo0       
169.254            link#6             UCS            en0      !
192.168.43         link#19            UCS        bridge1      !
192.168.43.5       0.c.29.d8.f6.86    UHLWI      bridge1    558
224.0.0/4          link#6             UmCS           en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI         en0       
255.255.255.255/32 link#6             UCS            en0      !
```

```
% netstat -rnW -f inet
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
default            10.2.2.1           UGSc           en0       
default            link#19            UCSI       bridge1      !
10.2.2/24          link#6             UCS            en0      !
10.2.2.1/32        link#6             UCS            en0      !
10.2.2.1           18:e8:29:bd:7f:4f  UHLWIir        en0   1197
10.2.2.144         8:66:98:e1:40:f1   UHLWI          en0   1035
10.2.2.231         b8:27:eb:ba:39:f6  UHLWI          en0    928
10.2.2.245/32      link#6             UCS            en0      !
127                127.0.0.1          UCS            lo0       
127.0.0.1          127.0.0.1          UH             lo0       
169.254            link#6             UCS            en0      !
192.168.43         link#19            UCS        bridge1      !
192.168.43.5       0.c.29.d8.f6.86    UHLWI      bridge1    539
224.0.0/4          link#6             UmCS           en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI         en0       
255.255.255.255/32 link#6             UCS            en0      !
```

Sadly, `-W` doesn't seem to be very helpful

**Comment by guedou** [comment]
Thanks for sharing! I am able to reproduce the issue with 10.14 using the following commands:
```
ifconfig bridge100 create
ifconfig bridge100 172.16.1.2/24 up
./run_scapy
>>> sr1(IP(dst="172.16.1.2", src="172.16.1.1") / ICMP())
Traceback (most recent call last):
[..]
scapy.error.Scapy_Exception: BIOCSETIF failed on bridge1
```

**Comment by gpotter2** [comment]
Isn't there a way to not use `netstat` on OSX?

**Comment by guedou** [comment]
This is indeed a regression that was already fixed, but is again broken. The culprit call is mocked that why the test never broke.

**Comment by twodayslate** [comment]
On Python 3.3+ [`if_nameindex`](https://docs.python.org/3/library/socket.html#socket.if_nameindex) works on my MacBook Pro

**Comment by gpotter2** [comment]
We [already use it](https://github.com/secdev/scapy/blob/db89d7b183b90c4f6dd6fcad577102d3be567d03/scapy/arch/bpf/core.py#L160), the issue here is getting the IPv4 and IPv6 routes.

**Comment by guedou** [comment]
Sorry for the delay. I forgot about this issue. #3105 fixes it.
