### ISSUE TITLE
Destructor tries to access `self.ins` when L2bpfSocket failed to be created

### ISSUE THREAD

**Issue by bdraco** [secdev/scapy#3065]
#### Brief description

The `_L2bpfSocket` destructor attempts to access `self.ins` before it is created if the socket failed to be created.

#### Environment

-   Scapy version: `2.4.4`
-   Python version: `3.8`
-   Operating System: `Mac OS`

#### How to reproduce

Smallest replication:
```
>>> from scapy.config import conf
>>> from scapy.sendrecv import AsyncSniffer
>>> conf.L2socket()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/scapy/arch/bpf/supersocket.py", line 242, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/scapy/arch/bpf/supersocket.py", line 62, in __init__
    (self.ins, self.dev_bpf) = get_dev_bpf()
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/scapy/arch/bpf/core.py", line 114, in get_dev_bpf
    raise Scapy_Exception("No /dev/bpf handle is available !")
scapy.error.Scapy_Exception: No /dev/bpf handle is available !
>>> ^D
Exception ignored in: <function _L2bpfSocket.__del__ at 0x110de31f0>
Traceback (most recent call last):
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/scapy/arch/bpf/supersocket.py", line 139, in __del__
    self.close()
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/scapy/arch/bpf/supersocket.py", line 211, in close
    if not self.closed and self.ins is not None:
AttributeError: 'L2bpfSocket' object has no attribute 'ins'
```
#### Expected result

No exception

**Comment by gpotter2** [comment]
Thanks for the report.
