### ISSUE TITLE
struct.error when building UDP/RTP packet

### ISSUE THREAD

**Issue by dlpersson** [secdev/scapy#3104]
#### Brief description

I am getting the following exception when I try to interact with an RTP packet that has been created

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/USER/PycharmProjects/pots_checker/homemade-sip-client/CallHandler.py", line 228, in _read_queue
    self._process_200_ok(message)
  File "/Users/USER/PycharmProjects/pots_checker/homemade-sip-client/CallHandler.py", line 220, in _process_200_ok
    self.media_handler.start_audio()
  File "/Users/USER/PycharmProjects/pots_checker/homemade-sip-client/MediaHandler.py", line 35, in start_audio
    print(pkt)
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 495, in __str__
    return str(self.build())
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 618, in build
    p = self.do_build()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 600, in do_build
    pkt = self.self_build()
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/packet.py", line 581, in self_build
    p = f.addfield(self, p, val)
  File "/Users/USER/PycharmProjects/pots_checker/venv/lib/python3.6/site-packages/scapy/fields.py", line 151, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
struct.error: 'I' format requires 0 <= number <= 4294967295
```

As you can see I am just trying to print the packet.

This is the method where the packet it built
```
def start_audio(self):
        seq_num = 0
        bind_layers(UDP, RTP, dport=self.dest_port)
        packets = []
        now = int(str(int(round(time.time() * 1000)))[2:])
        count = 0
        for b in self._read_bytes_from_file2('hello.pcm'):
            seq_num += 1
            now += 160
            count += 1
            pkt = IP(src=self.local_ip, dst=self.dest_ip) / \
                  UDP(sport=int(self.local_port), dport=int(self.dest_port)) / \
                  RTP(sequence=seq_num, sourcesync=70889, timestamp=now) / b
            print(pkt)  #Error happens here
            packets.append(pkt)
        for pkt in packets:
            send(pkt, iface="en0", verbose=False)
            time.sleep(.007)
```

The file "hello.pcm" is 24kb which is broken into 160 byte pieces. 'b' is the 160 byte payload. When I was originally working on this project a few months ago it worked fine. I can't find any references to this issue so I am lost at the moment

#### Environment

-   Scapy version: `2.4.4`
-   Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
-   Operating System: `macOS Catalina 10.15.8`

**Comment by dlpersson** [comment]
After further testing the error appears to be related to the RTP portion

```
pkt = IP(src=self.local_ip, dst=self.dest_ip) / \
          UDP(sport=int(self.local_port), dport=int(self.dest_port)) / b
```
Does not produce the error

**Comment by guedou** [comment]
Thanks for the report. Could you share a simple reproducer?

**Comment by dlpersson** [comment]
As usual I was incorrect here. The problem was with the timestamp portion.
The line
```now = int(str(int(round(time.time() * 1000)))[2:])```
Was the culprit. The number it returned was too large. So the timestamp argument of the RTP initialization was causing the error.
When I chopped off a few more numbers it worked fine

```now = int(str(int(round(time.time() * 1000)))[5:])```

If you need to reproduce the error for whatever reason here is the code I was going to submit

```
from scapy.all import *

now = int(str(int(round(time.time() * 1000)))[2:])
now += 160
pkt = IP(src='192.168.86.190', dst='8.8.8.8') / \
     UDP(sport=int(12345), dport=int(12346)) / \
      RTP(sequence=1, sourcesync=1, timestamp=now)
print(pkt)
```
