### ISSUE TITLE
BytesIO Support for Pcap Export

### ISSUE THREAD

**Issue by lillypad** [secdev/scapy#311]
Hello Devs,

I can't take credit for this, full credit goes to [furas](http://stackoverflow.com/users/1832058/furas) for creating it.

Can we please add this to the `utils.py`

Reference URL:
http://stackoverflow.com/questions/40198000/writing-pcap-to-buffer-with-scapy/40204215#40204215

I wasn't going to create a pull request as this is his work however it should be included if it isn't already.

The purpose of having something like this is to enable live capture of pcap data and send it over the wire for malware analysis, files on disc often tend to get messed with by malware.

Cheers!

**Comment by p-l-** [comment]
Hi,

Thanks for this report. Have you tried with Scapy's latest version? As I [answered on SO](http://stackoverflow.com/a/40206282/3223422), it should work out of the box (since #77).

Please let us know if it works for what you want to do!

**Comment by lillypad** [comment]
Hey p-I-,

I can confirm this also doesn't work in the newest version.

I've tried the following:
```
$ sudo scapy
Welcome to **Scapy (2.3.2)**
>>> import io
>>> cap = sniff(timeout=10)
>>> buf = io.BytesIO()
>>> wrpcap(buf, cap)
```

This returns the following error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 524, in wrpcap
    with PcapWriter(filename, *args, **kargs) as fdesc:
  File "/usr/lib/python2.7/dist-packages/scapy/utils.py", line 682, in __init__
    self.f = [open,gzip.open][gz](filename,append and "ab" or "wb", gz and 9 or bufsz)
TypeError: coercing to Unicode: need string or buffer, _io.BytesIO found
```

I would still recommend adding following code to `utils.py`:
```
def memwrpcap(filename, pkt, *args, **kargs):
    """Write a list of packets to a pcap file
    gz: set to 1 to save a gzipped capture
    linktype: force linktype value
    endianness: "<" or ">", force endianness"""

    # use MemoryPcapWriter instead of PcapWriter
    with MemoryPcapWriter(filename, *args, **kargs) as fdesc:
        fdesc.write(pkt)


class MemoryPcapWriter(PcapWriter):
    """A stream PCAP writer with more control than wrpcap()"""
    def __init__(self, filename, linktype=None, gz=False, endianness="", append=False, sync=False):
        """
        linktype: force linktype to a given value. If None, linktype is taken
                  from the first writter packet
        gz: compress the capture on the fly
        endianness: force an endianness (little:"<", big:">"). Default is native
        append: append packets to the capture file instead of truncating it
        sync: do not bufferize writes to the capture file
        """

        self.linktype = linktype
        self.header_present = 0
        self.append=append
        self.gz = gz
        self.endian = endianness
        self.filename=filename
        self.sync=sync
        bufsz=4096
        if sync:
            bufsz=0

        # use filename or file-like object 
        if isinstance(self.filename, str):
            self.f = [open,gzip.open][gz](filename,append and "ab" or "wb", gz and 9 or bufsz)
        else: # file-like object 
            self.f = filename

    def __exit__(self, exc_type, exc_value, tracback):
        self.flush()
        if isinstance(self.filename, str):
            self.close() # don't close file-like object
```

Again credit would go to [furas](http://stackoverflow.com/users/1832058/furas).

Adding this for others I suspect will be useful for malware analysis.

Cheers!

**Comment by p-l-** [comment]
Scapy's latest version is 2.3.3. Could you please update and check again?

**Comment by lillypad** [comment]
Yep version was outdated :)

**Comment by p-l-** [comment]
OK! Can you confirm the changes are no longer needed?

**Comment by gpotter2** [comment]
@p-l- I do confirm that

```
Welcome to Scapy (2.3.3.dev177)
>>> import io
>>> cap = sniff(timeout=10)
INFO: Sniffing on <NetworkInterface Killer E2200 Gigabit Ethernet Controller {C56DFFB3-992C-4964-B000-3E7C0F76E8BA}>
>>> buf = io.BytesIO()
>>> wrpcap(buf, cap)
>>>
```

Can be closed

**Comment by vaclcer** [comment]
Hello, I confirm it works with "wrcap", but it does not work with "wrcapng". Is this intentional? Is there any workaround? Thanks!

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/Users/vaclav/Repos/jupyter/scapy.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/vaclav/Repos/jupyter/scapy.ipynb) Cell 1 line 1
     [12](vscode-notebook-cell:/Users/vaclav/Repos/jupyter/scapy.ipynb#W0sZmlsZQ%3D%3D?line=11) payload_variable = BytesIO()
     [14](vscode-notebook-cell:/Users/vaclav/Repos/jupyter/scapy.ipynb#W0sZmlsZQ%3D%3D?line=13) #wrpcapng("file.pcapng", [packet])
---> [15](vscode-notebook-cell:/Users/vaclav/Repos/jupyter/scapy.ipynb#W0sZmlsZQ%3D%3D?line=14) wrpcapng(payload_variable, [packet])

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1227](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1227), in wrpcapng(filename, pkt)
   [1213](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1213) @conf.commands.register
   [1214](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1214) def wrpcapng(filename,  # type: str
   [1215](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1215)              pkt,  # type: _PacketIterable
   [1216](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1216)              ):
   [1217](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1217)     # type: (...) -> None
   [1218](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1218)     """Write a list of packets to a pcapng file
   [1219](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1219) 
   [1220](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1220)     :param filename: the name of the file to write packets to, or an open,
   (...)
   [1225](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1225)     :param pkt: packets to write
   [1226](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1226)     """
-> [1227](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1227)     with PcapNgWriter(filename) as fdesc:
   [1228](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scapy/utils.py:1228)         fdesc.write(pkt)`
