### ISSUE TITLE
global name 'Gen' is not defined

### ISSUE THREAD

**Issue by samsamsam1234** [secdev/scapy#312]
I installed scapy on Windows 10 and executed this sample.py.

```
from scapy.all import *
request=IP(dst='www.google.com')/ICMP()
response = sr1(request)
response.show()
```

But displaed error masseges.

```
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    response = sr1(request)
  File "C:\App\Python27\lib\site-packages\scapy\sendrecv.py", line 355, in sr1
    a,b=sndrcv(s,x,*args,**kargs)
  File "C:\App\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 14, in sndrcv
    if not isinstance(pkt, Gen):
NameError: global name 'Gen' is not defined
```

How to fix ?

**Comment by gpotter2** [comment]
There are some missing imports. You can add 
```
from scapy.base_classes import Gen, SetGen
import scapy.plist as plist
from scapy.utils import PcapReader
from scapy.data import MTU, ETH_P_ARP
```
to the beggining of the scapy/arch/windows/compatibility.py file until it is fixed

**Comment by samsamsam1234** [comment]
Thank you advice. But different error...

```
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    response = sr1(request)
  File "C:\App\Python27\lib\site-packages\scapy\sendrecv.py", line 355, in sr1
    a,b=sndrcv(s,x,*args,**kargs)
  File "C:\App\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 55, in sndrcv
    if WINDOWS or pid == 0:
NameError: global name 'WINDOWS' is not defined
```

**Comment by gpotter2** [comment]
Thank you for testing this,
You can add:
``
WINDOWS = True
``
At the beggining too.

**Comment by samsamsam1234** [comment]
Sorry, different error...

```
Begin emission:
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    response = sr1(request)
  File "C:\App\Python27\lib\site-packages\scapy\sendrecv.py", line 355, in sr1
    a,b=sndrcv(s,x,*args,**kargs)
  File "C:\App\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 73, in sndrcv
    log_runtime.exception("--- Error sending packets")
NameError: global name 'log_runtime' is not defined
```

**Comment by gpotter2** [comment]
Add
``
from scapy.error import Scapy_Exception,log_loading,log_runtime
ˋ`
I hope it will be the last on est :P

**Comment by samsamsam1234** [comment]
Thank you!
I was resolved by this code add.
```
from scapy.base_classes import Gen, SetGen
import scapy.plist as plist
from scapy.utils import PcapReader
from scapy.data import MTU, ETH_P_ARP
import os,re,sys,socket,time, itertools
WINDOWS = True
```

**Comment by gpotter2** [comment]
Fixed ! May you close ?

**Comment by p-l-** [comment]
Thanks @gpotter2!
