### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by slyoldfox** [secdev/scapy#3205]
#### Brief description

./run_scapy does not run on macOS Catalina 10.15.7

#### Environment

-   Scapy version: `100b2ca7d01128e059330d34f11d4b01d2744c7e`
-   Python version: `3.8.6`
-   Operating System: `macOS Catalina 10.15.7`

#### How to reproduce

`$ ./run_scapy`

#### Actual result

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/slyoldfox/scapy/scapy/__main__.py", line 15, in <module>
    interact()
  File "/Users/slyoldfox/scapy/scapy/main.py", line 550, in interact
    SESSION, GLOBKEYS = init_session(session_name, mydict)
  File "/Users/slyoldfox/scapy/scapy/main.py", line 411, in init_session
    importlib.import_module(".all", "scapy").__dict__
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/slyoldfox/scapy/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/Users/slyoldfox/scapy/scapy/arch/__init__.py", line 130, in <module>
    from scapy.arch.bpf.supersocket import *  # noqa F403
  File "/Users/slyoldfox/scapy/scapy/arch/bpf/supersocket.py", line 27, in <module>
    from scapy.layers.l2 import Loopback
  File "/Users/slyoldfox/scapy/scapy/layers/l2.py", line 17, in <module>
    from scapy.ansmachine import AnsweringMachine
  File "/Users/slyoldfox/scapy/scapy/ansmachine.py", line 20, in <module>
    from scapy.sendrecv import send, sniff
  File "/Users/slyoldfox/scapy/scapy/sendrecv.py", line 61, in <module>
    import scapy.route  # noqa: F401
  File "/Users/slyoldfox/scapy/scapy/route.py", line 221, in <module>
    conf.ifaces.reload()
  File "/Users/slyoldfox/scapy/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/Users/slyoldfox/scapy/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/Users/slyoldfox/scapy/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/Users/slyoldfox/scapy/scapy/arch/bpf/core.py", line 226, in load
    mac = scapy.utils.str2mac(get_if_raw_hwaddr(ifname)[1])
  File "/Users/slyoldfox/scapy/scapy/utils.py", line 581, in str2mac
    return ("%02x:" * 6)[:-1] % tuple(map(ord, s))
TypeError: not all arguments converted during string formatting
```
#### Expected result

A result :-)

#### Related resources

I added some debug output in the utils.py class and it seems to be breaking on the `fw0` interface.
```
fw0
(
 \ÿþ#Rô
it is a string
(40, 11, 92, 255, 254, 35, 82, 244)
```

**Comment by guedou** [comment]
Thanks for the report! I am a bit surprised, as we tested Scapy on macOS 10.15

Could you share the output of `ifconfig`, `netstat -rn -f inet`, and `netstat -rn -f inet6` ?
Another way to help, is to share the output of `print(type(s), repr(s))` after adding the line to `strmac()`

**Comment by slyoldfox** [comment]
@guedou can I post the output somewhere private for you?

the print command just before the `if instance` check in `str2mac` yields for the `fw0` interface:

`<class 'str'> '(\x0b\\ÿþ#Rô'`

The output of `networksetup -listallhardwareports` for that interface is.

```
Hardware Port: FireWire
Device: fw0
Ethernet Address: 28:0b:5c:ff:fe:23:52:f4
```

Might have been you tested on a mac without Firewire ports (this is a Mac Mini with one Firewire port)? The mac address is slightly longer than a usual ethernet mac addres

**Comment by guedou** [comment]
You can sent it to me via email (see the commits logs to retrieve my address).

**Comment by slyoldfox** [comment]
Should be in your mailbox :-)

**Comment by guedou** [comment]
Got it. Does that fix makes Scapy happy? 
```
$ git diff
diff --git a/scapy/arch/bpf/core.py b/scapy/arch/bpf/core.py
index d49267cd..d7d87c5f 100644
--- a/scapy/arch/bpf/core.py
+++ b/scapy/arch/bpf/core.py
@@ -122,6 +122,8 @@ def get_if_raw_hwaddr(ifname):
     # Pack and return the MAC address
     mac = addresses[0].split(' ')[1]
     mac = [chr(int(b, 16)) for b in mac.split(':')]
+    if len(mac) != 6:
+        raise Scapy_Exception("No MAC address found on %s !" % ifname)
     return (ARPHDR_ETHER, ''.join(mac))
 
 

```

**Comment by slyoldfox** [comment]
@guedou yep, also patched it on my homeassistant install which also seems happy now, thanks for the swift responses!
