### ISSUE TITLE
RawPcapWriter - struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by Fratso** [secdev/scapy#3256]
#### Brief description

Error: `struct.error: required argument is not an integer` while trying to write raw_bytes to a file using scapy.utilis.RawPcapWriter object.

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.8.2`
-   Operating System: `Ubuntu 20.04`

#### How to reproduce

```python
raw_pkt_list = []

# This is working fine
with RawPcapReader(input_pcap) as r:
    for tuple in r:
        raw_pkt_list.append(tuple[0])  # I don't need metadata

with RawPcapWriter("output.pcap") as w:
    w.write(raw_pkt_list[0])  # The error is raised from this method
```

No modification have been done on the bytes.
I need to work only with raw packets.

#### Actual result

```python
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/scapy/utils.py", line 1298, in write
    self._write_header(pkt)
  File "/usr/lib/python3/dist-packages/scapy/utils.py", line 1284, in _write_header
    self.f.write(struct.pack(self.endian + "IHHIIII", 0xa1b23c4d if self.nano else 0xa1b2c3d4,  # noqa: E501
struct.error: required argument is not an integer
```

#### Expected result

A pcap "output.pcap" should be created containing the packet I'm trying to write.

**Comment by guedou** [comment]
Could you test against the latest version?

**Comment by Fratso** [comment]
Alright I retried on Scapy `2.4.5` which is scapy latest version at the time of writing.

### Environment

- Scapy version: `2.4.5`
- Python version: `3.8.0`
- Operating System: `Ubuntu 20.04`

### Python interpreter outputs

It seems the RawPcapReader context manager dos not work:
```python
from scapy.all import *


>>> with RawPcapReader(input_pcap) as r:
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __enter__
```

Simple instance does not work either:
```python
>>> reader = RawPcapReader(input_pcap)
>>> l = reader.read_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1283, in read_all
    res = self._read_all(count)
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1295, in _read_all
    p = self.read_packet()  # type: Packet
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1264, in read_packet
    Packet,
NameError: name 'Packet' is not defined
```

About RawPcapWriter object, it is still the same error:
```python
# l_raw is a list of bytes, each bytes object is a valid packet.

with RawPcapWriter(output_pcap) as w:
...     for p in l_raw:
...             w.write(p)
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1733, in write
    self.write_header(pkt)
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1697, in write_header
    return self._write_header(bytes_encode(pkt))
  File "/home/fredo/.local/lib/python3.8/site-packages/scapy/utils.py", line 1718, in _write_header
    self.f.write(struct.pack(self.endian + "IHHIIII", 0xa1b23c4d if self.nano else 0xa1b2c3d4,  # noqa: E501
struct.error: required argument is not an integer
```

**Comment by gpotter2** [comment]
Could you retry using the github dev version? The first bug is already fixed for sure

**Comment by Fratso** [comment]
#### Environment

- Scapy version: `2.4.5rc1.dev50`
- Python version: `3.8.0`
- Operating System: `Ubuntu 20.04`


#### Scapy interpreter output

- [ ] Using RawPcapReader like this does not work:

```python
with RawPcapReader(input_pcap) as r:
...     raw_pkt_list = r.read_all()
...
<string>:1: ResourceWarning: unclosed file <_io.BufferedReader name='../03012021.pcap'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
AttributeError: __enter__
```

- [X] Using RawPcapReader like this does work:
```python
reader = RawPcapReader(input_pcap)
>>> raw_pkt_list = []
>>> for p in reader:
...     raw_pkt_list.append(p)
...
>>> raw_pkt_list[:2]
[b'\x00\x00\x80\x00\xd6\xbe\x89\x8e7\x00\xd6\xbe\x89\x8e@\x186Zc\xab\x01g\x02\x01\x1a\x02\n\x0c\x0b\xffL\x00\x10\x06\x1d\x1e\xd7\x08`\xf6\xaf\x81\x9c', b'\x00\xca\x80\x00\xd6\xbe\x89\x8e7\x00\xd6\xbe\x89\x8e@\x18X1gA\xb3]\x02\x01\x1a\x02\n\x08\x0b\xffL\x00\x10\x063\x1a\xe8\xb1S]\xe5\n\xbc']
```

- [ ] And finally, writing Raw pcap raise the same issue:
```python
with RawPcapWriter("output.pcap") as w:
...     w.write(raw_pkt_list[0])
...
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
  File "/home/fredo/scapy_dev/scapy/utils.py", line 1732, in write
    self.write_header(pkt)
  File "/home/fredo/scapy_dev/scapy/utils.py", line 1696, in write_header
    return self._write_header(bytes_encode(pkt))
  File "/home/fredo/scapy_dev/scapy/utils.py", line 1718, in _write_header
    2, 4, 0, 0, self.snaplen, self.linktype))
struct.error: required argument is not an integer
```

**Comment by gpotter2** [comment]
Also why is everyone using RawPcapReader ? This is aimed at internal use only. Why not use `PcapReader` that has the decorators implemented?

**Comment by Fratso** [comment]
Actually I find RawPcapReader pretty handful. It's working on the version I'm working with, I just noticed the issue while writing the bytes using RawPcapWriter. A workaround I used is recreate the Ether layer then using wrpcap instead to write the Raw bytes.

In my case I'm not using `PcapReader` because I'm working with some fuzzy pcaps and PcapReader is using the scapy constructors which I don't want to use in this specific case...
