### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 'flags=3<LEARNING,DISCOVER>'

### ISSUE THREAD

**Issue by pascalnl** [secdev/scapy#3326]
### Brief description

./scapy doesn't run on freebsd 8.8

### Scapy version

scapy-2.4.5rc1.dev78

### Python version

3.8.6

### Operating system

OpenBSD router 6.8 GENERIC.MP#98 amd64

### Additional environment information

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 32768
        index 6 priority 0 llprio 3
        groups: lo
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x6
        inet 127.0.0.1 netmask 0xff000000
em0: flags=808843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,AUTOCONF4> mtu 1500
        lladdr 00:0d:b9:59:14:94
        index 1 priority 0 llprio 3
        groups: egress
        media: Ethernet autoselect (1000baseT full-duplex,rxpause,txpause)
        status: active
        inet 83.86.---.--netmask 0xfffffe00 broadcast 83.86.255.255
em1: flags=8b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
        lladdr 00:0d:b9:59:14:95
        index 2 priority 0 llprio 3
        media: Ethernet autoselect (1000baseT full-duplex,rxpause,txpause)
        status: active
em2: flags=8b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
        lladdr 00:0d:b9:59:14:96
        index 3 priority 0 llprio 3
        media: Ethernet autoselect (none)
        status: no carrier
em3: flags=8b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
        lladdr 00:0d:b9:59:14:97
        index 4 priority 0 llprio 3
        media: Ethernet autoselect (none)
        status: no carrier
enc0: flags=0<>
        index 5 priority 0 llprio 3
        groups: enc
        status: active
bridge0: flags=41<UP,RUNNING>
        index 7 llprio 3
        groups: bridge
        priority 32768 hellotime 2 fwddelay 15 maxage 20 holdcnt 6 proto rstp
        em3 flags=3<LEARNING,DISCOVER>
                port 4 ifpriority 0 ifcost 0
        em2 flags=3<LEARNING,DISCOVER>
                port 3 ifpriority 0 ifcost 0
        em1 flags=3<LEARNING,DISCOVER>
                port 2 ifpriority 0 ifcost 0
        vether0 flags=3<LEARNING,DISCOVER>
                port 9 ifpriority 0 ifcost 0
tun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
        description: OpenVPN to local net 192.168.0.0
        index 8 priority 0 llprio 3
        groups: tun openvpn
        status: active
        inet 10.8.0.1 --> 10.8.0.2 netmask 0xffffffff
vether0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        lladdr fe:e1:ba:d0:46:11
        index 9 priority 0 llprio 3
        groups: vether
        media: Ethernet autoselect
        status: active
        inet 192.168.0.1 netmask 0xffffff00 broadcast 192.168.0.255
```

### How to reproduce

./scapy

### Actual result

(homeassistant) router$ /usr/local/homeassistant/bin/scapy                                                                                                                                                  
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No IPv4 address found on em1 !
WARNING: No IPv4 address found on em2 !
WARNING: more No IPv4 address found on em3 !
Traceback (most recent call last):
  File "/usr/local/homeassistant/bin/scapy", line 8, in <module>
    sys.exit(interact())
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/main.py", line 561, in interact
    SESSION = init_session(session_name, mydict=mydict, ret=True)
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/main.py", line 459, in init_session
    scapy_builtins = _scapy_builtins()
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/main.py", line 307, in _scapy_builtins
    importlib.import_module(".all", "scapy").__dict__.copy()
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/arch/__init__.py", line 131, in <module>
    conf.use_bpf = True
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/config.py", line 114, in __set__
    val = self.hook(self.name, val, old, *self.args, **self.kargs)
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/config.py", line 655, in _socket_changer
    _set_conf_sockets()
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/config.py", line 613, in _set_conf_sockets
    conf.ifaces.reload()
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/arch/bpf/core.py", line 233, in load
    mac = scapy.utils.str2mac(get_if_raw_hwaddr(ifname)[1])
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/arch/bpf/core.py", line 128, in get_if_raw_hwaddr
    mac = [chr(int(b, 16)) for b in mac.split(':')]
  File "/usr/local/homeassistant/lib/python3.8/site-packages/scapy/arch/bpf/core.py", line 128, in <listcomp>
    mac = [chr(int(b, 16)) for b in mac.split(':')]
ValueError: invalid literal for int() with base 16: 'flags=3<LEARNING,DISCOVER>'

### Expected result

Nice & running

### Related resources

Looks simular like #3205

**Comment by Asmeble** [comment]
this needs to be fixed.

**Comment by guedou** [comment]
@pascalnl is this related to FreeBSD or OpenBSD?

**Comment by guedou** [comment]
I could no reproduce the issue on OpenBSD 6.9 on maser. Please add comments, and I will reopen the issue.
