### ISSUE TITLE
pdfdump failed when conf.prog.pdfreader not exists

### ISSUE THREAD

**Issue by dark-lbp** [secdev/scapy#333]
The Problem is Scapy default use acroread as pdf reader. If acroread is not installed on our os, pdfdump will raise this problem.
```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scapy/packet.py", line 417, in pdfdump
    subprocess.Popen([conf.prog.pdfreader, fname+".pdf"])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I am using osx so this code is work for me.
```python
Welcome to Scapy (2.3.3.dev6)
>>> conf.prog.pdfreader = 'open'
>>> a.pdfdump()
KeyboardInterrupt
>>> a=TCP()
>>> a.pdfdump()
WARNING: No IP underlayer to compute checksum. Leaving null.
Ignoring line 17070 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17071 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17072 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17073 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17074 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17075 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17076 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17077 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17078 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17079 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
Ignoring line 17080 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
Ignoring line 17081 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
>>>
```
May be we should try auto find pdfreader applications when init scapy or we just check default pdfreader is exists and warning if conf.prog.pdfreader is not exists?

**Comment by p-l-** [comment]
Fixed in #692
