### ISSUE TITLE
UTscapy LaTeX output support is broken

### ISSUE THREAD

**Issue by zabbal** [secdev/scapy#3359]
### Brief description

When selecting `-f LaTeX` while running UTscapy tests I got the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 1227, in <module>
    sys.exit(main())
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 1156, in main
    output, result, campaign = execute_campaign(
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 921, in execute_campaign
    output = campaign_to_LATEX(test_campaign)
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 799, in campaign_to_LATEX
    output %= info_line(test_campaign)
TypeError: info_line() missing 1 required positional argument: 'theme'

```
Note: the campaign itself works fine (tests pass/fail as usual) - only the LaTeX output generation is borked, the ansi option works fine for example.

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Ubuntu 21.04

### Additional environment information

I'm using tox to run UTscapy in isolated environment.

### How to reproduce

Run some *.uts with LaTeX output.

### Actual result

Exit code 1.

### Expected result

.tex files are generated.

**Comment by zabbal** [comment]
When I look at the code I fail to understand how was it working at all. It seems something like `latex_info_line()` should be used instead of default `info_line()` - similar to `html_info_line()`

Has anyone managed to produce LaTeX output?
