### ISSUE TITLE
Circular import error around scapy.sendrecv

### ISSUE THREAD

**Issue by PeterisP** [secdev/scapy#3415]
### Brief description

I'm trying to apply scripts that rely on scapy and include a line `from scapy.layers.bluetooth import HCI_Hdr, HCI_PHDR_Hdr` which triggers

> ImportError: cannot import name 'send' from partially initialized module 'scapy.sendrecv' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py)

### Scapy version

2.4.5

### Python version

3.9

### Operating system

OS X 11.6

### Additional environment information

I attempted both the pip 2.4.5 version and the latest source from github (2.4.5rc1.dev137), with identical results.

### How to reproduce

1. Open python3
2a. Enter `from scapy.layers.bluetooth import HCI_Hdr, HCI_PHDR_Hdr`
2b. Alternatively, enter `from scapy.sendrecv import sndrcv`
2c. Alternatively, enter `from scapy.sendrecv import send, sniff`

### Actual result

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/site-packages/scapy/layers/bluetooth.py", line 47, in <module>
>     from scapy.sendrecv import sndrcv
>   File "/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py", line 61, in <module>
>     import scapy.route  # noqa: F401
>   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 218, in <module>
>     conf.route = Route()
>   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 37, in __init__
>     self.resync()
>   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 45, in resync
>     from scapy.arch import read_routes
>   File "/usr/local/lib/python3.9/site-packages/scapy/arch/__init__.py", line 124, in <module>
>     from scapy.arch.bpf.supersocket import *  # noqa F403
>   File "/usr/local/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 27, in <module>
>     from scapy.layers.l2 import Loopback
>   File "/usr/local/lib/python3.9/site-packages/scapy/layers/l2.py", line 17, in <module>
>     from scapy.ansmachine import AnsweringMachine
>   File "/usr/local/lib/python3.9/site-packages/scapy/ansmachine.py", line 20, in <module>
>     from scapy.sendrecv import send, sniff
> ImportError: cannot import name 'send' from partially initialized module 'scapy.sendrecv' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py)
>

**Comment by PeterisP** [comment]
I'm sorry, it apparently *does* work properly with the 2.4.5rc1.dev137 version, it looks like that previously I accidentally ran the 2.4.5 pip distribution both times. So the issue is apparently fixed now.
