### ISSUE TITLE
Test read_routes6() - "check mandatory routes" fails on my local machine

### ISSUE THREAD

**Issue by cdleonard** [secdev/scapy#3438]
### Brief description

Ran tests on my personal linux laptop and encountered a failure in ipv6 routing tests. The machine has public ipv6 connectivity which is still not very widespread.

### Scapy version

e28aa5703321 (close to master)

### Python version

3.8

### Operating system

Linux 5.11 Ubuntu 20.04.3 LTS

### How to reproduce

Run `tox -e py38-linux_non_root`

### Actual result

```
###(020)=[failed] Test read_routes6() - check mandatory routes

>>> conf.route6
Destination                                 Next Hop                   Iface      Src candidates                          Metric
::1/128                                     ::                         lo         ::1                                     256   
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
2a04:241e:501:3800::/64                     ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
fe80::/64                                   ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               600   
::1/128                                     ::                         lo         ::1                                     0     
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
2a04:241e:501:3800:97dd:a430:3684:5e53/128  ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
2a04:241e:501:3800:b67c:3d19:75f2:e24a/128  ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
fe80::7316:f7dd:fe9e:db87/128               ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               0     
2a04:241e:501:3800::/57                     fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
::/0                                        fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:97dd:a430:3684:5e53        
>>> 
>>> if len(routes6) > 2 and not WINDOWS:
...     assert(sum(1 for r in routes6 if r[0] == "::1" and r[4] == ["::1"]) >= 1)
...     if not OPENBSD and len(iflist) >= 2:
...         assert sum(1 for r in routes6 if r[0] == "fe80::" and r[1] == 64) >= 1
...         try:
...             assert sum(1 for r in routes6 if in6_islladdr(r[0]) and r[1] == 128 and r[4] == ["::1"]) >= 1
...         except:
...             # IPv6 is not available, but we still check the loopback
...             assert conf.route6.route("::/0") == (conf.loopback_name, "::", "::")
...             assert sum(1 for r in routes6 if r[1] == 128 and r[4] == ["::1"]) >= 1
... else:
...     True
... 
Traceback (most recent call last):
  File "<input>", line 7, in <module>
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 10, in <module>
AssertionError
```

### Expected result

Test should pass

### Related resources

My machine has ipv6 connectivity through a wifi router and it works fine through various public ipv6 testing websites.

It is difficult to understand what the test actual checks for. First failure is on this line:
`            assert sum(1 for r in routes6 if in6_islladdr(r[0]) and r[1] == 128 and r[4] == ["::1"]) >= 1`
It apparently tries to verify that it is possible to reach a fe80::*/128 link-local address from ::1, it's not clear why that should be so. Is my system misconfigured somehow?

An exception is raised and it next jumps to this assertion:
`            assert conf.route6.route("::/0") == (conf.loopback_name, "::", "::")`
This fails again, default route to public ipv6 internet goes through my wifi interface.

**Comment by cdleonard** [comment]
My guess is that the test itself is incorrect but it is not clear how to fix it.

**Comment by guedou** [comment]
Does adding `routes6 = read_routes6()` before `conf.route6` make it works?

**Comment by cdleonard** [comment]
It does not, the previous tests does that anyway.

**Comment by cdleonard** [comment]
Here's more config data from my system:

```
$ ip --oneline -6 addr
1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever
2: wlp0s20f3    inet6 2a04:241e:501:3800::2/128 scope global dynamic noprefixroute \       valid_lft 3362sec preferred_lft 1562sec
2: wlp0s20f3    inet6 2a04:241e:501:3800:fed1:8e49:9777:cd40/64 scope global temporary dynamic \       valid_lft 86397sec preferred_lft 54043sec
2: wlp0s20f3    inet6 2a04:241e:501:3800:b67c:3d19:75f2:e24a/64 scope global dynamic mngtmpaddr noprefixroute \       valid_lft 86397sec preferred_lft 86197sec
2: wlp0s20f3    inet6 fe80::7316:f7dd:fe9e:db87/64 scope link noprefixroute \       valid_lft forever preferred_lft forever

$ ip -6 route
::1 dev lo proto kernel metric 256 pref medium
2a04:241e:501:3800::2 dev wlp0s20f3 proto kernel metric 600 pref medium
2a04:241e:501:3800::/64 dev wlp0s20f3 proto ra metric 600 pref medium
2a04:241e:501:3800::/57 via fe80::8af7:c7ff:fe14:5a06 dev wlp0s20f3 proto ra metric 600 pref medium
fe80::/64 dev wlp0s20f3 proto kernel metric 600 pref medium
default via fe80::8af7:c7ff:fe14:5a06 dev wlp0s20f3 proto ra metric 600 pref medium

$ cat /proc/net/ipv6_route
00000000000000000000000000000001 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000100 00000002 00000000 00000001       lo
2a04241e050138000000000000000002 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000258 00000001 00000000 00000001 wlp0s20f3
2a04241e050138000000000000000000 40 00000000000000000000000000000000 00 00000000000000000000000000000000 00000258 00000004 00000000 00000001 wlp0s20f3
2a04241e050138000000000000000000 39 00000000000000000000000000000000 00 fe800000000000008af7c7fffe145a06 00000258 00000002 00000000 00000003 wlp0s20f3
fe800000000000000000000000000000 40 00000000000000000000000000000000 00 00000000000000000000000000000000 00000258 00000001 00000000 00000001 wlp0s20f3
00000000000000000000000000000000 00 00000000000000000000000000000000 00 fe800000000000008af7c7fffe145a06 00000258 00000009 00000000 00000003 wlp0s20f3
00000000000000000000000000000001 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000000 0000000a 00000000 80200001       lo
2a04241e050138000000000000000002 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000000 00000006 00000000 80200001 wlp0s20f3
2a04241e05013800b67c3d1975f2e24a 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000000 00000002 00000000 80200001 wlp0s20f3
2a04241e05013800fed18e499777cd40 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000000 0000000b 00000000 80200001 wlp0s20f3
fe800000000000007316f7ddfe9edb87 80 00000000000000000000000000000000 00 00000000000000000000000000000000 00000000 00000005 00000000 80200001 wlp0s20f3
ff000000000000000000000000000000 08 00000000000000000000000000000000 00 00000000000000000000000000000000 00000100 00000009 00000000 00000001 wlp0s20f3
00000000000000000000000000000000 00 00000000000000000000000000000000 00 00000000000000000000000000000000 ffffffff 00000001 00000000 00200200       lo
```

I really think this test is incorrect: `assert sum(1 for r in routes6 if in6_islladdr(r[0]) and r[1] == 128 and r[4] == ["::1"]) >= 1`. Why would it be possible to reach link-local addresses with a source of ::1 ???

**Comment by guedou** [comment]
Interesting! Could you share the output of `conf.route6.routes` ? Can you also indicate the Linux distribution that you are using? I am not able to reproduce the issue.

**Comment by cdleonard** [comment]
Isn't this the same data? Here you go:

```
###(020)=[failed] Test read_routes6() - check mandatory routes

>>> from pprint import pprint
>>> 
>>> routes6 = read_routes6()
>>> conf.route6
Destination                                 Next Hop                   Iface      Src candidates                          Metric
::1/128                                     ::                         lo         ::1                                     256   
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800::/64                     ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
fe80::/64                                   ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               600   
::1/128                                     ::                         lo         ::1                                     0     
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800:62ce:939a:33:103d/128    ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800:b67c:3d19:75f2:e24a/128  ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
fe80::7316:f7dd:fe9e:db87/128               ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               0     
2a04:241e:501:3800::/57                     fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
::/0                                        fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
>>> conf.route6.routes
[('::1', 128, '::', 'lo', ['::1'], 256), ('2a04:241e:501:3800::2', 128, '::', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 600), ('2a04:241e:501:3800::', 64, '::', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 600), ('2a04:241e:501:3800::', 57, 'fe80::8af7:c7ff:fe14:5a06', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 600), ('fe80::', 64, '::', 'wlp0s20f3', ['fe80::7316:f7dd:fe9e:db87'], 600), ('::', 0, 'fe80::8af7:c7ff:fe14:5a06', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 600), ('::1', 128, '::', 'lo', ['::1'], 0), ('2a04:241e:501:3800::2', 128, '::', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 0), ('2a04:241e:501:3800:62ce:939a:33:103d', 128, '::', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 0), ('2a04:241e:501:3800:b67c:3d19:75f2:e24a', 128, '::', 'wlp0s20f3', ['2a04:241e:501:3800:b67c:3d19:75f2:e24a', '2a04:241e:501:3800::2', '2a04:241e:501:3800:62ce:939a:33:103d'], 0), ('fe80::7316:f7dd:fe9e:db87', 128, '::', 'wlp0s20f3', ['fe80::7316:f7dd:fe9e:db87'], 0)]
>>> pprint(conf.route6)
Destination                                 Next Hop                   Iface      Src candidates                          Metric
::1/128                                     ::                         lo         ::1                                     256   
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800::/64                     ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
fe80::/64                                   ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               600   
::1/128                                     ::                         lo         ::1                                     0     
2a04:241e:501:3800::2/128                   ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800:62ce:939a:33:103d/128    ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
2a04:241e:501:3800:b67c:3d19:75f2:e24a/128  ::                         wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  0     
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
fe80::7316:f7dd:fe9e:db87/128               ::                         wlp0s20f3  fe80::7316:f7dd:fe9e:db87               0     
2a04:241e:501:3800::/57                     fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
::/0                                        fe80::8af7:c7ff:fe14:5a06  wlp0s20f3  2a04:241e:501:3800:b67c:3d19:75f2:e24a  600   
                                                                                  2a04:241e:501:3800::2                         
                                                                                  2a04:241e:501:3800:62ce:939a:33:103d          
>>> pprint(conf.route6.routes)
[('::1', 128, '::', 'lo', ['::1'], 256),
 ('2a04:241e:501:3800::2',
  128,
  '::',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  600),
 ('2a04:241e:501:3800::',
  64,
  '::',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  600),
 ('2a04:241e:501:3800::',
  57,
  'fe80::8af7:c7ff:fe14:5a06',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  600),
 ('fe80::', 64, '::', 'wlp0s20f3', ['fe80::7316:f7dd:fe9e:db87'], 600),
 ('::',
  0,
  'fe80::8af7:c7ff:fe14:5a06',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  600),
 ('::1', 128, '::', 'lo', ['::1'], 0),
 ('2a04:241e:501:3800::2',
  128,
  '::',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  0),
 ('2a04:241e:501:3800:62ce:939a:33:103d',
  128,
  '::',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  0),
 ('2a04:241e:501:3800:b67c:3d19:75f2:e24a',
  128,
  '::',
  'wlp0s20f3',
  ['2a04:241e:501:3800:b67c:3d19:75f2:e24a',
   '2a04:241e:501:3800::2',
   '2a04:241e:501:3800:62ce:939a:33:103d'],
  0),
 ('fe80::7316:f7dd:fe9e:db87',
  128,
  '::',
  'wlp0s20f3',
  ['fe80::7316:f7dd:fe9e:db87'],
  0)]
>>> 
```

I'm using ubuntu 20.04 LTS but it would be very strange if the distro mattered here. If this works for you: what OS/distro and do you have ipv6 connectivity?

**Comment by guedou** [comment]
Sorry for the answer delay, I have been overwhelmed by personal and professional issues.

How does this patch work for you?
```
git diff
diff --git a/test/regression.uts b/test/regression.uts
index 32b822d7..c69bb063 100644
--- a/test/regression.uts
+++ b/test/regression.uts
@@ -310,11 +310,13 @@ conf.route6
 
 # Doesn't pass on Travis Bionic XXX
 if len(routes6) > 2 and not WINDOWS:
+    # Identify routes to fe80::/64
     assert(sum(1 for r in routes6 if r[0] == "::1" and r[4] == ["::1"]) >= 1)
     if not OPENBSD and len(iflist) >= 2:
         assert sum(1 for r in routes6 if r[0] == "fe80::" and r[1] == 64) >= 1
         try:
-            assert sum(1 for r in routes6 if in6_islladdr(r[0]) and r[1] == 128 and r[4] == ["::1"]) >= 1
+            # Identify a route to a node IPv6 link-local address
+            assert sum(1 for r in routes6 if in6_islladdr(r[0]) and r[1] == 128) >= 1
         except:
             # IPv6 is not available, but we still check the loopback
             assert conf.route6.route("::/0") == (conf.loopback_name, "::", "::")
```

**Comment by cdleonard** [comment]
This patch does fix the bug for me.

**Comment by guedou** [comment]
Thanks. I pushed it to #3491
