### ISSUE TITLE
Test failure: tls.uts "pcapng file with a Decryption Secrets Block"

### ISSUE THREAD

**Issue by cdleonard** [secdev/scapy#3489]
### Brief description

Test failure in tls.uts "pcapng file with a Decryption Secrets Block"

### Scapy version

7e161f1d1fd371887021713b3c0431e0a31f551b

### Python version

3.8.10

### Operating system

Linux 5.11.0

### How to reproduce

 run `tox -e py38-linux_non_root -- -k tshark,linux`

### Actual result

```
Tests for TLS module
━ Run at 10:43:04 from [test/tls.uts] by UTscapy in 0.04992175102233887
 └ Passed=0
 └ Failed=1

######
## Decrypt packets from a pcap
######


###(080)=[failed] pcapng file with a Decryption Secrets Block

>>> bck_conf = conf
>>> 
>>> key_log_path = scapy_path("doc/notebooks/tls/raw_data/tls_nss_example.keys.txt")
>>> pcap_path = scapy_path("doc/notebooks/tls/raw_data/tls_nss_example.pcap")
>>> pcapng_path = get_temp_file()
>>> os.system("editcap --inject-secrets tls,%s %s %s" % (key_log_path, pcap_path, pcapng_path))
0
>>> 
>>> packets = rdpcap(pcapng_path)
>>> assert b"GET /secret.txt HTTP/1.0\n" in packets[11].msg[0].data
>>> assert b"z2|gxarIKOxt,G1d>.Q2MzGY[k@" in packets[13].msg[0].data
>>> 
>>> conf = bck_conf
```

Also fails if I `apt remove wireshark-common` to remove editcap, but in a different way

```
###(080)=[failed] pcapng file with a Decryption Secrets Block

>>> bck_conf = conf
>>> 
>>> key_log_path = scapy_path("doc/notebooks/tls/raw_data/tls_nss_example.keys.txt")
>>> pcap_path = scapy_path("doc/notebooks/tls/raw_data/tls_nss_example.pcap")
>>> pcapng_path = get_temp_file()
>>> os.system("editcap --inject-secrets tls,%s %s %s" % (key_log_path, pcap_path, pcapng_path))
32512
>>> 
>>> packets = rdpcap(pcapng_path)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/leonard/files/work/scapy/scapy/utils.py", line 1116, in rdpcap
    with PcapReader(filename) as fdesc:  # type: ignore
  File "/home/leonard/files/work/scapy/scapy/utils.py", line 1153, in __call__
    raise Scapy_Exception(
scapy.error.Scapy_Exception: No data could be read!
```

**Comment by cdleonard** [comment]
Test seems to fail because os.system returns zero which is a false value for utscapy.

Looking at other tests they mostly do `assert (0 == os.system("foo"))` instead.

The `editcap` tool might be absent so maybe the test should be skipped if it is not present.

I don't know why CI doesn't catch this.

**Comment by cdleonard** [comment]
@guedou this issue was apparently introduced by 9a91a79ffe13e51254076b1a8a2e5f5bab45f612
