### ISSUE TITLE
The error raised by wrong BPF filter syntax is uncaught when using AsyncSniffer.

### ISSUE THREAD

**Issue by cosmin-ionut** [secdev/scapy#3567]
### Brief description

The error raised by wrong BPF filter syntax in AsyncSniffer is not caught.

### Scapy version

2.4.5

### Python version

3.9.7

### Operating system

Linux 5.13.0-37-generic

### Additional environment information

This behavior is only reproducible on Linux, it couldn't be reproduced on Windows.
I didn't try on MAC.

### How to reproduce

**Step 1:**
Open scapy

**Step 2:**
Run the following lines of code:
`e = AsyncSniffer(filter='adawdadadsadaaw')`
`e.start()`

**Step 3:**
Observe that:
- the incorrect filter error is uncaught
- the AsyncSniffer doesn't capture packets
- e.running is True, even though there was an error raised and the AsyncSniffer dosen't catch anything.

### Actual result

```
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/scapy/sendrecv.py", line 1127, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/local/lib/python3.9/dist-packages/scapy/arch/linux.py", line 497, in __init__
    attach_filter(self.ins, filter, self.iface)
  File "/usr/local/lib/python3.9/dist-packages/scapy/arch/linux.py", line 166, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python3.9/dist-packages/scapy/arch/common.py", line 156, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression adawdadadsadaaw (-1)
```

### Expected result

The error should be caught.

**For lack of a better section, I will add more info here:**
After a brief investigation, this behavior might be caused by the fact that:
File scapy/scapy/arch/linux.py line 498, there is a try-except, whose `except `catches only `ImportErrors`:
```
if filter is not None:
    try:
        attach_filter(self.ins, filter, self.iface)
    except ImportError as ex:
        log_runtime.error("Cannot set filter: %s", ex)
```

If the `except` is edited to catch all exceptions, the error is caught and the problematic behavior is eliminated.
```
if filter is not None:
    try:
        attach_filter(self.ins, filter, self.iface)
    except Exception as ex:
        log_runtime.error("Cannot set filter: %s", ex)
```

Example after modification:

```
>>> e = AsyncSniffer(filter='adawdadadsadaaw')
>>> e.start()
>>> ERROR: Cannot set filter: Failed to compile filter expression adawdadadsadaaw (-1)
>>>
>>> e.stop()
<Sniffed: TCP:35 UDP:0 ICMP:0 Other:0>
>>>
```

**Comment by guedou** [comment]
Thanks for reporting this issue? Can you make a PR with a fix?  I will suggest to catch both `ImportError` and `Scapy_Exception`.

**Comment by hktalent** [comment]
@guedou 
macos same error
```
 $ python -V
Python 3.10.9
$ pip list|grep scapy
scapy                          2.5.0
```

error:
```
$ /usr/bin/sudo python z.py
Password:
WARNING: No IPv4 address found on en5 !
WARNING: No IPv4 address found on ap1 !
WARNING: more No IPv4 address found on en10 !
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/CCAK/tools/wifi/z.py", line 12, in <module>
    sniffer = scapy.sniff(iface="en0", filter="wlan.fc.type == 0x08", store=False)
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/sendrecv.py", line 1311, in sniff
    sniffer._run(*args, **kwargs)
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/sendrecv.py", line 1171, in _run
    sniff_sockets[_RL2(iface)(type=ETH_P_ALL, iface=iface,
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/arch/bpf/supersocket.py", line 331, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/arch/bpf/supersocket.py", line 196, in __init__
    attach_filter(self.ins, filter, self.iface)
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/arch/bpf/core.py", line 162, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/Users/51pwn/anaconda3/lib/python3.10/site-packages/scapy/arch/common.py", line 116, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression wlan.fc.type == 0x08 (-1)
```

code:
```
import scapy.all as scapy

# 创建 sniff() 对象
sniffer = scapy.sniff(iface="en0", filter="wlan.fc.type == 0x08", store=False)
# 循环处理数据包
for packet in sniffer:
    # 解析数据包的头部
    radiotap = packet.getlayer(scapy.Radiotap)
    # 解析数据包的帧
    dot11 = packet.getlayer(scapy.Dot11)
    # 打印数据包的信息
    print(radiotap.datarate, dot11.ssid)

```
