### ISSUE TITLE
Documented example on Automata raise the TypeError exception: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by paoloaq** [secdev/scapy#3581]
### Brief description

The [documented "First Example" on Automata](https://scapy.readthedocs.io/en/latest/advanced_usage.html#first-example) raise the exception `TypeError: 'NoneType' object is not callable` on `a=HelloWorld()` call.

### Scapy version

2.4.5

### Python version

3.8.10

### Operating system

Linux 5.13.0-39-generic 

### How to reproduce

```python
from scapy.automaton import Automaton, ATMT

class HelloWorld(Automaton):
    @ATMT.state(initial=1)
    def BEGIN(self):
        print("State=BEGIN")

    @ATMT.condition(BEGIN)
    def wait_for_nothing(self):
        print("Wait for nothing...")
        raise self.END()

    @ATMT.action(wait_for_nothing)
    def on_nothing(self):
        print("Action on 'nothing' condition")

    @ATMT.state(final=1)
    def END(self):
        print("State=END")


if __name__ == '__main__':
	HelloWorld().run()
```

### Actual result

```bash
Exception in thread scapy.automaton _do_start:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/paolo/.virtualenvs/address-resolution-alert/lib/python3.8/site-packages/scapy/automaton.py", line 756, in _do_control
    self.send_sock = self.send_sock_class(**self.socket_kargs)
TypeError: 'NoneType' object is not callable
```

### Expected result

Same as the example in documentation:

```bash
State=BEGIN
Wait for nothing...
Action on 'nothing' condition
State=END
```

**Comment by paoloaq** [comment]
It seems that `send_sock_class` attribute of the `Automaton` class, used in the [`_do_control`](https://github.com/secdev/scapy/blob/master/scapy/automaton.py#L954) method, is not being initialized in the [`__init__`](https://github.com/secdev/scapy/blob/master/scapy/automaton.py#L689).

**Comment by paoloaq** [comment]
Sorry, my fault.

Solved by changing the imports from: `from scapy.automaton import Automaton, ATMT` to: `from scapy.all import *`.

Just an hint: it would be useful to indicate the imports in the sample code in the documentation.
Thanks for the great work!

**Comment by gpotter2** [comment]
You can probably work it out using

```
from scapy.arch import *
from scapy.automaton....
```
