### ISSUE TITLE
[Windows] Scapy does not launch when wpcap.dll is not found

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#365]
The following script could be used to reproduce the issue:
```
from scapy.all import *
print conf
```

The resulting trace is the following:
```
Traceback (most recent call last):
  File "test/dump_conf.py", line 1, in <module>
    from scapy.all import *
  File "C:\projects\scapy-appveyor\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\projects\scapy-appveyor\scapy\arch\__init__.py", line 83, in <module>
    from scapy.arch.windows import *
  File "C:\projects\scapy-appveyor\scapy\arch\windows\__init__.py", line 37, in <module>
    from scapy.arch import pcapdnet
  File "C:\projects\scapy-appveyor\scapy\arch\pcapdnet.py", line 26, in <module>
    from .winpcapy import *
  File "C:\projects\scapy-appveyor\scapy\arch\winpcapy.py", line 26, in <module>
    _lib=CDLL('wpcap.dll')
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

```

**Comment by gpotter2** [comment]
Well we said here:
http://scapy.readthedocs.io/en/latest/installation.html#windows
Than winpcap was needed...

**Comment by gpotter2** [comment]
Talking about links... https://github.com/secdev/scapy/issues/308 is still opened...

**Comment by guedou** [comment]
I think that Scapy should sill be usable without winpcap. For example, it would be nice to be able to use it on Windows as a regular user in order to parser pcap files. That's the current behaviours on other architectures.

Fixing this bug seems possible.

**Comment by gpotter2** [comment]
It does... I can have a look at it if you are not already handling it... What are actually the functions that still need to be useable ?

**Comment by gpotter2** [comment]
I've also started to fix that:
https://github.com/secdev/scapy/pull/380

**Comment by gpotter2** [comment]
@p-l- @guedou So this has been closed right ? And this https://github.com/secdev/scapy/issues/309 can be closed too...

**Comment by guedou** [comment]
Thanks =)

I thought that issues were automatically closed after PR merging.

**Comment by Slowly** [comment]
...so you *HAVE* to have admin rights in order to use scapy, even if you install scapy via pip...?
