### ISSUE TITLE
tubtap doesn't work on Mac os monterey 12.4

### ISSUE THREAD

**Issue by jhay06** [secdev/scapy#3659]
### Brief description

Scapy does not work on mac os monterey 12.4 
I had already installed a tunnelblick to get the notarized tun tap kext

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Mac OS 12.4 Monterey

### Additional environment information

ARm apple silicon

### How to reproduce

from scapy.all import *

t=TunTapInterface('tun0')

### Actual result

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/scapy/layers/tuntap.py", line 171, in __init__
    sock = open(devname, "r+b", buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: b'/dev/tun0'

### Expected result

should create a tun interface

**Comment by guedou** [comment]
Can you test with the master branch?

**Comment by jhay06** [comment]
same error

**Comment by guedou** [comment]
This is unfortunately expected as tun tap is now deprecated on macOS.
