### ISSUE TITLE
[Windows] NameError: global name 'Gen' is not defined

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#367]
Some unit tests are failing due to a missing import in `scapy\arch\windows\compatibility.py`, see:

```
###(053)=[failed] Sending and receiving an ICMP
>>> x=sr1(IP(dst="www.google.com")/ICMP(),timeout=3)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\projects\scapy-appveyor\scapy\sendrecv.py", line 355, in sr1
    a,b=sndrcv(s,x,*args,**kargs)
  File "C:\projects\scapy-appveyor\scapy\arch\windows\compatibility.py", line 14, in sndrcv
    if not isinstance(pkt, Gen):
NameError: global name 'Gen' is not defined
```

**Comment by gpotter2** [comment]
It does work for me... So I guess only in Unit tests ?

```
>>> x=sr1(IP(dst="www.google.com")/ICMP(),timeout=3)
Begin emission:
Finished to send 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
```

**Comment by guedou** [comment]
I was using an old scapy =/
