### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by tkekan** [secdev/scapy#3696]
### Brief description

I already have set the max open files to open files > 1024 i.e. (-n) 1048576 as can be seen from ulimit.
Process Process-4126:
Traceback (most recent call last):
File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
self._target(self._args, self._kwargs)
File "<>", line 286, in send
self._sendComposite(pkt, padToLength)
File "<>", line 276, in _sendComposite
send(packet, verbose=0)
File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 429, in send kargs
File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 394, in _send
socket = socket or _func(iface)(iface=iface, *kargs)
File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 503, in init
_flush_fd(self.ins.fileno())
File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 460, in _flush_fd
r, w, e = select([fd], [], [], 0)
ValueError: filedescriptor out of range in select()

### Scapy version

2.4.5

### Python version

3.6.8

### Operating system

centOS

### How to reproduce

using multiprocess to spawn a prorcess and start scapy send as a task in the process. 

### Actual result

Multiple of below tracebacks after some point.
Process Process-4126:
Traceback (most recent call last):
File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
self._target(self._args, self._kwargs)
File "<>", line 286, in send
self._sendComposite(pkt, padToLength)
File "<>", line 276, in _sendComposite
send(packet, verbose=0)
File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 429, in send kargs
File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 394, in _send
socket = socket or _func(iface)(iface=iface, *kargs)
File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 503, in init
_flush_fd(self.ins.fileno())
File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 460, in _flush_fd
r, w, e = select([fd], [], [], 0)
ValueError: filedescriptor out of range in select()

### Expected result

No error logs

**Comment by tkekan** [comment]
Hello, I had to open this issue since I tried to reach over in https://gitter.im/secdev/scapy but received no response. 
If someone can please take a look at this, I would greatly appreciate it..

**Comment by gpotter2** [comment]
Hi there, 3 things to note:
- Could you retry using master? It appears you're on 2.4.5
- Could you try using a newer version of Python? 3.6 is EOL
- Scapy is not tested (atm) on CentOS :/ so your mileage may vary

**Comment by tkekan** [comment]
Thanks @gpotter2 
* Is there a major diff in 2.4.5 and main that you suspect would solve the issue ?
* I can definitely try with newer PY
* To be more specific it's Oracle Linux on which we tried it out. Any issues there ?

Also is scapy tested with gevent ? Are there any specific observations based on https://www.gevent.org/api/gevent.monkey.html ?

**Comment by gpotter2** [comment]
There are quite a bunch of differences.

Could you share some code? You mentioned you were using multiprocessing, are you able to use Scapy otherwise? When does this issue happen exactly ? Are you spawning multiple Scapy instances?

**Comment by gpotter2** [comment]
Closing for inactivity

**Comment by pale-emperor** [comment]
I have similar problem when spawning multiple Scapy instances

 ```
 Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scapy/automaton.py", line 1098, in _do_control
    self.send_sock = self.send_sock_class(**self.socket_kargs)
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 501, in __init__
    _flush_fd(self.ins.fileno())
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 462, in _flush_fd
    r, w, e = select([fd], [], [], 0)
ValueError: filedescriptor out of range in select()
 ```
