### ISSUE TITLE
WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb5260f30> failed with ''. It was closed.

### ISSUE THREAD

**Issue by gharbit** [secdev/scapy#3707]
Dear community,

HW configuration:
- Board: RPI4
- USB wifi: Alfa awus036acs (RTL8811AU chipset)

SW configuration:
- OS Buster 10
- Kernel Linux 5.10.103
- Scapy 2.4.5

I'm implementing on an RPI4 a beacon packet sniffer based on the scapy-python package. 
It's working correctly until I get this warning:
`WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb5260f30> failed with ''. It was closed.`

Actually, it's an error because no frame is detected after that.

What could be the origin of this error?
Is it a known problem? Is there a corrective patch?

Thanks for your support.

Best Regards,

**Comment by guedou** [comment]
Could you share a small code sample that reproduce the issue?

**Comment by gharbit** [comment]
It's here:
[example.txt](https://github.com/secdev/scapy/files/9252889/example.txt)

**Comment by gharbit** [comment]
Bonjour @guedou 
Any update?

**Comment by gpotter2** [comment]
Could you retry using master?

**Comment by gharbit** [comment]
How to provide the full error log.
I only get this warning displayed on the terminal:
`
WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb5260f30> failed with ''. It was closed`

**Comment by gpotter2** [comment]
Assuming you're on master all you need is
```
from scapy.config import conf
conf.debug_dissector = 2
```

**Comment by gharbit** [comment]
@gpotter2 , @guedou 
I installed the master branch and I added the debug flag.
Actually, it's a memory error.
`WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb52560f0> failed with ''. It was closed.`
`Traceback (most recent call last):
  File "/home/user/app/src/sniffer_wifi_socket.py", line 497, in <module>
    main()
  File "/home/user/app/src/sniffer_wifi_socket.py", line 489, in main
    lfilter=lambda x: x.haslayer(Dot11Beacon), monitor=True)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1305, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1219, in _run
    p = s.recv()
  File "/usr/lib/scapy/scapy/supersocket.py", line 178, in recv
    cls, val, ts = self.recv_raw(x)
  File "/usr/lib/scapy/scapy/arch/linux.py", line 558, in recv_raw
    pkt, sa_ll, ts = self._recv_raw(self.ins, x)
  File "/usr/lib/scapy/scapy/supersocket.py", line 131, in _recv_raw
    pkt, ancdata, flags, sa_ll = sock.recvmsg(x, flags_len)
MemoryError`

I restarted the program and I followed the memory consumption (via htop).
The memory usage increased constantly:
@12h50	-> RAM: 310M
@14h00	-> RAM: 800M
@14h40	-> RAM: 1,05G
@15h05	-> RAM: 1,20G

@ 15h17, I got a new error: 
`ERROR: Dot11Elt dissector failed
ERROR: Dot11Elt dissector failed
ERROR: more Dot11Elt dissector failed
WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb520f0f0> failed with 'maximum recursion depth exceeded'. It was closed.
...
RecursionError: maximum recursion depth exceeded`

Log is here:
[scapy_error2.txt](https://github.com/secdev/scapy/files/9276900/scapy_error2.txt)

Any solution please?
Is there a way to free memory during scapy sniffer run?

Looking forward to receiving your support. Thanks.

**Comment by polydroi** [comment]
I think your PI simply runs out of memory. Storing scapys Packet objects in RAM is not that memory efficient for longer captures.

**Comment by gharbit** [comment]
@polydroi
Yeah, that's what I mentioned in my last comment.
So what's the solution for a long capture 24h/24h?

**Comment by polydroi** [comment]
In your application, you can also reduce the memory consumption of sniff by providing the argument `store=False`

From what I've seen in your example, sniff is preserving a list of captured Packet objects, even if you are not using them.

**Comment by gpotter2** [comment]
Good point. This should fix it

**Comment by gharbit** [comment]
Fixed the above error, but got another one each running hour:

`ERROR: IP dissector failed
ERROR: SNAP dissector failed
ERROR: more LLC dissector failed
WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb52290b0> failed with 'unpack requires a buffer of 4 bytes'. It was closed.
Traceback (most recent call last):
  File "/home/user/app/src/sniffer_wifi_socket.py", line 497, in <module>
    main()
  File "/home/user/app/src/sniffer_wifi_socket.py", line 489, in main
    lfilter=lambda x: x.haslayer(Dot11Beacon), monitor=True, store=False)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1305, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1219, in _run
    p = s.recv()
  File "/usr/lib/scapy/scapy/supersocket.py", line 182, in recv
    pkt = cls(val)  # type: Packet
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1033, in dissect
    self.do_dissect_payload(payl)
  File "/usr/lib/scapy/scapy/packet.py", line 1008, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1033, in dissect
    self.do_dissect_payload(payl)
  File "/usr/lib/scapy/scapy/packet.py", line 1008, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1033, in dissect
    self.do_dissect_payload(payl)
  File "/usr/lib/scapy/scapy/packet.py", line 1008, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1033, in dissect
    self.do_dissect_payload(payl)
  File "/usr/lib/scapy/scapy/packet.py", line 1008, in do_dissect_payload
    p = cls(s, _internal=1, _underlayer=self)
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1028, in dissect
    s = self.do_dissect(s)
  File "/usr/lib/scapy/scapy/packet.py", line 985, in do_dissect
    s, fval = f.getfield(self, s)
  File "/usr/lib/scapy/scapy/fields.py", line 1757, in getfield
    p = self.m2i(pkt, remain)
  File "/usr/lib/scapy/scapy/fields.py", line 1505, in m2i
    return self.cls(m, _parent=pkt)  # type: ignore
  File "/usr/lib/scapy/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/scapy/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/usr/lib/scapy/scapy/packet.py", line 1028, in dissect
    s = self.do_dissect(s)
  File "/usr/lib/scapy/scapy/packet.py", line 985, in do_dissect
    s, fval = f.getfield(self, s)
  File "/usr/lib/scapy/scapy/fields.py", line 2049, in getfield
    s, v = self.field.getfield(pkt, s)
  File "/usr/lib/scapy/scapy/fields.py", line 263, in getfield
    return s[self.sz:], self.m2i(pkt, self.struct.unpack(s[:self.sz])[0])
struct.error: unpack requires a buffer of 4 bytes
`

**Comment by polybassa** [comment]
Could you please provide the raw packet that triggered this error?

`conf.debug_dissector=True` should produce a more meaningful output.

**Comment by gpotter2** [comment]
You should keep `conf.debug_dissector` disabled in general, when you're not debugging.

**Comment by gharbit** [comment]
It's strange.
I cannot reproduce the same error.

The wifi usb is plugged well in the RPI4. I'm not connected to any Acces Point. But, now I get the following error:
`WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0xb5235110> failed with '[Errno 100] Network is down'. It was closed.
Traceback (most recent call last):
  File "/home/user/app/src/sniffer_wifi_socket.py", line 506, in <module>
    main()
  File "/home/user/app/src/sniffer_wifi_socket.py", line 498, in main
    lfilter=lambda x: x.haslayer(Dot11Beacon), monitor=True, store=False)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1305, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/scapy/scapy/sendrecv.py", line 1219, in _run
    p = s.recv()
  File "/usr/lib/scapy/scapy/supersocket.py", line 178, in recv
    cls, val, ts = self.recv_raw(x)
  File "/usr/lib/scapy/scapy/arch/linux.py", line 558, in recv_raw
    pkt, sa_ll, ts = self._recv_raw(self.ins, x)
  File "/usr/lib/scapy/scapy/supersocket.py", line 131, in _recv_raw
    pkt, ancdata, flags, sa_ll = sock.recvmsg(x, flags_len)
OSError: [Errno 100] Network is down
Error for wireless request "Set Frequency" (8B04) :
    SET failed on device wlan0 ; No such device.
`

**Comment by gharbit** [comment]
@polybassa @gpotter2 
Any update?

**Comment by gpotter2** [comment]
Clearly this isn't a bug but a mis-usage. Please note that this is a bug tracker and not a forum.
