### ISSUE TITLE
RandTCPOptions fails to randomize MD5 (exception triggered)

### ISSUE THREAD

**Issue by nrathaus** [secdev/scapy#3777]
### Brief description

In the latest version (from git) there is a bug in the RandTCPOptions code where the '16s' of MD5 is treated incorrectly due to:
```
for stru in structs:
```

Being used on the string '16s', which results in:
`stru`
being used with this function:
`struct.calcsize(stru)`

Which for the case of:
`struct.calcsize('1')`

An exception is triggered

### Scapy version

git master

### Python version

3.9

### Operating system

MacOS (but the bug is unrelated)

### How to reproduce

The "easiest" way to trigger this bug is to do:
```
import scapy.all
payload = scapy.all.Ether()/scapy.all.IP(dst='192.168.15.1')/scapy.all.TCP()
p = scapy.all.fuzz(payload)
p.show2()
```

And then to start fuzzing, when the fuzzing falls on the "RandTCPOptions" and MD5 as the field to randomize, an exception is triggered (note that the line numbers don't match as I modified the code to try and trace this issue... sorry :) ) :
```
Cannot calcsize for [!1], error: repeat count given without format specifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1686, in show2
    return self.__class__(raw(self)).show(dump, indent, lvl, label_lvl)
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/compat.py", line 294, in raw
    return bytes(x)
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 589, in __bytes__
    return self.build()
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 954, in build
    p = self.do_build()
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 709, in do_build
    self = next(iter(self))
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1346, in loop
    for payl in payloads:
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  [Previous line repeated 6 more times]
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1346, in loop
    for payl in payloads:
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1339, in loop
    for x in loop(todo[:], done):
  [Previous line repeated 6 more times]
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/packet.py", line 1351, in loop
    done2[k] = done2[k]._fix()
  File "/opt/homebrew/lib/python3.10/site-packages/scapy/layers/inet.py", line 384, in _fix
    v = random.randint(0, 2 ** (8 * _size) - 1)
```

### Actual result

An exception is triggered

### Expected result

Showing a packet dump of a random MD5

### Related resources

The following patch can be used to resolve it, scapy/layers/inet.py, from:
```
                for stru in structs:
```

To this:
```
                struct_list = list(structs) # split it char by char
                if 's' in structs:
                    # We need to split it with the number before the 's'
                    struct_list = [structs]

                for stru in struct_list:
```

You can probably make a better fix

**Comment by gpotter2** [comment]
Thanks for the report. I've made a PR over https://github.com/secdev/scapy/pull/3784
Could you try it out? Thanks
