### ISSUE TITLE
[AutoCompletion/Windows] Crash when does not exist

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#385]
Scapy crash when trying to auto-complete when the object does not exist...

```
>>> do_not_exist.[I PRESSED TAB]
Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 381, in interact
    local=session, readfunc=conf.readfunc)
  File "C:\Python27\lib\code.py", line 306, in interact
    console.interact(banner)
  File "C:\Python27\lib\code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "C:\Python27\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "C:\Python27\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "C:\Python27\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "C:\Python27\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "C:\Python27\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "C:\Python27\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "C:\Python27\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "C:\Python27\lib\rlcompleter.py", line 83, in complete
    self.matches = self.attr_matches(text)
  File "C:\Python27\lib\site-packages\scapy\main.py", line 242, in attr_matches
    object = eval(expr, session)
  File "<string>", line 1, in <module>
NameError: name 'do_not_exist' is not defined
```

**Comment by gpotter2** [comment]
Tiny fix for that in https://github.com/secdev/scapy/pull/386

**Comment by p-l-** [comment]
Is this Windows-specific? I cannot reproduce.

**Comment by gpotter2** [comment]
Yes it is. It's the compatibility part with "pyreadline" that break
