### ISSUE TITLE
StreamSocket didn't inherit socket's timeout value 

### ISSUE THREAD

**Issue by dark-lbp** [secdev/scapy#390]
`StreamSocket.sr1` didn't inherit socket's timeout value.
```python
WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: Combined crypto modes not available for IPsec (pycrypto 2.7a1 required).
Welcome to Scapy (2.3.3.dev53)
>>> import time
>>> nic = 'en4'
>>> host = '192.168.70.210'
>>> port = 161
>>> packet1 = 'some data'
>>>
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> sock.connect((host, port))
>>> sock.settimeout(2)
>>> connection = StreamSocket(sock, Raw)
>>>
>>> # use socket's send and recv
>>> start = time.time()
>>> connection.send(Raw(packet1))
9
>>> connection.recv()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scapy/supersocket.py", line 127, in recv
    pkt = self.ins.recv(x, socket.MSG_PEEK)
timeout: timed out
>>> end = time.time()
>>> print("current timeout is: %s" % (end - start))
current timeout is: 2.00608706474
>>>
>>> # use StreamSocket's sr1
>>> start = time.time()
>>> connection.sr1(Raw(packet1))
# this will stuck a long time
```

I think StreamSocket should inherit sock‘s timeout by default.  Is this make sense?

**Comment by dark-lbp** [comment]
There is some additional info.
OS:  MacOS 10.12.2
some info from scapy.conf
```
L2listen   = <L2bpfListenSocket: read/write packets using BPF>
L2socket   = <L2bpfSocket: read/write packets using BPF>
L3socket   = <L3bpfSocket: read/write packets using BPF>
use_bpf    = True
use_dnet   = False
use_pcap   = False
use_winpcapy = False
verb       = 2
version    = '2.3.3.dev53'
```

**Comment by dark-lbp** [comment]
Hmm, `StreamSocket.sr1` actual running `sendrecv.sndrcv`, it's a little bit complex than i think.
Looks like the only chose is add timeout parameter to `StreamSocket.sr1` like `StreamSocket.sr1(packet, timeout=2)`
