### ISSUE TITLE
UTscapy misses syntax errors

### ISSUE THREAD

**Issue by evverx** [secdev/scapy#3962]
### Brief description

UTscapy can miss syntax errors like
```python
>>> RTRErrorReport in pkt and pkt.error_code == 1and pkt.error_text == b'Internal Error'
Traceback (most recent call last):
  File "/usr/lib64/python3.11/codeop.py", line 153, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/codeop.py", line 118, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 2
    RTRErrorReport in pkt and pkt.error_code == 1and pkt.error_text == b'Internal Error'
                                                ^
SyntaxError: invalid decimal literal
```
because under the hood it uses `code.InteractiveInterpreter().runsource(...)` and it swallows syntax errors unless syntax warnings are treated as errors:
```python
code.InteractiveInterpreter().runsource('1and 2')
<input>:1: SyntaxWarning: invalid decimal literal
2
False
```

### Scapy version

55cc32cc89a293e5947bef620eca342935a12866

### Python version

3.11.2

### Operating system

6.2.7-200.fc37.x86_64

### How to reproduce

It can be reproduced by running the scapy testsuite where the RTR test passes even though it contains
```python
RTRErrorReport in pkt and pkt.error_code == 1and pkt.error_text == b'Internal Error'
```

I fixed it locally with
```diff
diff --git a/scapy/autorun.py b/scapy/autorun.py
index 7cc21633..79d9e0cb 100644
--- a/scapy/autorun.py
+++ b/scapy/autorun.py
@@ -15,6 +15,7 @@ from queue import Queue
 import sys
 import threading
 import traceback
+import warnings

 from scapy.config import conf
 from scapy.themes import NoTheme, DefaultTheme, HTMLTheme2, LatexTheme2
@@ -81,8 +82,10 @@ def autorun_commands(_cmds, my_globals=None, verb=None):
                 print(line)
                 cmd += "\n" + line
                 sys.last_value = None
-                if interp.runsource(cmd):
-                    continue
+                with warnings.catch_warnings():
+                    warnings.simplefilter('error', SyntaxWarning)
+                    if interp.runsource(cmd):
+                        continue
                 if sys.last_value:  # An error occurred
                     traceback.print_exception(sys.last_type,
                                               sys.last_value,
```
but I'm not sure whether it's the right fix because `catch_warnings` isn't thread-safe and as far as I can see there are threads there. I'll try to take a closer look later but in the meantime I fixed all the syntax errors in https://github.com/secdev/scapy/pull/3960. It should make it easier to bring the right fix eventually.

**Comment by evverx** [comment]
I think that apart from syntax errors catching all sort of warnings there would be useful. It could make it easier to catch issues like
```python
>>> p = PipeEngine()
>>>
>>> s = RdpcapSource(os.path.join(dname, "t.pcap"))
>>> d1 = Drain(name="d1")
>>> c = WrpcapSink(os.path.join(dname, "t2.pcap"), name="c")
>>> s > d1 > c
<c [d1>#]>
>>> p.add(s)
>>> p.start()
Exception ignored in: <_io.FileIO name='/tmp/scapylk1khphf/t.pcap' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/vagrant/scapy-2/scapy/scapypipes.py", line 110, in start
    self.f = PcapReader(self.fname)
    ^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/scapylk1khphf/t.pcap'>
```

**Comment by gpotter2** [comment]
There's actually a mode in UTscapy to enable all warnings: https://github.com/secdev/scapy/blob/1eaa24f855aa00f4957310a900c1cc91ac5af067/scapy/tools/UTscapy.py#L1245 but we had to disable (from memory) because some dependencies threw some and we had no control over it. Maybe we could enable some warnings on a specific basis (ResourceWarning could be a good idea).

For SyntaxWarning in the meantime: https://github.com/secdev/scapy/pull/4260
