### ISSUE TITLE
Packet __setitem__ results in  'NoneType' object has no attribute 'payload'

### ISSUE THREAD

**Issue by stefanDeveloper** [secdev/scapy#3965]
### Brief description

I'm trying to manipulate the IP layer of a provided PCAP file (https://github.com/zeek/zeek/blob/master/testing/btest/Traces/tcp/payload-syn.pcap). However, if I run the provided example code, I get the following result:

```
Traceback (most recent call last):
  File "/home/smachmeier/projects/emcl/heiFIP/example.py", line 15, in <module>
    packets[3][IP] = buf
  File "/home/smachmeier/projects/emcl/heiFIP/.venv/lib/python3.10/site-packages/scapy/packet.py", line 1337, in __setitem__
    self[cls].underlayer.payload = val
AttributeError: 'NoneType' object has no attribute 'payload'
```
Wireshark view:

![image](https://user-images.githubusercontent.com/18898803/228834937-4aaaade5-b440-462c-8105-0dec9baab413.png)

Using `show()` reveals:

```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 140
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = tcp
  chksum    = 0xf917
  src       = 192.168.0.1
  dst       = 192.168.0.2
  \options   \
###[ TCP ]### 
     sport     = http
     dport     = http
     seq       = 10
     ack       = 0
     dataofs   = 5
     reserved  = 0
     flags     = S
     window    = 8192
     chksum    = 0xc4e2
     urgptr    = 0
     options   = []
###[ HTTP 1 ]### 
###[ HTTP Request ]### 
        Method    = 'GET'
        Path      = '//index.php?page=../../../etc/passwd'
        Http_Version= 'HTTP/1.1'
        A_IM      = None
        Accept    = '*/*'
        Accept_Charset= None
        Accept_Datetime= None
        Accept_Encoding= None
        Accept_Language= None
        Access_Control_Request_Headers= None
        Access_Control_Request_Method= None
        Authorization= None
        Cache_Control= None
        Connection= None
        Content_Length= None
        Content_MD5= None
        Content_Type= None
        Cookie    = None
        DNT       = None
        Date      = None
        Expect    = None
        Forwarded = None
        From      = None
        Front_End_Https= None
        HTTP2_Settings= None
        Host      = None
        If_Match  = None
        If_Modified_Since= None
        If_None_Match= None
        If_Range  = None
        If_Unmodified_Since= None
        Keep_Alive= None
        Max_Forwards= None
        Origin    = None
        Permanent = None
        Pragma    = None
        Proxy_Authorization= None
        Proxy_Connection= None
        Range     = None
        Referer   = None
        Save_Data = None
        TE        = None
        Upgrade   = None
        Upgrade_Insecure_Requests= None
        User_Agent= 'czxt2s'
        Via       = None
        Warning   = None
        X_ATT_DeviceId= None
        X_Correlation_ID= None
        X_Csrf_Token= None
        X_Forwarded_For= None
        X_Forwarded_Host= None
        X_Forwarded_Proto= None
        X_Http_Method_Override= None
        X_Request_ID= None
        X_Requested_With= None
        X_UIDH    = None
        X_Wap_Profile= None
        Unknown_Headers= None
###[ Raw ]### 
           load      = '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

However `packets[0].underlayer` is `None`.

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Linux 5.19.0-35

### How to reproduce

```python
from scapy.all import rdpcap
from scapy.layers.inet import IP

packets = rdpcap("./payload-syn.pcap")

buf = packets[0][IP]
packets[0][IP] = buf
```

With the PCAP https://github.com/zeek/zeek/blob/master/testing/btest/Traces/tcp/payload-syn.pcap

### Actual result

```
Traceback (most recent call last):
  File "/home/smachmeier/projects/emcl/heiFIP/example.py", line 15, in <module>
    packets[3][IP] = buf
  File "/home/smachmeier/projects/emcl/heiFIP/.venv/lib/python3.10/site-packages/scapy/packet.py", line 1337, in __setitem__
    self[cls].underlayer.payload = val
AttributeError: 'NoneType' object has no attribute 'payload'
```

### Expected result

Manipulating the IP layer should work fine.
Using the trace https://github.com/zeek/zeek/blob/master/testing/btest/Traces/tcp/syn.pcap works fine.

**Comment by gpotter2** [comment]
You can't assign the root packet in Scapy. You're basically doing:

```
>>> a = IP()/TCP()
>>> a[IP] = IP()
```

which is meaningless.
