### ISSUE TITLE
scapy/fields.py", line 2495, in any2i_one     x = self.s2i[x] KeyError: '0'

### ISSUE THREAD

**Issue by azuryl** [secdev/scapy#3996]
### Brief description

from scapy.all import *
from scapy.layers.dot11 import Dot11,Dot11Action

csi_req = RadioTap() / Dot11(addr1="ff:ff:ff:ff:ff:ff",addr2="40:1c:83:8d:c3:bd",addr3="1c:83:8d:a0:09") / Dot11Action(category="0",action="17") \
          / Dot11HECapabilities(mac_padding_0=0,csi_supported=1,channel_width_set=0b1111)

sendp(csi_req,iface="wlan1mon")

### Scapy version

 scapy-2.5.0.dev85

### Python version

3.8.16

### Operating system

Nvidia ubuntu 5.10.104-tegra

### How to reproduce

run the script

from scapy.all import *
from scapy.layers.dot11 import Dot11,Dot11Action

csi_req = RadioTap() / Dot11(addr1="ff:ff:ff:ff:ff:ff",addr2="40:1c:83:8d:c3:bd",addr3="1c:83:8d:a0:09") / Dot11Action(category="0",action="17") \
          / Dot11HECapabilities(mac_padding_0=0,csi_supported=1,channel_width_set=0b1111)

sendp(csi_req,iface="wlan1mon")

### Actual result

send succ

### Expected result

python send_bef.py 
Traceback (most recent call last):
  File "send_bef.py", line 4, in <module>
    csi_req = RadioTap() / Dot11(addr1="ff:ff:ff:ff:ff:ff",addr2="40:1c:83:8d:c3:bd",addr3="1c:83:8d:a0:09") / Dot11Action(category="0",action="17") \
  File "/data/anaconda/envs/sensor/lib/python3.8/site-packages/scapy/base_classes.py", line 398, in __call__
    i.__init__(*args, **kargs)
  File "/data/anaconda/envs/sensor/lib/python3.8/site-packages/scapy/packet.py", line 189, in __init__
    self.get_field(fname).any2i(self, value)
  File "/data/anaconda/envs/sensor/lib/python3.8/site-packages/scapy/fields.py", line 2519, in any2i
    return self.any2i_one(pkt, x)
  File "/data/anaconda/envs/sensor/lib/python3.8/site-packages/scapy/fields.py", line 2495, in any2i_one
    x = self.s2i[x]
KeyError: '0'

**Comment by gpotter2** [comment]
category="0"
