### ISSUE TITLE
[Windows] IndexError: list index out of range

### ISSUE THREAD

**Issue by weyou** [secdev/scapy#400]
Scapy cannot be imported from my windows host.  Here is the error message.
```
C:\Windows\system32>py -2
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 83, in <modu
le>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 319,
 in <module>
    IFACES.load_from_powershell()
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 271,
 in load_from_powershell
    for i in get_windows_if_list():
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 207,
 in get_windows_if_list
    for line in query)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 206,
 in <genexpr>
    (dict(zip(['name', 'win_index', 'description', 'guid', 'mac'], line))
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 54,
in _exec_query_ps
    l.append(line.split(':', 1)[1].strip())
IndexError: list index out of range
```

I checked the output from the PowerShell. One of the interface node is like this:
```
Name                 : Cisco AnyConnect Secure Mobility Client Virtual Miniport
                        Adapter for Windows x64
InterfaceIndex       : 27
InterfaceDescription :
GUID                 : {BBC11E80-1C5A-4581-AA05-D9FA8B6C67B1}
MacAddress           :
```

Note that the name of Cisco AnyConnect interface has a line breaking.  Here is the patch:
```
def _exec_query_ps(cmd, fields):
    """Execute a PowerShell query"""
    ps = sp.Popen([conf.prog.powershell] + cmd +
                  ['|', 'select %s' % ', '.join(fields), '|', 'fl'],
                  stdout=sp.PIPE,
                  universal_newlines=True)
    l=[]
    for line in ps.stdout:
        if not line.strip(): #skip empty lines
            continue

+       fv = line.split(':', 1)
+       if len(fv) == 1:
+           l[-1] += fv[0].strip()
+           continue
+       else:
+           l.append(fv[1].strip())
+
-       l.append(line.split(':', 1)[1].strip())
        if len(l) == len(fields):
            yield l
            l=[]
```

**Comment by gpotter2** [comment]
Thanks for reporting the bug... but i don't like the way you fixed it...
_exec_query_ps should be working whatever is inside, not only when ":" is on each line
