### ISSUE TITLE
SNMP endOfMibView causes exception

### ISSUE THREAD

**Issue by nrathaus** [secdev/scapy#4294]
### Brief description

The following pkt:
```
b'03\x02\x01\x01\x04\x06public\xa2&\x02\x01\x00\x02\x01\x00\x02\x01\x000\x1b0\x19\x06\x15+\x06\x01\x06\x03\x10\x01\x05\x02\x01\x06\x07comview\x01\x01\x82\x00'
```

Causes an exception in Scapy:
BER_Decoding_Error("Unknown prefix [82] for [b'\\x82\\x00']")

Minimal test case:
```
res = b'03\x02\x01\x01\x04\x06public\xa2&\x02\x01\x00\x02\x01\x00\x02\x01\x000\x1b0\x19\x06\x15+\x06\x01\x06\x03\x10\x01\x05\x02\x01\x06\x07comview\x01\x01\x82\x00'
pkt = scapy.layers.snmp.SNMP(_pkt=res)
```

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Ubuntu 22.04

### How to reproduce

Run this script:
```
res = b'03\x02\x01\x01\x04\x06public\xa2&\x02\x01\x00\x02\x01\x00\x02\x01\x000\x1b0\x19\x06\x15+\x06\x01\x06\x03\x10\x01\x05\x02\x01\x06\x07comview\x01\x01\x82\x00'
pkt = scapy.layers.snmp.SNMP(_pkt=res)
```

### Actual result

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/test/venv/lib/python3.10/site-packages/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 1029, in dissect
    s = self.do_dissect(s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1packet.py", line 55, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 496, in dissect
    _, x = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 487, in m2i
    s = obj.dissect(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 200, in dissect
    v, s = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 741, in m2i
    return self.extract_packet(choice, s, _underlayer=pkt)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 183, in extract_packet
    c = cls(s, _underlayer=_underlayer)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 1029, in dissect
    s = self.do_dissect(s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1packet.py", line 55, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 496, in dissect
    _, x = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 487, in m2i
    s = obj.dissect(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 200, in dissect
    v, s = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 572, in m2i
    c, s = self._extract_packet(s, pkt)  # type: ignore
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 537, in <lambda>
    self._extract_packet = lambda s, pkt: self.extract_packet(
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 183, in extract_packet
    c = cls(s, _underlayer=_underlayer)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 165, in __init__
    self.dissect(_pkt)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/packet.py", line 1029, in dissect
    s = self.do_dissect(s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1packet.py", line 55, in do_dissect
    return self.ASN1_root.dissect(self, x)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 496, in dissect
    _, x = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 487, in m2i
    s = obj.dissect(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 200, in dissect
    v, s = self.m2i(pkt, s)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1fields.py", line 152, in m2i
    return codec.dec(s, context=self.context)  # type: ignore
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1/ber.py", line 372, in dec
    return cls.do_dec(s, context, safe)
  File "/home/test/venv/lib/python3.10/site-packages/scapy/asn1/ber.py", line 353, in do_dec
    raise BER_Decoding_Error("Unknown prefix [%02x] for [%r]" %
scapy.asn1.ber.BER_Decoding_Error: Unknown prefix [82] for [b'\x82\x00']
### Already decoded ###
None
### Remaining ###
b'\x82\x00'
```

### Expected result

No error (SNMP packet is valid):
```
Simple Network Management Protocol
    version: v2c (1)
    community: public
    data: get-response (2)
        get-response
            request-id: 0
            error-status: noError (0)
            error-index: 0
            variable-bindings: 1 item
                1.3.6.1.6.3.16.1.5.2.1.6.7.99.111.109.118.105.101.119.1.1: endOfMibView
                    Object Name: 1.3.6.1.6.3.16.1.5.2.1.6.7.99.111.109.118.105.101.119.1.1 (iso.3.6.1.6.3.16.1.5.2.1.6.7.99.111.109.118.105.101.119.1.1)
                    endOfMibView
                        [Expert Info (Note/Response): endOfMibView]
    [Response To: 14257]
    [Time: 0.024067280 seconds]
```

**Comment by gpotter2** [comment]
I can't reproduce on master.

**Comment by nrathaus** [comment]
@gpotter2  it seems it was a bug in my version (older than master) - I think 'version 2.5.0' is not a good benchmark when finding issues

You can close this

**Comment by gpotter2** [comment]
You are correct, which is why the issue template explcitly says 

> Please check that you are using the latest Scapy version, e.g. installed via:
pip install --upgrade git+https://github.com/secdev/scapy.git
