### ISSUE TITLE
[Modules/Windows] Crashing on start scapy modules

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#432]
**Following roadmap https://github.com/secdev/scapy/issues/399**

While testing stuff on every scapy file, i've noticed out that some modules were not working at all (crashing) when importing.
Here's my list:

**Windows only:**
-
- modules.VoIP:
```
>>> from scapy.modules.voip import *
Traceback (most recent call last):
  File "Z:\github\scapy\scapy\modules\voip.py", line 15, in <module>
    from fcntl import fcntl
ImportError: No module named fcntl
```
- contrib.ppi_geotag.py
```
>>> from scapy.contrib.ppi_geotag import *
Traceback (most recent call last):
  File "Z:\github\scapy\scapy\contrib\ppi_geotag.py", line 338, in <module>
    Fixed6_4Field("Altitude_g", None),   GPSTime_Field("GPSTime", None),
  File "Z:\github\scapy\scapy\contrib\ppi_geotag.py", line 193, in __init__
    return LETimeField.__init__(self, name, default, strf="%a, %d %b %Y %H:%M:%S UTC")
  File "Z:\github\scapy\scapy\contrib\ppi_geotag.py", line 174, in __init__
    self.delta = time.mktime(epoch) - time.mktime(time.gmtime(0))
OverflowError: mktime argument out of range
```

**Comment by gpotter2** [comment]
Both fixed
