### ISSUE TITLE
smbclientserver test timing out in autopkgtest

### ISSUE THREAD

**Issue by charles2910** [secdev/scapy#4338]
Since you guys are a very nice - VERY NICE, really! - upstream and want to go deep in this samba time out issue inside autopkgtest, I'm creating this new issue so we don't carry a 50+ email thread going forward.

Hey there, I've following the discussion and I missed this one:

> On a somewhat related note in terms of packaging the "samba-client", "samba" and "python3-tkinter" packages should be added to the list of build/test dependencies to get the test suite to pass with the master branch/next version of scapy

I do have a question though about the `smbclientserver.uts`. I'm packaging a snapshot of the master branch for reasons (supporting `python-cryptography >= 42`, see [#1067409](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067409)) and smbclientserver tests are timing out. I'm wondering if it's a limitation of the environment I'm running the tests (schroot) or if it might be a bug in scapy or samba. Could you guys give me a hand here?

<details><summary>Autopkgtest logs</summary>
<p>

```
SMB2 Client and Server tests
━ Run at 04:28:46 from [test/scapy/layers/smbclientserver.uts] by UTscapy in 17.82572913169861
 └ Passed=5
 └ Failed=5

######
## SMB2 Client tests
######


###(001)=[failed] smbclient: connect then list shares

>>> with run_smbserver():
...    try:
...       cli = run_smbclient()
...       results = cli.shares()
...       print(results)
...       assert ('test', 'DISKTREE', 'Test share') in results
...       assert any(x[0] == "IPC$" for x in results)
...    finally:
...       cli.close()
...
@ Starting smbd server
@ Server started !
Starting control thread [tid=140005375342272]
## state=[BEGIN]
Condition [continue_smb2] not taken
Condition [send_negotiate] taken to state [SENT_NEGOTIATE]
   + Running action [on_negotiate]
SENT : DirectTCP / SMB_Header / SMBNegotiate_Request
switching from [BEGIN] to [SENT_NEGOTIATE]
## state=[SENT_NEGOTIATE]
Stopping control thread (tid=140005375342272)
@ Stopping smbd server !

Test failed. Smbd logs:
[2024/03/23 04:28:28.724838,  0] source3/smbd/server.c:1746(main)
  smbd version 4.19.5-Debian started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
[2024/03/23 04:28:28.728109,  1] source3/profile/profile.c:49(set_profile_level)
  INFO: Profiling turned OFF from pid 257574
[2024/03/23 04:28:28.737263,  1] source3/passdb/pdb_tdb.c:540(tdbsam_open)
  tdbsam_open: Converting version 0.0 database to version 4.0.
[2024/03/23 04:28:28.737408,  1] source3/passdb/pdb_tdb.c:305(tdbsam_convert_backup)
  tdbsam_convert_backup: updated /tmp/scapyb3uq36xm/private/passdb.tdb file.
[2024/03/23 04:28:29.173125,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2024/03/23 04:28:29.173181,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN1.0]
[2024/03/23 04:28:29.173195,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [Windows for Workgroups 3.1a]
[2024/03/23 04:28:29.173203,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LM1.2X002]
[2024/03/23 04:28:29.173210,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN2.1]
[2024/03/23 04:28:29.173217,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [NT LM 0.12]
[2024/03/23 04:28:29.173225,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.002]
[2024/03/23 04:28:29.173232,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.???]
[2024/03/23 04:28:29.173415,  3] source3/smbd/smb2_negprot.c:345(smbd_smb2_request_process_negprot)
  Selected protocol SMB2_FF

@ smbd server stopped !
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "<input>", line 3, in run_smbclient
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 952, in __init__
    self.smbsock = SMB_SOCKET(self.sock)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 485, in __init__
    raise TimeoutError(
TimeoutError: The SMB handshake timed out ! (enable debug=1 for logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 10, in <module>
NameError: name 'cli' is not defined


###(002)=[failed] smbclient: connect to test share and list files

>>> with run_smbserver():
...    try:
...       cli = run_smbclient()
...       cli.use("test")
...       files = cli.ls()
...       names = [x[0] for x in files]
...       assert all(x in names for x in ['.', '..', 'sub', 'fileB', 'fileScapy', 'fileA'])
...    finally:
...       cli.close()
...
@ Starting smbd server
@ Server started !
Starting control thread [tid=140005375342272]
## state=[BEGIN]
Condition [continue_smb2] not taken
Condition [send_negotiate] taken to state [SENT_NEGOTIATE]
   + Running action [on_negotiate]
SENT : DirectTCP / SMB_Header / SMBNegotiate_Request
switching from [BEGIN] to [SENT_NEGOTIATE]
## state=[SENT_NEGOTIATE]
Stopping control thread (tid=140005375342272)
@ Stopping smbd server !

Test failed. Smbd logs:
[2024/03/23 04:28:32.247052,  0] source3/smbd/server.c:1746(main)
  smbd version 4.19.5-Debian started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
[2024/03/23 04:28:32.249314,  1] source3/profile/profile.c:49(set_profile_level)
  INFO: Profiling turned OFF from pid 257602
[2024/03/23 04:28:32.691677,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2024/03/23 04:28:32.691721,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN1.0]
[2024/03/23 04:28:32.691730,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [Windows for Workgroups 3.1a]
[2024/03/23 04:28:32.691739,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LM1.2X002]
[2024/03/23 04:28:32.691745,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN2.1]
[2024/03/23 04:28:32.691751,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [NT LM 0.12]
[2024/03/23 04:28:32.691757,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.002]
[2024/03/23 04:28:32.691762,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.???]
[2024/03/23 04:28:32.691883,  3] source3/smbd/smb2_negprot.c:345(smbd_smb2_request_process_negprot)
  Selected protocol SMB2_FF
[2024/03/23 04:28:34.902880,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_spnego' registered
[2024/03/23 04:28:34.902955,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5' registered
[2024/03/23 04:28:34.902978,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5_sasl' registered
[2024/03/23 04:28:34.902995,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'spnego' registered
[2024/03/23 04:28:34.903013,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'schannel' registered
[2024/03/23 04:28:34.903031,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ncalrpc_as_system' registered
[2024/03/23 04:28:34.903048,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'sasl-EXTERNAL' registered
[2024/03/23 04:28:34.903066,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp' registered
[2024/03/23 04:28:34.903083,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp_resume_ccache' registered
[2024/03/23 04:28:34.903101,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_basic' registered
[2024/03/23 04:28:34.903118,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_ntlm' registered
[2024/03/23 04:28:34.903135,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_negotiate' registered
[2024/03/23 04:28:34.903159,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'krb5' registered
[2024/03/23 04:28:34.903178,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'fake_gssapi_krb5' registered
[2024/03/23 04:28:34.903674,  3] source3/smbd/smb2_negprot.c:1198(smb2_multi_protocol_reply_negprot)
  Selected protocol SMB 2.???
[2024/03/23 04:28:34.903718,  5] source3/smbd/smb2_negprot.c:1200(smb2_multi_protocol_reply_negprot)
  smb2_multi_protocol_reply_negprot: negprot index=7

@ smbd server stopped !
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "<input>", line 3, in run_smbclient
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 952, in __init__
    self.smbsock = SMB_SOCKET(self.sock)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 485, in __init__
    raise TimeoutError(
TimeoutError: The SMB handshake timed out ! (enable debug=1 for logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 10, in <module>
NameError: name 'cli' is not defined


###(003)=[failed] smbclient: connect to test share and get file

>>> LOCALPATH = pathlib.Path(get_temp_dir())
>>>
>>> with run_smbserver():
...    try:
...       cli = run_smbclient()
...       cli.use("test")
...       cli.lcd(str(LOCALPATH))
...       completions = cli.get_complete("file")
...       assert all(x in completions for x in ['fileA', 'fileB'])
...       cli.get('fileA')
...       assert (LOCALPATH / "fileA").exists()
...       assert [x.name for x in cli.lls()] == ['fileA']
...    finally:
...       cli.close()
...
@ Starting smbd server
@ Server started !
Starting control thread [tid=140005375342272]
## state=[BEGIN]
Condition [continue_smb2] not taken
Condition [send_negotiate] taken to state [SENT_NEGOTIATE]
   + Running action [on_negotiate]
SENT : DirectTCP / SMB_Header / SMBNegotiate_Request
switching from [BEGIN] to [SENT_NEGOTIATE]
## state=[SENT_NEGOTIATE]
Stopping control thread (tid=140005375342272)
@ Stopping smbd server !

Test failed. Smbd logs:
[2024/03/23 04:28:35.759666,  0] source3/smbd/server.c:1746(main)
  smbd version 4.19.5-Debian started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
[2024/03/23 04:28:35.763423,  1] source3/profile/profile.c:49(set_profile_level)
  INFO: Profiling turned OFF from pid 257638
[2024/03/23 04:28:36.202357,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2024/03/23 04:28:36.202422,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN1.0]
[2024/03/23 04:28:36.202440,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [Windows for Workgroups 3.1a]
[2024/03/23 04:28:36.202457,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LM1.2X002]
[2024/03/23 04:28:36.202471,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN2.1]
[2024/03/23 04:28:36.202484,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [NT LM 0.12]
[2024/03/23 04:28:36.202496,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.002]
[2024/03/23 04:28:36.202509,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.???]
[2024/03/23 04:28:36.202724,  3] source3/smbd/smb2_negprot.c:345(smbd_smb2_request_process_negprot)
  Selected protocol SMB2_FF
[2024/03/23 04:28:38.480846,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_spnego' registered
[2024/03/23 04:28:38.480887,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5' registered
[2024/03/23 04:28:38.480898,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5_sasl' registered
[2024/03/23 04:28:38.480907,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'spnego' registered
[2024/03/23 04:28:38.480915,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'schannel' registered
[2024/03/23 04:28:38.480923,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ncalrpc_as_system' registered
[2024/03/23 04:28:38.480931,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'sasl-EXTERNAL' registered
[2024/03/23 04:28:38.480938,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp' registered
[2024/03/23 04:28:38.480946,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp_resume_ccache' registered
[2024/03/23 04:28:38.480954,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_basic' registered
[2024/03/23 04:28:38.480962,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_ntlm' registered
[2024/03/23 04:28:38.480970,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_negotiate' registered
[2024/03/23 04:28:38.480981,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'krb5' registered
[2024/03/23 04:28:38.480989,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'fake_gssapi_krb5' registered
[2024/03/23 04:28:38.481238,  3] source3/smbd/smb2_negprot.c:1198(smb2_multi_protocol_reply_negprot)
  Selected protocol SMB 2.???
[2024/03/23 04:28:38.481258,  5] source3/smbd/smb2_negprot.c:1200(smb2_multi_protocol_reply_negprot)
  smb2_multi_protocol_reply_negprot: negprot index=7

@ smbd server stopped !
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "<input>", line 3, in run_smbclient
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 952, in __init__
    self.smbsock = SMB_SOCKET(self.sock)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 485, in __init__
    raise TimeoutError(
TimeoutError: The SMB handshake timed out ! (enable debug=1 for logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 13, in <module>
NameError: name 'cli' is not defined


###(004)=[failed] smbclient: connect to test share, cd, put file and cat it

>>> LOCALPATH = pathlib.Path(get_temp_dir())
>>> with (LOCALPATH / "fileC").open("w") as fd:
...    fd.write("Nice\nData")
...
9
>>> with run_smbserver():
...    try:
...       cli = run_smbclient()
...       cli.use("test")
...       cli.lcd(str(LOCALPATH))
...       cli.cd("sub")
...       # upload
...       cli.put('fileC')
...       # check completion
...       completions = cli.get_complete("")
...       assert all(x in completions for x in ['secret', 'fileC'])
...       # cat
...       assert cli.cat('fileC') == b'Nice\nData'
...       # check on disk
...       with (SHARE_DIR / "sub" / "fileC").open("r") as fd:
...          assert fd.read() == "Nice\nData"
...    finally:
...       cli.close()
...
@ Starting smbd server
@ Server started !
Starting control thread [tid=140005375342272]
## state=[BEGIN]
Condition [continue_smb2] not taken
Condition [send_negotiate] taken to state [SENT_NEGOTIATE]
   + Running action [on_negotiate]
SENT : DirectTCP / SMB_Header / SMBNegotiate_Request
switching from [BEGIN] to [SENT_NEGOTIATE]
## state=[SENT_NEGOTIATE]
Stopping control thread (tid=140005375342272)
@ Stopping smbd server !

Test failed. Smbd logs:
[2024/03/23 04:28:39.258004,  0] source3/smbd/server.c:1746(main)
  smbd version 4.19.5-Debian started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
[2024/03/23 04:28:39.260401,  1] source3/profile/profile.c:49(set_profile_level)
  INFO: Profiling turned OFF from pid 257683
[2024/03/23 04:28:39.721864,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2024/03/23 04:28:39.721909,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN1.0]
[2024/03/23 04:28:39.721919,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [Windows for Workgroups 3.1a]
[2024/03/23 04:28:39.721929,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LM1.2X002]
[2024/03/23 04:28:39.721936,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN2.1]
[2024/03/23 04:28:39.721942,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [NT LM 0.12]
[2024/03/23 04:28:39.721948,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.002]
[2024/03/23 04:28:39.721954,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.???]
[2024/03/23 04:28:39.722080,  3] source3/smbd/smb2_negprot.c:345(smbd_smb2_request_process_negprot)
  Selected protocol SMB2_FF
[2024/03/23 04:28:41.637629,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_spnego' registered
[2024/03/23 04:28:41.637696,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5' registered
[2024/03/23 04:28:41.637717,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5_sasl' registered
[2024/03/23 04:28:41.637733,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'spnego' registered
[2024/03/23 04:28:41.637750,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'schannel' registered
[2024/03/23 04:28:41.637765,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ncalrpc_as_system' registered
[2024/03/23 04:28:41.637781,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'sasl-EXTERNAL' registered
[2024/03/23 04:28:41.637797,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp' registered
[2024/03/23 04:28:41.637812,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp_resume_ccache' registered
[2024/03/23 04:28:41.637829,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_basic' registered
[2024/03/23 04:28:41.637845,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_ntlm' registered
[2024/03/23 04:28:41.637860,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_negotiate' registered
[2024/03/23 04:28:41.637882,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'krb5' registered
[2024/03/23 04:28:41.637898,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'fake_gssapi_krb5' registered
[2024/03/23 04:28:41.638360,  3] source3/smbd/smb2_negprot.c:1198(smb2_multi_protocol_reply_negprot)
  Selected protocol SMB 2.???
[2024/03/23 04:28:41.638398,  5] source3/smbd/smb2_negprot.c:1200(smb2_multi_protocol_reply_negprot)
  smb2_multi_protocol_reply_negprot: negprot index=7

@ smbd server stopped !
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "<input>", line 3, in run_smbclient
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 952, in __init__
    self.smbsock = SMB_SOCKET(self.sock)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 485, in __init__
    raise TimeoutError(
TimeoutError: The SMB handshake timed out ! (enable debug=1 for logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 19, in <module>
NameError: name 'cli' is not defined


###(005)=[failed] smbclient: connect to test share and recursive get

>>> LOCALPATH = pathlib.Path(get_temp_dir())
>>>
>>> with run_smbserver():
...    try:
...       cli = run_smbclient()
...       cli.use("test")
...       cli.lcd(str(LOCALPATH))
...       cli.get(".", r=True)
...       # check on disk
...    finally:
...       cli.close()
...
@ Starting smbd server
@ Server started !
Starting control thread [tid=140005375342272]
## state=[BEGIN]
Condition [continue_smb2] not taken
Condition [send_negotiate] taken to state [SENT_NEGOTIATE]
   + Running action [on_negotiate]
SENT : DirectTCP / SMB_Header / SMBNegotiate_Request
switching from [BEGIN] to [SENT_NEGOTIATE]
## state=[SENT_NEGOTIATE]
Stopping control thread (tid=140005375342272)
@ Stopping smbd server !

Test failed. Smbd logs:
[2024/03/23 04:28:42.791670,  0] source3/smbd/server.c:1746(main)
  smbd version 4.19.5-Debian started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
[2024/03/23 04:28:42.795324,  1] source3/profile/profile.c:49(set_profile_level)
  INFO: Profiling turned OFF from pid 257725
[2024/03/23 04:28:43.230046,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [PC NETWORK PROGRAM 1.0]
[2024/03/23 04:28:43.230094,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN1.0]
[2024/03/23 04:28:43.230104,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [Windows for Workgroups 3.1a]
[2024/03/23 04:28:43.230114,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LM1.2X002]
[2024/03/23 04:28:43.230121,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [LANMAN2.1]
[2024/03/23 04:28:43.230128,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [NT LM 0.12]
[2024/03/23 04:28:43.230135,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.002]
[2024/03/23 04:28:43.230142,  3] source3/smbd/smb2_negprot.c:1133(smb2_multi_protocol_reply_negprot)
  Requested protocol [SMB 2.???]
[2024/03/23 04:28:43.230284,  3] source3/smbd/smb2_negprot.c:345(smbd_smb2_request_process_negprot)
  Selected protocol SMB2_FF
[2024/03/23 04:28:45.637009,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_spnego' registered
[2024/03/23 04:28:45.637045,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5' registered
[2024/03/23 04:28:45.637055,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'gssapi_krb5_sasl' registered
[2024/03/23 04:28:45.637064,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'spnego' registered
[2024/03/23 04:28:45.637072,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'schannel' registered
[2024/03/23 04:28:45.637079,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ncalrpc_as_system' registered
[2024/03/23 04:28:45.637087,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'sasl-EXTERNAL' registered
[2024/03/23 04:28:45.637095,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp' registered
[2024/03/23 04:28:45.637103,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'ntlmssp_resume_ccache' registered
[2024/03/23 04:28:45.637111,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_basic' registered
[2024/03/23 04:28:45.637119,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_ntlm' registered
[2024/03/23 04:28:45.637127,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'http_negotiate' registered
[2024/03/23 04:28:45.637138,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'krb5' registered
[2024/03/23 04:28:45.637146,  3] auth/gensec/gensec_start.c:1083(gensec_register)
  GENSEC backend 'fake_gssapi_krb5' registered
[2024/03/23 04:28:45.637397,  3] source3/smbd/smb2_negprot.c:1198(smb2_multi_protocol_reply_negprot)
  Selected protocol SMB 2.???
[2024/03/23 04:28:45.637417,  5] source3/smbd/smb2_negprot.c:1200(smb2_multi_protocol_reply_negprot)
  smb2_multi_protocol_reply_negprot: negprot index=7

@ smbd server stopped !
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "<input>", line 3, in run_smbclient
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 952, in __init__
    self.smbsock = SMB_SOCKET(self.sock)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.ac4XGh/autopkgtest_tmp/src/scapy/layers/smbclient.py", line 485, in __init__
    raise TimeoutError(
TimeoutError: The SMB handshake timed out ! (enable debug=1 for logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 10, in <module>
NameError: name 'cli' is not defined



UTscapy ended with error code 1
```

The test definition is:

```bash
./test/run_tests -c test/configs/linux.utsc -K tcpdump \
                                            -K manufdb \
                                            -K wireshark \
                                            -K ci_only \
                                            -K vcan_socket \
                                            -K automotive_comm \
                                            -K imports \
                                            -K scanner \
                                            -K netaccess \
                                            -K root \
                                            -K tshark \
                                            -K brotli \
                                            -K zstd
```
</p>
</details>

_Originally posted by @charles2910 in https://github.com/secdev/scapy/issues/3847#issuecomment-2016344722_

**Comment by charles2910** [comment]
> Off topic note: in your command I'd replace -K root with -K needs_root. Seems to be a mistake (maybe mine?).

About the `-K root`, it is wrong indeed. I'll change to `needs_root`.

> How does one get its hands on a working, somewhat debuggable autopkgtest environment?

There seems to be some additional debugging info in autopkgtest:

```
DEBUGGING OPTIONS
       --debug|-d
              Include additional debugging information in the trace log.  Each additional -d increases
              the debugging level; the current maximum is -ddd.  If you like to see what's  going  on,
              -d or -dd is recommended.

       --shell-fail|-s
              Run  an  interactive  shell in the testbed after a failed build, test, or dependency in‐
              stallation.

       --shell
              Run an interactive shell in the testbed after every test.
```

I'll try to get some logs for you. If you want to try yourself, a Debian vm or machine can do it, then you would need the to get the buildinfo so auto autopkgtest can build and run the tests for you - not that friendly for someone who isn't acquainted with debian packaging :-(

**Comment by gpotter2** [comment]
> Since you guys are a very nice - VERY NICE, really! - upstream

Thanks :)

>  If you want to try yourself, a Debian vm or machine can do it, then you would need the to get the buildinfo so auto autopkgtest can build and run the tests for you

It'll probably end up like this. It's honnestly not that easy to debug Scapy tests. I'll try and see if I can get autopkgtest running.

On an unrelated note and just to be sure, could you clarify a bit which Scapy version you're using? If debian's still using what we tagged 2.5.0 (with patches), the `smbclientserver.uts` tests shouldn't be included.

> On a somewhat related note in terms of packaging the "samba-client", "samba" and "python3-tkinter"

tkinter shouldn't be necessary, see https://github.com/secdev/scapy/pull/4258.

**Comment by gpotter2** [comment]
At quick glance, https://salsa.debian.org/pkg-security-team/scapy/-/merge_requests/3 is missing the patch from https://github.com/secdev/scapy/pull/4024 to support cryptography 42.0.

**Comment by charles2910** [comment]
@gpotter2 

Oh, that explains a lot. I saw only the patch from the MR didn't solve things, but I wasn't smart enough to find the correct additional commit.

That's why I was packaging the HEAD of the master branch to build correctly with cryptography 42.

I've just uploaded `scapy_2.5.0+git20240324.2b58b51+dfsg-1`, so maybe in a few ours you can easily test it with autopkgtest. You'll need to add the source feed in `/etc/apt/sources.list` and run `autopkgtest scapy -- null`, you will need to install autopkgtest and scapy in the vm. The `/etc/apt/sources.list` should look like:

```
deb https://deb.debian.org/debian/ unstable main
deb-src https://deb.debian.org/debian/ unstable main
```

You might find `file:///usr/share/doc/autopkgtest/README.running-tests.html` and `man autopkgtest` a nice source of useful info.

**Comment by charles2910** [comment]
I have no idea how or why, but the test decided to pass today! I think it might be because some other package got updated between yesterday and today, but I'm not sure. (so I think I'm just gonna close this issue, do you agree?)

Oh, btw tests for this new version are passing in [amd64](https://ci.debian.net/packages/s/scapy/testing/amd64/44326189/), [arm64](https://ci.debian.net/packages/s/scapy/testing/arm64/44326216/) and [ppc64el](https://ci.debian.net/packages/s/scapy/testing/ppc64el/44326381/)! The other archs are still waiting to run the tests.

**Comment by charles2910** [comment]
Closing the ticket, thanks for all the help!

P.S.: tests are also passing on all Debian archs (amd64, armel, armhf, s390x, ppc64el)!

**Comment by gpotter2** [comment]
That's good to hear !

Hopefully that was actually as simple as a dependency trick, and not some mysterious issue that will come back later :)
