### ISSUE TITLE
The "OSS-Fuzz Findings" test seems to fail on 32-bit machines

### ISSUE THREAD

**Issue by evverx** [secdev/scapy#4527]
### Brief description

https://download.copr.fedorainfracloud.org/results/packit/evverx-scapy-2/fedora-40-i386/07990313-scapy/builder-live.log.gz
```python
###(167)=[failed] OSS-Fuzz Findings

>>> from io import BytesIO
>>> file = BytesIO(b"\n\r\r\n\x1c\x00\x00\x00M<+\x1a\x01\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x1c\x00\x00\x00\x01\x00\x00\x00\x14\x00\x00\x00\xe4\x00\x00\x00\x00\x00\x04\x00\x14\x00\x00\x00\x01\x00\x00\x00(\x00\x00\x00\xe4\x00\x00\x00\x00\x00\x04\x00\x02\x00\t\x00b'ens16\xb0'\x00\x00\x00\x00\x00\x00\x00(\x00\x00\x00\x06\x00\x00\x004\x00\x00\x00\x01\x00\x00\x00}\x17\x06\x00\xb5t\x1d\x85\x14\x00\x00\x00\x14\x00\x00\x00E\x00\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x014\x00\x00\x00")
>>> rdpcap(file)
<No name: TCP:0 UDP:0 ICMP:0 Other:1>
>>> 
>>> file = BytesIO(b'\n\r\r\n\xff\xfe\xfe\xffM<+\x1a')
>>> try:
...     rdpcap(file)
... except Scapy_Exception:
...     pass
... 
PcapNg: Could not read major value
>>> file = BytesIO(b"\n\r\r\n\x00\x00\x008\x1a+<M\x00\x01\x00\x00\xef\xff\xff\x81\x01\x00\x00\x01\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x009\x00\x00\x00\x01\x00\x00\x000\x00e\x00\x00\x00\x00\x00\x00\x00\x008\x00\x00\x00\x06\x00\x00\x00d\x00\x00\x00\x00'\x00\x00\x00\x01\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x80\x01\x00\x00\x000\x00\x00\x00\x01\x00\x00\x008\x00\x00\n\x0c\x00A\x05\xc0\x01\x00\x00\x00\x00\x00d\x00\x00\x00\x00\x00\x00\x00\x00\x000\x00\x00\x00\x01\x00\x00\x008\x00\x00\n\x0c\x00A\x05\xc0\x83\x00\x00\x043\x01\x00\x00\x00\x00\x00d\x00\x00\x00\x00d")
>>> l = rdpcap(file)
PcapNg: invalid option length 12 for end-of-option
PcapNg: EPB invalid proc index(expected 4 bytes, got 0) !
>>> 
>>> file = BytesIO(b"M<\xb2\xa1 \x00\xff\xf9\xff\x00\x00\xff\xff\xff\xa1\xb2<M\x01\x00\x00\x00\x00\x00\x00\x17\xca\xca\xca\xca\xca\xca\xca\xca\xca\xca\r\x80\x01[\x00\x01noenum\x00\x00\x00\x00\x00\x06value\x01\x00\x00\x00\x00\x00\x00\x01\x85\xff\xff\x00\x00\x94\xc3\x000\x00\x08\xa0\xf30\x800\x000\x00")
>>> l = rdpcap(file)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/builddir/build/BUILD/scapy-2.5.0/scapy/utils.py", line 1346, in rdpcap
    return fdesc.read_all(count=count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/scapy-2.5.0/scapy/utils.py", line 1627, in read_all
    res = self._read_all(count)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/scapy-2.5.0/scapy/utils.py", line 1535, in _read_all
    p = self.read_packet()  # type: Packet
        ^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/scapy-2.5.0/scapy/utils.py", line 1591, in read_packet
    rp = super(PcapReader, self)._read_packet(size=size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/scapy-2.5.0/scapy/utils.py", line 1503, in _read_packet
    return (self.f.read(caplen)[:size],
            ^^^^^^^^^^^^^^^^^^^
OverflowError: cannot fit 'int' into an index-sized integer
```

### Scapy version

1935723c

### Python version

3.12.1

### Operating system

Fedora 40

### How to reproduce

It can be reproduced by running the test on an i386 machine.

**Comment by guedou** [comment]
Thanks for the report. I was able to easily replicate it thanks to Docker i36 images (such as https://hub.docker.com/layers/i386/python/3.10-bookworm/images/sha256-33e665055788054cb3778709851f2a939bcc4bc36b4640506806556d648fecca?context=explore)
