### ISSUE TITLE
Backtrace loading manufdb

### ISSUE THREAD

**Issue by rfrohl** [secdev/scapy#4555]
### Brief description

The embedded manufdb fails to load with python3.11.

### Scapy version

2.6.0

### Python version

3.11

### Operating system

openSUSE Tumbleweed

### How to reproduce

$ scapy

### Actual result

```
Traceback (most recent call last):
  File "/usr/bin/scapy", line 33, in <module>
    sys.exit(load_entry_point('scapy==2024.9.28', 'console_scripts', 'scapy')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/main.py", line 767, in interact
    SESSION = init_session(session_name, mydict=mydict, ret=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/main.py", line 542, in init_session
    scapy_builtins = _scapy_builtins()
                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/main.py", line 387, in _scapy_builtins
    for k, v in importlib.import_module(".all", "scapy").__dict__.copy().items()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/scapy/all.py", line 13, in <module>
    from scapy.data import *
  File "/usr/lib/python3.11/site-packages/scapy/data.py", line 608, in <module>
    MANUFDB = load_manuf(
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/data.py", line 327, in load
    content = func(filename)
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/data.py", line 572, in load_manuf
    from scapy.libs.manuf import DATA
  File "/usr/lib/python3.11/site-packages/scapy/libs/manuf.py", line 62, in <module>
    DATA = _d("""
           ^^^^^^
  File "/usr/lib/python3.11/site-packages/scapy/libs/manuf.py", line 58, in _d
    b85decode(x.replace("\n", ""))
  File "/usr/lib64/python3.11/base64.py", line 509, in b85decode
    raise ValueError('base85 overflow in hunk starting at byte %d'
ValueError: base85 overflow in hunk starting at byte 3715
```

**Comment by guedou** [comment]
Thanks for sharing. How did you install Scapy?

**Comment by gpotter2** [comment]
Honnestly this bug is a bit crazy. Why would the same base85 fail to be decoded in your setup, yet succeed on other setups?

Sounds to me like either some weird bug in your Python flavor, or maybe in the way the file was encoded when you downloaded it.. something crazy like that

**Comment by evverx** [comment]
I launched an openSUSE container, installed the scapy package and that weird backtrace popped up. I'm not sure how exactly it was packaged there but `manuf.py` is different from what is in the scapy repository or the scapy tarball:
```sh
# cmp /tarball/scapy-2.6.0/scapy/libs/manuf.py /scapy/scapy/libs/manuf.py
# cmp /scapy/scapy/libs/manuf.py /usr/lib/python3.11/site-packages/scapy/libs/manuf.py
/scapy/scapy/libs/manuf.py /usr/lib/python3.11/site-packages/scapy/libs/manuf.py differ: char 5609, line 108
```

**Comment by evverx** [comment]
I'm 99% it's a bug in the openSUSE package. The following part of the spec file
```sh
%install
%python3_install
# Fix non-executable-script rpmlint issue:
find %{buildroot}%{python3_sitelib} -name "*.py" -exec sed -i "/#!/d" {} \;
%fdupes %{buildroot}%{python3_sitelib}
```
seems to be the culprit in the sense it's responsible for dropping a bunch of lines from the original manuf.py file.

**Comment by evverx** [comment]
@rfrohl it's unrelated to this issue but I took a closer look at https://build.opensuse.org/projects/security/packages/scapy/files/scapy.spec and it seems the test are skipped. I'm not sure if it helps but all the moving parts needed to run them on Fedora with no tox can be found at https://github.com/secdev/scapy/blob/master/.packit.yml. It adds a bunch of build dependencies to the Fedora spec file and then runs
```sh
OPENSSL_CONF=$(python3 ./.config/ci/openssl.py) ./test/run_tests -c test/configs/linux.utsc -K ci_only -K scanner
```
Depending on what the build environment looks like `-K netaccess` should probably be added to skip those tests as well.

**Comment by evverx** [comment]
>  they have no network access

I think `-K netaccess` combined with avoiding tox should work.

(I removed `-K netaccess` from the packit config because I set `enable_net` to `true` there at some point but it's off by default when actual Fedora packages are built as far as I can remember)
