### ISSUE TITLE
scapy requires writeable filesystem

### ISSUE THREAD

**Issue by prauscher** [secdev/scapy#4575]
### Brief description

Imagine using a docker container with read only root, where scapy was installed in the Dockerfile. Whenever importing `scapy` (or any submodule) this fails with PermissionDenied, as scapy tries to create the Folder `.config` in `XDG_CONFIG_HOME`:

```
>>> from scapy.layers.dns import DNS
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    from scapy.layers.dns import DNS
  File "/tmp/venv/lib/python3.13/site-packages/scapy/layers/dns.py", line 24, in <module>
    from scapy.arch import (
    ...<3 lines>...
    )
  File "/tmp/venv/lib/python3.13/site-packages/scapy/arch/__init__.py", line 24, in <module>
    from scapy.data import (
    ...<2 lines>...
    )
  File "/tmp/venv/lib/python3.13/site-packages/scapy/data.py", line 415, in <module>
    @scapy_data_cache("ethertypes")
  File "/tmp/venv/lib/python3.13/site-packages/scapy/data.py", line 301, in scapy_data_cache
    from scapy.main import SCAPY_CACHE_FOLDER
  File "/tmp/venv/lib/python3.13/site-packages/scapy/main.py", line 164, in <module>
    SCAPY_CONFIG_FOLDER = _probe_config_folder("scapy")
  File "/tmp/venv/lib/python3.13/site-packages/scapy/main.py", line 82, in _probe_config_folder
    return _probe_xdg_folder(
        "XDG_CONFIG_HOME",
        os.path.join(os.path.expanduser("~"), ".config"),
        *cf
    )
  File "/tmp/venv/lib/python3.13/site-packages/scapy/main.py", line 76, in _probe_xdg_folder
    path.mkdir(mode=0o700)
  File "/usr/local/lib/python3.13/pathlib/_local.py", line 722, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```

### Scapy version

2.6.0

### Python version

3.13

### Operating system

Debian

### Additional environment information

Running scapy in a read-only-root Docker container (or anywhere where XDG_CONFIG_HOME/.config/scapy does not exist and is not writeable)

### How to reproduce

`import scapy`

### Actual result

Stacktrace (see above)

### Expected result

scapy should be able to run e.g. by disabling the cache (or using an in-memory-cache only)

**Comment by prauscher** [comment]
Ok, I need to investigate this further: Altrough I received this error recently, in similar environments the error did not occur and judging from the code it should not occur.

**Comment by prauscher** [comment]
Sorry, this seems to be a duplicate of #4571, so it will be fixed with the next release.
