### ISSUE TITLE
dnet module error. can't run the package on mac

### ISSUE THREAD

**Issue by chetanpm** [secdev/scapy#467]
I am on macOS 10.12.2, python 2.7.13. 
Installing via sudo pip install scapy
Installation succeeds but when I run it:

`Chetans-MacBook-Pro:~ chetanpm$ sudo scapy
Password:
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
ERROR: Unable to import dnet module: No module named dnet
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 25, in <module>
    interact()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/main.py", line 278, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/all.py", line 28, in <module>
    from route6 import *
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/route6.py", line 271, in <module>
    conf.route6 = Route6()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/route6.py", line 29, in __init__
    self.resync()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/route6.py", line 42, in resync
    self.routes = read_routes6()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/unix.py", line 150, in read_routes6
    lifaddr = in6_getifaddr()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/unix.py", line 126, in in6_getifaddr
    i = dnet.intf()
NameError: global name 'dnet' is not defined`

IT fails to initiate, I need it as dependency for [pyrit](https://github.com/JPaulMora/Pyrit). I could not find a way to make it work.

**Comment by guedou** [comment]
You either need to follow the [instructions](http://scapy.readthedocs.io/en/latest/installation.html#mac-os-x) to install mandatory dependencies, or use Scapy directly from github.

macOS is natively supported since a few months. This feature will be in the next release. 

See this [asciicinema video](https://asciinema.org/a/94787) for an example.

**Comment by chetanpm** [comment]
The [Instructions](http://scapy.readthedocs.io/en/latest/installation.html#mac-os-x) didn't work for me. The github version did install and initiated with no errors though. Thank you :)
