### ISSUE TITLE
PicklingError with scapy 2.3.3

### ISSUE THREAD

**Issue by vapniks** [secdev/scapy#470]
```
me@mycomputer:tmp/> scapy -s scapysession1                                                                                  [21:25:30 17-01-15]!10077
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: New session [scapysession1]
Welcome to Scapy (2.3.3)
>>> ip=IP(dst="192.168.0.10")
>>> ip
<IP  dst=192.168.0.10 |>
>>> 
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 25, in <module>
    interact()
  File "/usr/local/lib/python2.7/dist-packages/scapy/main.py", line 385, in interact
    save_session(conf.session, session)
  File "/usr/local/lib/python2.7/dist-packages/scapy/main.py", line 146, in save_session
    cPickle.dump(to_be_saved, f, pickleProto)
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

```

**Comment by gpotter2** [comment]
So that's a cPickle bug: parsing functions crash.
For instance, this works:
```
PS C:\Users\gpotter\Desktop> scapy -s scapysession1
INFO: New session [scapysession1]
Welcome to Scapy (2.3.3.dev146)
>>> IP()
<IP  |>
>>>
[Closed]
```

But using this:
```
>>> def test():
...     return "true"
...
```
or this:
```
ip = IP()
```
won't.

@p-l- There is a really easy way of fixing this: getting rid of cPickle, which is now a bit outdated, to go on with https://pypi.python.org/pypi/dill. But this one is not installed by default, so we would have to disable the function if it's not installed....

**Comment by vapniks** [comment]
Great thanks.

**Comment by gpotter2** [comment]
Fixes in https://github.com/secdev/scapy/issues/470
