### ISSUE TITLE
starting scapy under windows (cygwin) crashes but import no issue

### ISSUE THREAD

**Issue by pinggit** [secdev/scapy#527]
```
pings@PINGS-X240:~/bin$ scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
Traceback (most recent call last):
  File "/usr/bin/scapy", line 25, in <module>
    interact()
  File "/usr/lib/python2.7/site-packages/scapy/main.py", line 300, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "/usr/lib/python2.7/site-packages/scapy/all.py", line 25, in <module>
    from scapy.route import *
  File "/usr/lib/python2.7/site-packages/scapy/route.py", line 163, in <module>
    conf.route=Route()
  File "/usr/lib/python2.7/site-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/usr/lib/python2.7/site-packages/scapy/route.py", line 29, in resync
    from scapy.arch import read_routes
ImportError: cannot import name read_routes

pings@PINGS-X240:~/bin$

In [48]: import scapy
In [49]:
```

I think I saw some posts about the exact same errors, but not seeing any solutions.
any help?

**Comment by gpotter2** [comment]
Cygwin is not currently supported by scapy as windows is fully supported

**Comment by gpotter2** [comment]
@p-l- Could you close this please ? This is a `wontfix` issue
