### ISSUE TITLE
Fuzzing random crash

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#529]
Performing
`>>> str(fuzz(IP()/ICMP()))`
randomly crash:

```
>>> str(fuzz(IP()/ICMP()))
'U\x83\x00\x1c\x1fb\xe0\x00\xa3\x01\xc7\xda\xc0\xa8\x00w\x7f\x00\x00\x01\xa5\xc1\xb9\xfcn\xcf1r'
>>> str(fuzz(IP()/ICMP()))
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 280, in __str__
    return self.build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 357, in build
    p = self.do_build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 347, in do_build
    pay = self.do_build_payload()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 339, in do_build_payload
    return self.payload.do_build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 344, in do_build
    pkt = self.self_build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 335, in self_build
    p = f.addfield(self, p, val)
  File "C:\Python27\lib\site-packages\scapy\fields.py", line 149, in addfield
    return self.fld.addfield(pkt,s,val)
  File "C:\Python27\lib\site-packages\scapy\fields.py", line 74, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
error: 'H' format requires 0 <= number <= 65535
```

@guedou What you used in https://github.com/secdev/scapy/pull/522

**Comment by guedou** [comment]
That's a _known problem_ with `fuzz()`. As far as I remember, `fuzz()` feeds invalid (i.e out of bounds) values. I did not try to fix it.
