### ISSUE TITLE
NameError: global name 'PcapReader' is not defined

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#652]
when send a captured packet in another method,
have another error

```
>>> #for sniffed_packet in sniff(offline=r'C:\Users\hello\Downloads\dhcp.pcap', prn=customAction):
... for sniffed_packet in sniff(offline=r'C:\Users\hello\Downloads\dhcp.pcap'):
...     if count == 0:
...         responsepkt = sr1(sniffed_packet)
...     count = count + 1
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 182, in sniff
    s = PcapReader(offline)
NameError: global name 'PcapReader' is not defined
```

**Comment by guedou** [comment]
Closed at it is likely related to #651 
You can reopen it if solving #651 does not also solve this one.
