### ISSUE TITLE
IndexError: Layer [Raw] not found

### ISSUE THREAD

**Issue by usama7628674** [secdev/scapy#686]
File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 817, in getitem
raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Raw] not found

Any help would be greatly appreciated

**Comment by gpotter2** [comment]
Hello, could you please give us your OS version, and how to reproduce ?

**Comment by usama7628674** [comment]
I have parrot os 3.6 version.the issue comes when I use WiFi-Pumpkin.
the complete details of the error is following:-


Traceback (most recent call last):
File "/root/Desktop/WiFi-Pumpkin-master/core/servers/proxy/tcp/intercept.py", line 43, in run
self.main()
File "/root/Desktop/WiFi-Pumpkin-master/core/servers/proxy/tcp/intercept.py", line 94, in main
self.plugins[Active].filterPackets(pkt)
File "/root/Desktop/WiFi-Pumpkin-master/plugins/analyzers/httpCap.py", line 87, in filterPackets
self.load = pkt[Raw].load
File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 817, in getitem
raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Raw] not found



As you can see the problem in scapy layer Raw.
Help me in resolving this error.

**Comment by mtury** [comment]
WiFi-Pumpkin assumes you should get a Raw layer somewhere, although in practice you don't. It seems the problem comes from the WiFi-Pumpkin code itself (or maybe the way you execute it).

**Comment by p-l-** [comment]
Not a bug in Scapy.
