### ISSUE TITLE
Facing problem while setting  IPOption in scapy with python3.5  

### ISSUE THREAD

**Issue by Murlidhara** [secdev/scapy#748]
code

#!/usr/bin/python3.5
from scapy.all import *
a=IP(src='50.50.50.2',dst='40.40.40.2',options=IPOption('\x83\x07\x04\x00\x00\x00\x00\x00'))
send(a,iface='eth1')

Getting the error

WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
Traceback (most recent call last):
  File "tool.py", line 3, in <module>
    a=IP(src='50.50.50.2',dst='40.40.40.2',options=IPOption('\x83\x07\x04\x00\x00\x00\x00\x00'))
  File "/usr/local/lib/python3.5/dist-packages/scapy/base_classes.py", line 199, in __call__
    i.__init__(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 87, in __init__
    self.dissect(_pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 623, in dissect
    s = self.do_dissect(s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 591, in do_dissect
    s,fval = f.getfield(self, s)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 696, in getfield
    bs = struct.unpack('!%dB' % nb_bytes, w)
TypeError: a bytes-like object is required, not 'str'

from scapy prompt

root@esst-srv3:/tmp/scapy# scapy
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
INFO: Please, report issues to https://github.com/phaethon/scapy
INFO: Can't import python cryptography lib. Won't be able to decrypt WEP.
INFO: Can't import python cryptography lib. Disabled IPsec encryption/authentication.
INFO: Can't import python cryptography. Disabled certificate manipulation tools
WARNING: IPython not available. Using standard Python shell instead.
Welcome to Scapy (3.0.0)
>>> a=IP(src="30.1.1.2",dst="20.1.1.2",options=IPOption('\x83\x07\x04\x00\x00\x00\x00\x00'),)
Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/scapy/base_classes.py", line 197, in __call__
    cls =  cls.dispatch_hook(*args, **kargs)
  File "/usr/local/lib/python3.4/dist-packages/scapy/layers/inet.py", line 161, in dispatch_hook
    opt = pkt[0] & 0x1f
TypeError: unsupported operand type(s) for &: 'str' and 'int'

Please help me in resolving this issue

**Comment by p-l-** [comment]
Scapy does not support, for now, Python 3.
