### ISSUE TITLE
Error during installation.

### ISSUE THREAD

**Issue by NileshPS** [secdev/scapy#752]
```
Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 199kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ag2uz8ex/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ag2uz8ex/scapy/

```

**Comment by p-l-** [comment]
Hi,

Which version of Python are you using?

**Comment by NileshPS** [comment]
3.5

**Comment by NileshPS** [comment]
I cloned the latest version from github and it installed without any problems. The issue is present only when installing through pip.

**Comment by gpotter2** [comment]
We do not support python 3 yet, but we are working on it.

Please use python 2.7 for now.
