### ISSUE TITLE
how to use this skill to scan port 53

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#765]
i subscribe scapy.ml-subscribe@secdev.org <scapy.ml-subscribe@secdev.org>
but no email confirm today

i would like to ask
how to find my current vlan id with scapy as tcpdump do not have things return in vmware virtual machine in window 10 when test the physical connected switch
sudo tcpdump -nn -v -i eth0 -s 1500 -c 1 'ether[20:2] == 0x2000' 

when i try to vlan hopping to scan network port 53, it running a long time,
can't it vlan hopping back?
```
ans,unans = sr(Ether()/Dot1Q(vlan=50)/Dot1Q(vlan=100)/IP(dst="192.168.100.200/24")/TCP(dport=[53,80,443,8080]))
for s,r in ans:
    print r.sprintf("%-15s,IP.src% %4s,TCP.sport% %2s,TCP.flags%")
```

```
>>> sendp(Ether()/Dot1Q(vlan=50)/Dot1Q(vlan=100)/IP(dst="192.168.100.200")/ICMP())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 279, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 247, in __gen_send
    s.send(p)
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 260, in send
    sx = str(x)
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 277, in __str__
    return self.build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 354, in build
    p = self.do_build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 341, in do_build
    pkt = self.self_build()
  File "C:\Python27\lib\site-packages\scapy\packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "C:\Python27\lib\site-packages\scapy\fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 105, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 97, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 45, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 200, in l2_register_l3
    return conf.neighbor.resolve(l2, l3.payload)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 45, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 200, in l2_register_l3
    return conf.neighbor.resolve(l2, l3.payload)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 45, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "C:\Python27\lib\site-packages\scapy\layers\inet.py", line 782, in inet_register_l3
    return getmacbyip(l3.dst)
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 80, in getmacbyip
    nofilter=1)
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 395, in srp1
    a,b=srp(*args,**kargs)
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 378, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 89, in sndrcv
    stoptime = time.time()+timeout
NameError: global name 'time' is not defined

```

**Comment by mike-savory** [comment]
The final error in your traceback shows as being a windows compatibility issue.

File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 89, in sndrcv
    stoptime = time.time()+timeout
NameError: global name 'time' is not defined

Try including the line "import time" before running the commands above.

**Comment by hoyeunglee** [comment]
it succeed to send , but how to make it reply back with vlan hopping?

```
>>> ans,unans = sr(Ether()/Dot1Q(vlan=805)/Dot1Q(vlan=4)/IP(dst="192.168.4.192/24")/TCP(dport=[53]))
Begin emission:
Finished to send 256 packets.
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

>>> sendp(Ether()/Dot1Q(vlan=100)/Dot1Q(vlan=50)/IP(dst="192.168.50.100/24")/ICMP())
................................................................................................................................................................................................................................................................
Sent 256 packets.
```

**Comment by hoyeunglee** [comment]
My src ip is public IP address and the private IP address can send to this public ip theoretically
But why I can not receive this packet?

I am thinking to edit src ip in icmp but it seems no need, then where do private IP address send reply to?

**Comment by p-l-** [comment]
@hoyeunglee I think you question is a network question, not a Scapy one, so maybe you'll have more luck on a StackExchange web site (you may want to try [Information Security](https://security.stackexchange.com/) or [Network Engineering](https://networkengineering.stackexchange.com/)).

**Comment by mike-savory** [comment]
where do private IP address send reply to?
Wherever their route table says !
