### ISSUE TITLE
Is it possible to apply a BPF filter to packets already sniffed?

### ISSUE THREAD

**Issue by boeing888** [secdev/scapy#818]
I'm working to write a program that need to re-filter the packets sniffed by sniff() using BPF syntax. My purpose is pretty simple:if a packet match the BPF syntax,return True,else return False.I cannot just use sniff(filter='xxxx') in the first sniff because I need all the traffic pass through the network interface.And I need to do this in memory for the hard disk is too slow.  So, here's my solution:
```
import io
from scapy.all import *

pkts=sniff(count=10)
for pkt in pkts:
    buf=io.BytesIO()
    PcapWriter(buf).write(pkt)
    buf.seek(0)
    cap=sniff(offline=buf,filter='icmp')
    if len(cap)>0:
        print 'match!'
```
But it seems not work. Here's the error message:
```
Traceback (most recent call last):
  File "scapy/sendrecv.py", line 704, in sniff
    ins = _select(sniff_sockets)
  File "scapy/sendrecv.py", line 692, in _select
    return select(sockets, [], [], remain)[0]
  File "scapy/utils.py", line 838, in fileno
    return self.f.fileno()
UnsupportedOperation: fileno

```
So does sniff() support sniff from BytesIO?Or is there a better way to filter a packet using BPF syntax?
Any hint is appreciated, thanks!

**Comment by p-l-** [comment]
You can just use `sniff(offline=pkts, filter='icmp')`. Would that work for you?

**Comment by p-l-** [comment]
BTW I've updated your issue title. If you do not agree with that, please let me know.

**Comment by boeing888** [comment]
Thanks for your reply:) But I want to keep all the network traffic captured, not only capture the icmp packet.
For example, I sniffed 10 packets from interface wlan0, and I want to keep these packets and pick out which packet match the BPF syntax that I'll input later.Just like wireshark, if you input different BPF rules, packets that matched will be picked out, but in fact all the packets are kept.
I've been stuck for two days, could you give me some help? Thank you !

**Comment by p-l-** [comment]
OK, maybe I've not been clear enough. You can first sniff the packets, and the apply a BPF filter with another `sniff()` call:
```Python
pkts = sniff(count=10)
pkts_icmp = sniff(offline=pkts, filter="icmp")
```
Does that work for you?

**Comment by boeing888** [comment]
Eh..Maybe it's my fault, I didn't make it clear. I'm working on a program and I've listed all the packets in a table, just like the packet list in wireshark. After apply BPF filter, the packets in  the list that don't match should be hidden.If I re-list all the packets that have been filtered, It would be quite slow and takes too much time to repaint the UI, and if i know exactly which packet show be hidden(the index), I can use things like   list[i].hidden()   to hide them, It's a much fast way.

**Comment by p-l-** [comment]
You can also use a single packet as input for `sniff()`. In that case, you can do:

```Python
pkts = sniff(count=10)
for pkt in pkts:
    if sniff(offline=pkt, filter='icmp'):
        print 'match!'
```

But this will fork a `tcpdump` process for each packet.

As a side note, if your test is that simple, you can also use a Scapy test instead (it's not strictly equivalent though):
```Python
pkts = sniff(count=10)
for pkt in pkts:
    if ICMP in pkt:
        print 'match!'
```

**Comment by boeing888** [comment]
Oh, I know what goes wrong. I've tried
```
pkts=sniff(count=10)
p=sniff(offline=pkts[0])
```
several times without a 'filter' parameter and it will raise an error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/sendrecv.py", line 655, in sniff
    )] = offline
  File "scapy/utils.py", line 718, in __call__
    filename, fdesc, magic = cls.open(filename)
  File "scapy/utils.py", line 752, in open
    magic = fdesc.read(4)
  File "scapy/packet.py", line 232, in __getattr__
    return self.payload.__getattr__(attr)
  File "scapy/packet.py", line 232, in __getattr__
    return self.payload.__getattr__(attr)
  File "scapy/packet.py", line 232, in __getattr__
    return self.payload.__getattr__(attr)
  File "scapy/packet.py", line 232, in __getattr__
    return self.payload.__getattr__(attr)
  File "scapy/packet.py", line 232, in __getattr__
    return self.payload.__getattr__(attr)
  File "scapy/packet.py", line 230, in __getattr__
    fld, v = self.getfield_and_val(attr)
  File "scapy/packet.py", line 1251, in getfield_and_val
    raise AttributeError(attr)
AttributeError: read
```
So I thought this way won't work and struggled for one day...And with that parameter, everything goes right. Maybe it's a bug?

Finally, thank you very much:)

**Comment by boeing888** [comment]
BTW, when I'm using 
```
sudo ./run_scapy3
```
an error raised.
```
>>> pkts=sniff(count=10)
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/zhang/Source Code/scapy/scapy/sendrecv.py", line 671, in sniff
    *arg, **karg)] = iface
  File "/home/zhang/Source Code/scapy/scapy/arch/linux.py", line 576, in __init__
    set_promisc(self.ins, i)
  File "/home/zhang/Source Code/scapy/scapy/arch/linux.py", line 166, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, "")
struct.error: argument for 's' must be a bytes object

```
Maybe it's a compatibility issue?

**Comment by p-l-** [comment]
Which version of Scapy are you using?

**Comment by boeing888** [comment]
I cloned it from Github today using```git clone https://github.com/secdev/scapy```
I think it's the latest version?

**Comment by p-l-** [comment]
My mistake!

**Comment by p-l-** [comment]
Scapy support is very experimental (but we're working on it!), please consider using Python 2 for now.

**Comment by p-l-** [comment]
I've cleaned the answers to make it easier to find the solution. Is it OK for you to close this issue?

**Comment by boeing888** [comment]
Of course you can! You're coooool bro, maybe one day I'll become a developer like you ; )

**Comment by p-l-** [comment]
Of course you will! Thanks for your interest in Scapy, let us know if we can help you :-)

**Comment by p-l-** [comment]
@boeing888 since #820 has been merged, the bug you reported should be fixed now. Thanks!

**Comment by boeing888** [comment]
@p-l- Ah, thank you! I'm sorry to bother you again but another error raised when I'm running scapy using python3:
```
zhang@XPS-13-9343:~/Source Code/scapy$ sudo ./run_scapy3 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhang/Source Code/scapy/scapy/__init__.py", line 93, in <module>
    interact()
  File "/home/zhang/Source Code/scapy/scapy/main.py", line 412, in interact
    init_session(session_name, mydict)
  File "/home/zhang/Source Code/scapy/scapy/main.py", line 285, in init_session
    scapy_builtins = {k: v for k, v in six.iteritems(importlib.import_module(".all", "scapy").__dict__) if _validate_local(k)}
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/zhang/Source Code/scapy/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/home/zhang/Source Code/scapy/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/home/zhang/Source Code/scapy/scapy/route6.py", line 34, in __init__
    self.resync()
  File "/home/zhang/Source Code/scapy/scapy/route6.py", line 47, in resync
    self.routes = read_routes6()
  File "/home/zhang/Source Code/scapy/scapy/arch/linux.py", line 328, in read_routes6
    lifaddr = in6_getifaddr() 
  File "/home/zhang/Source Code/scapy/scapy/arch/linux.py", line 303, in in6_getifaddr
    addr = scapy.utils6.in6_ptop(b':'.join(addr))
  File "/home/zhang/Source Code/scapy/scapy/utils6.py", line 613, in in6_ptop
    return inet_ntop(socket.AF_INET6, inet_pton(socket.AF_INET6, str))
  File "/home/zhang/Source Code/scapy/scapy/pton_ntop.py", line 88, in inet_pton
    return socket.inet_pton(af, addr)
OSError: illegal IP address string passed to inet_pton

```
However, everything goes right with python2:```sudo ./run_scapy``` .
I re-download scapy today and it's the latest version.
