### ISSUE TITLE
IPv6 requires elevated privileges ...

### ISSUE THREAD

**Issue by klement** [secdev/scapy#839]
Hi, using scapy 2.3.3, I'm facing the following issue:

```
>>> x = Ether()/IPv6()
>>> x = x.__class__(str(x))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 261, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 319, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 308, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 299, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 70, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 94, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 88, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/l2.py", line 38, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 468, in <lambda>
    conf.neighbor.register_l3(Ether, IPv6, lambda l2,l3: getmacbyip6(l3.dst))
  File "/usr/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 109, in getmacbyip6
    res = neighsol(ip6, a, iff, chainCC=chainCC)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 79, in neighsol
    chainCC=chainCC)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 375, in srp1
    a,b=srp(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 357, in srp
    s = conf.L2socket(iface=iface, filter=filter, nofilter=nofilter, type=type)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 406, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 1] Operation not permitted
```

If I specify the MAC addresses for Ether layer, everything works just fine:

```
>>> y = Ether(src='52:54:00:fd:3a:b9', dst='52:54:00:fd:3a:b9')/IPv6()
>>> y = y.__class__(str(y))
```

It also works just fine (with empty Ether layer) with IPv4:

```
>>> z = Ether()/IP()
>>> z = z.__class__(str(z))
```

I don't think that the first code snipper should raise the exception.

**Comment by guedou** [comment]
This is fixed on the master branch on github:

```
>>> Ether(str(Ether()/IPv6()))
<Ether  dst=ff:ff:ff:ff:ff:ff src=00:00:00:00:00:00 type=IPv6 |<IPv6  version=6 tc=0 fl=0 plen=0 nh=No Next Header hlim=64 src=::1 dst=::1 |>>
```

Please reopen the issue if you still have the issue.
