### ISSUE TITLE
 Scapy sniff returns an error with pypy

### ISSUE THREAD

**Issue by blizzardplus** [secdev/scapy#842]
I am running something like this
```
from scapy.all import *
myFilter = "host 1.2.3.4 and port 54321"
packets = sniff(filter=myFilter)
```
And I get the following error:

```
 Traceback (most recent call last):
   File "/usr/pypy/lib-python/2.7/threading.py", line 797, in __bootstrap_inner
     self.run()
   File "/usr/pypy/lib-python/2.7/threading.py", line 750, in run
     self.__target(*self.__args, **self.__kwargs)
   File "test.py", line 85, in sniffTask
     packetList = sniff(filter=dispFilter, store=0, timeout=sniffTimeout, stop_filter=stopfilter)
   File "/usr/pypy/site-packages/scapy/sendrecv.py", line 593, in sniff
     **karg)]
   File "/usr/pypy/site-packages/scapy/arch/linux.py", line 496, in __init__
     attach_filter(self.ins, filter, iface)
   File "/usr/pypy/site-packages/scapy/arch/linux.py", line 157, in attach_filter
     s.setsockopt(SOL_SOCKET, SO_ATTACH_FILTER, bpfh)
   File "<string>", line 1, in setsockopt
 error: [Errno 22] Invalid argument

```
This has been reported before, but I guess never fixed: [Link](https://mail.python.org/pipermail/pypy-issue/2012-November/003243.html)

**Comment by gpotter2** [comment]
Hi,
Could you try using
https://github.com/secdev/scapy/pull/738
? It has a fix for attach_filter
Thanks !

**Comment by blizzardplus** [comment]
Used [#738](https://github.com/secdev/scapy/pull/738), slightly different error message this time:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/pypy/site-packages/scapy/sendrecv.py", line 671, in sniff
    *arg, **karg)] = iface
  File "/usr/pypy/site-packages/scapy/arch/linux.py", line 557, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/pypy/site-packages/scapy/arch/linux.py", line 157, in attach_filter
    s.setsockopt(SOL_SOCKET, SO_ATTACH_FILTER, bp)
  File "<string>", line 1, in setsockopt
TypeError: expected string, got bpf_program object

Using PyPy 5.8.0:

Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901] on linux2

**Comment by gpotter2** [comment]
Definatly a bug

**Comment by gpotter2** [comment]
Sorry for the delay, fixed in https://github.com/secdev/scapy/pull/872
