### ISSUE TITLE
NameError: global name 'log_runtime' is not defined

### ISSUE THREAD

**Issue by amirgreen** [secdev/scapy#914]
I installed scapy and it works fine when i'm running it directly. But when im trynig to write scripts with it it gives me an error. I wrote a simple code but cant get it to work.
**Code:**
`from scapy.all import *

packets = sniff(count=1)
packets.show()`

**Error:**
`Traceback (most recent call last):
  File "C:/Users/Amir/PycharmProjects/ClientAndServer/mim.py", line 3, in <module>
    packets = sniff(count=1)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 177, in sniff
    log_runtime.info('Sniffing on %s' % conf.iface)
NameError: global name 'log_runtime' is not defined`

What should I do? couldn't find a solution...

**Comment by gpotter2** [comment]
Could you retry using the latest scapy version:
https://github.com/secdev/scapy/archive/master.zip
It seems that you are using an outdated version

**Comment by amirgreen** [comment]
ok, now i cant run scapy at all...
`Traceback (most recent call last):
  File "C:\Python27\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 421, in interact
    init_session(session_name, mydict)
  File "C:\Python27\lib\site-packages\scapy\main.py", line 293, in init_session
    scapy_builtins = {k: v for k, v in six.iteritems(importlib.import_module(".all", "scapy").__dict__) if _validate_local(k)}
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module>
    from scapy.arch import *
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 70, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 531, in <module>
    IFACES.load_from_powershell()
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 426, in load_from_powershell
    for i in get_windows_if_list():
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 309, in get_windows_if_list
    for line in query)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 308, in <genexpr>
    (dict(zip(['name', 'win_index', 'description', 'guid', 'mac', 'netid'], line))
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 83, in _exec_query_ps
    l[-1] += sl[0].strip()
IndexError: list index out of range`

**Comment by gpotter2** [comment]
```
Traceback (most recent call last): 
File "C:\Python27\Scripts\\scapy", line 25, in <module> interact() 
File "C:\Python27\lib\site-packages\scapy\main.py", line 421, in interact init_session(session_name, mydict) 
File "C:\Python27\lib\site-packages\scapy\main.py", line 293, in init_session scapy_builtins = {k: v for k, v in six.iteritems(importlib.import_module(".all", "scapy").__dict__) if _validate_local(k)} 
File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module __import__(name) 
File "C:\Python27\lib\site-packages\scapy\all.py", line 16, in <module> from scapy.arch import * 
File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 70, in <module> from scapy.arch.windows import * 
File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 531, in <module> IFACES.load_from_powershell() 
File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 426, in load_from_powershell for i in get_windows_if_list(): 
File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 309, in get_windows_if_list for line in query) 
File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 308, in <genexpr> (dict(zip(['name', 'win_index', 'description', 'guid', 'mac', 'netid'], line)) 
File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 83, in _exec_query_ps l[-1] += sl[0].strip() IndexError: list index out of range
```

**Comment by gpotter2** [comment]
Hi, it seems to be a bug.
Could you please give us the content of (using powershell):
- If you are using windows 7:
```
Get-WmiObject Win32_NetworkAdapter | select Name, InterfaceIndex, InterfaceDescription, GUID, MacAddress, NetConnectionID | fl
```
- If you are using windows 8+:
```
Get-NetAdapter | select InterfaceDescription, InterfaceIndex, Name , InterfaceGuid, MacAddress, Name | fl
```

**Comment by amirgreen** [comment]
```
InterfaceDescription : Npcap Loopback Adapter
InterfaceIndex       : 22
Name                 : Ethernet 4
InterfaceGuid        : {4E6F0429-72A6-4CE4-B9A8-9A85F5F1E3A2}
MacAddress           : 02-00-4C-4F-4F-50

InterfaceDescription : Realtek PCIe GBE Family Controller
InterfaceIndex       : 17
Name                 : Local Area Connection
InterfaceGuid        : {F5CBBD74-C4F9-4BA7-ABB2-DA00C8C3A2BF}
MacAddress           : FC-AA-14-07-7A-AA

InterfaceDescription : Npcap Loopback Adapter
InterfaceIndex       : 4
Name                 : Npcap Loopback Adapter
InterfaceGuid        : {261F7440-064F-45A1-AB31-9442C55E4FC9}
MacAddress           : 02-00-4C-4F-4F-50

InterfaceDescription : LogMeIn Hamachi Virtual Ethernet Adapter
InterfaceIndex       : 9
Name                 : Ethernet 2
InterfaceGuid        : {803C1BD5-D466-4309-8BC0-F7DCA52C1BC3}
MacAddress           : 7A-79-19-2A-9D-7F
```

**Comment by gpotter2** [comment]
Thanks, there is indeed a bug.
Could you also give me
`Get-NetAdapter | select * | fl`

Seems that not enough data is returned

**Comment by amirgreen** [comment]
```
MacAddress                                       : 02-00-4C-4F-4F-50
Status                                           : Up
LinkSpeed                                        : 1.2 Gbps
MediaType                                        : 802.3
PhysicalMediaType                                : Unspecified
AdminStatus                                      : Up
MediaConnectionState                             : Connected
DriverInformation                                : Driver Date 2006-06-21 Version 10.0.15063.0 NDIS 6.30
DriverFileName                                   : loop.sys
NdisVersion                                      : 6.30
ifOperStatus                                     : Up
ifAlias                                          : Ethernet 4
InterfaceAlias                                   : Ethernet 4
ifIndex                                          : 22
ifDesc                                           : Npcap Loopback Adapter
ifName                                           : ethernet_32776
DriverVersion                                    : 10.0.15063.0
LinkLayerAddress                                 : 02-00-4C-4F-4F-50
Caption                                          :
Description                                      :
ElementName                                      :
InstanceID                                       : {4E6F0429-72A6-4CE4-B9A8-9A85F5F1E3A2}
CommunicationStatus                              :
DetailedStatus                                   :
HealthState                                      :
InstallDate                                      :
Name                                             : Ethernet 4
OperatingStatus                                  :
OperationalStatus                                :
PrimaryStatus                                    :
StatusDescriptions                               :
AvailableRequestedStates                         :
EnabledDefault                                   : 2
EnabledState                                     : 5
OtherEnabledState                                :
RequestedState                                   : 12
TimeOfLastStateChange                            :
TransitioningToState                             : 12
AdditionalAvailability                           :
Availability                                     :
CreationClassName                                : MSFT_NetAdapter
DeviceID                                         : {4E6F0429-72A6-4CE4-B9A8-9A85F5F1E3A2}
ErrorCleared                                     :
ErrorDescription                                 :
IdentifyingDescriptions                          :
LastErrorCode                                    :
MaxQuiesceTime                                   :
OtherIdentifyingInfo                             :
PowerManagementCapabilities                      :
PowerManagementSupported                         :
PowerOnHours                                     :
StatusInfo                                       :
SystemCreationClassName                          : CIM_NetworkPort
SystemName                                       : Grunfeld5
TotalPowerOnHours                                :
MaxSpeed                                         :
OtherPortType                                    :
PortType                                         :
RequestedSpeed                                   :
Speed                                            : 1215752192
UsageRestriction                                 :
ActiveMaximumTransmissionUnit                    : 1500
AutoSense                                        :
FullDuplex                                       : True
LinkTechnology                                   :
NetworkAddresses                                 : {02004C4F4F50}
OtherLinkTechnology                              :
OtherNetworkPortType                             :
PermanentAddress                                 : 02004C4F4F50
PortNumber                                       : 0
SupportedMaximumTransmissionUnit                 :
AdminLocked                                      : False
ComponentID                                      : *msloop
ConnectorPresent                                 : True
DeviceName                                       : \Device\{4E6F0429-72A6-4CE4-B9A8-9A85F5F1E3A2}
DeviceWakeUpEnable                               : False
DriverDate                                       : 2006-06-21
DriverDateData                                   : 127953216000000000
DriverDescription                                : Microsoft KM-TEST Loopback Adapter
DriverMajorNdisVersion                           : 6
DriverMinorNdisVersion                           : 30
DriverName                                       : \SystemRoot\System32\drivers\loop.sys
DriverProvider                                   : Microsoft
DriverVersionString                              : 10.0.15063.0
EndPointInterface                                : False
HardwareInterface                                : True
Hidden                                           : False
HigherLayerInterfaceIndices                      : {23}
IMFilter                                         : False
InterfaceAdminStatus                             : 1
InterfaceDescription                             : Npcap Loopback Adapter
InterfaceGuid                                    : {4E6F0429-72A6-4CE4-B9A8-9A85F5F1E3A2}
InterfaceIndex                                   : 22
InterfaceName                                    : ethernet_32776
InterfaceOperationalStatus                       : 1
InterfaceType                                    : 6
iSCSIInterface                                   : False
LowerLayerInterfaceIndices                       :
MajorDriverVersion                               : 6
MediaConnectState                                : 1
MediaDuplexState                                 : 2
MinorDriverVersion                               : 0
MtuSize                                          : 1500
NdisMedium                                       : 0
NdisPhysicalMedium                               : 0
NetLuid                                          : 1689399750295552
NetLuidIndex                                     : 32776
NotUserRemovable                                 : False
OperationalStatusDownDefaultPortNotAuthenticated : False
OperationalStatusDownInterfacePaused             : False
OperationalStatusDownLowPowerState               : False
OperationalStatusDownMediaDisconnected           : False
PnPDeviceID                                      : ROOT\NET\0002
PromiscuousMode                                  : False
ReceiveLinkSpeed                                 : 1215752192
State                                            : 2
TransmitLinkSpeed                                : 1215752192
Virtual                                          : False
VlanID                                           :
WdmInterface                                     : False
PSComputerName                                   :
CimClass                                         : ROOT/StandardCimv2:MSFT_NetAdapter
CimInstanceProperties                            : {Caption, Description, ElementName, InstanceID...}
CimSystemProperties                              : Microsoft.Management.Infrastructure.CimSystemProperties

MacAddress                                       : FC-AA-14-07-7A-AA
Status                                           : Up
LinkSpeed                                        : 1 Gbps
MediaType                                        : 802.3
PhysicalMediaType                                : 802.3
AdminStatus                                      : Up
MediaConnectionState                             : Connected
DriverInformation                                : Driver Date 2015-04-06 Version 9.1.406.2015 NDIS 6.40
DriverFileName                                   : rt640x64.sys
NdisVersion                                      : 6.40
ifOperStatus                                     : Up
ifAlias                                          : Local Area Connection
InterfaceAlias                                   : Local Area Connection
ifIndex                                          : 17
ifDesc                                           : Realtek PCIe GBE Family Controller
ifName                                           : ethernet_6
DriverVersion                                    : 9.1.406.2015
LinkLayerAddress                                 : FC-AA-14-07-7A-AA
Caption                                          :
Description                                      :
ElementName                                      :
InstanceID                                       : {F5CBBD74-C4F9-4BA7-ABB2-DA00C8C3A2BF}
CommunicationStatus                              :
DetailedStatus                                   :
HealthState                                      :
InstallDate                                      :
Name                                             : Local Area Connection
OperatingStatus                                  :
OperationalStatus                                :
PrimaryStatus                                    :
StatusDescriptions                               :
AvailableRequestedStates                         :
EnabledDefault                                   : 2
EnabledState                                     : 5
OtherEnabledState                                :
RequestedState                                   : 12
TimeOfLastStateChange                            :
TransitioningToState                             : 12
AdditionalAvailability                           :
Availability                                     :
CreationClassName                                : MSFT_NetAdapter
DeviceID                                         : {F5CBBD74-C4F9-4BA7-ABB2-DA00C8C3A2BF}
ErrorCleared                                     :
ErrorDescription                                 :
IdentifyingDescriptions                          :
LastErrorCode                                    :
MaxQuiesceTime                                   :
OtherIdentifyingInfo                             :
PowerManagementCapabilities                      :
PowerManagementSupported                         :
PowerOnHours                                     :
StatusInfo                                       :
SystemCreationClassName                          : CIM_NetworkPort
SystemName                                       : Grunfeld5
TotalPowerOnHours                                :
MaxSpeed                                         :
OtherPortType                                    :
PortType                                         :
RequestedSpeed                                   :
Speed                                            : 1000000000
UsageRestriction                                 :
ActiveMaximumTransmissionUnit                    : 1500
AutoSense                                        :
FullDuplex                                       : True
LinkTechnology                                   :
NetworkAddresses                                 : {FCAA14077AAA}
OtherLinkTechnology                              :
OtherNetworkPortType                             :
PermanentAddress                                 : FCAA14077AAA
PortNumber                                       : 0
SupportedMaximumTransmissionUnit                 :
AdminLocked                                      : False
ComponentID                                      : PCI\VEN_10EC&DEV_8168&REV_06
ConnectorPresent                                 : True
DeviceName                                       : \Device\{F5CBBD74-C4F9-4BA7-ABB2-DA00C8C3A2BF}
DeviceWakeUpEnable                               : True
DriverDate                                       : 2015-04-06
DriverDateData                                   : 130727520000000000
DriverDescription                                : Realtek PCIe GBE Family Controller
DriverMajorNdisVersion                           : 6
DriverMinorNdisVersion                           : 40
DriverName                                       : \SystemRoot\System32\drivers\rt640x64.sys
DriverProvider                                   : Realtek
DriverVersionString                              : 9.1.406.2015
EndPointInterface                                : False
HardwareInterface                                : True
Hidden                                           : False
HigherLayerInterfaceIndices                      : {25}
IMFilter                                         : False
InterfaceAdminStatus                             : 1
InterfaceDescription                             : Realtek PCIe GBE Family Controller
InterfaceGuid                                    : {F5CBBD74-C4F9-4BA7-ABB2-DA00C8C3A2BF}
InterfaceIndex                                   : 17
InterfaceName                                    : ethernet_6
InterfaceOperationalStatus                       : 1
InterfaceType                                    : 6
iSCSIInterface                                   : False
LowerLayerInterfaceIndices                       :
MajorDriverVersion                               : 9
MediaConnectState                                : 1
MediaDuplexState                                 : 2
MinorDriverVersion                               : 1
MtuSize                                          : 1500
NdisMedium                                       : 0
NdisPhysicalMedium                               : 14
NetLuid                                          : 1688849960927232
NetLuidIndex                                     : 6
NotUserRemovable                                 : False
OperationalStatusDownDefaultPortNotAuthenticated : False
OperationalStatusDownInterfacePaused             : False
OperationalStatusDownLowPowerState               : False
OperationalStatusDownMediaDisconnected           : False
PnPDeviceID                                      : PCI\VEN_10EC&DEV_8168&SUBSYS_E0001458&REV_06\4&1DCB0711
PromiscuousMode                                  : False
ReceiveLinkSpeed                                 : 1000000000
State                                            : 2
TransmitLinkSpeed                                : 1000000000
Virtual                                          : False
VlanID                                           :
WdmInterface                                     : False
PSComputerName                                   :
CimClass                                         : ROOT/StandardCimv2:MSFT_NetAdapter
CimInstanceProperties                            : {Caption, Description, ElementName, InstanceID...}
CimSystemProperties                              : Microsoft.Management.Infrastructure.CimSystemProperties

MacAddress                                       : 02-00-4C-4F-4F-50
Status                                           : Up
LinkSpeed                                        : 1.2 Gbps
MediaType                                        : 802.3
PhysicalMediaType                                : Unspecified
AdminStatus                                      : Up
MediaConnectionState                             : Connected
DriverInformation                                : Driver Date 2006-06-21 Version 10.0.15063.0 NDIS 6.30
DriverFileName                                   : loop.sys
NdisVersion                                      : 6.30
ifOperStatus                                     : Up
ifAlias                                          : Npcap Loopback Adapter
InterfaceAlias                                   : Npcap Loopback Adapter
ifIndex                                          : 4
ifDesc                                           : Npcap Loopback Adapter
ifName                                           : ethernet_32775
DriverVersion                                    : 10.0.15063.0
LinkLayerAddress                                 : 02-00-4C-4F-4F-50
Caption                                          :
Description                                      :
ElementName                                      :
InstanceID                                       : {261F7440-064F-45A1-AB31-9442C55E4FC9}
CommunicationStatus                              :
DetailedStatus                                   :
HealthState                                      :
InstallDate                                      :
Name                                             : Npcap Loopback Adapter
OperatingStatus                                  :
OperationalStatus                                :
PrimaryStatus                                    :
StatusDescriptions                               :
AvailableRequestedStates                         :
EnabledDefault                                   : 2
EnabledState                                     : 5
OtherEnabledState                                :
RequestedState                                   : 12
TimeOfLastStateChange                            :
TransitioningToState                             : 12
AdditionalAvailability                           :
Availability                                     :
CreationClassName                                : MSFT_NetAdapter
DeviceID                                         : {261F7440-064F-45A1-AB31-9442C55E4FC9}
ErrorCleared                                     :
ErrorDescription                                 :
IdentifyingDescriptions                          :
LastErrorCode                                    :
MaxQuiesceTime                                   :
OtherIdentifyingInfo                             :
PowerManagementCapabilities                      :
PowerManagementSupported                         :
PowerOnHours                                     :
StatusInfo                                       :
SystemCreationClassName                          : CIM_NetworkPort
SystemName                                       : Grunfeld5
TotalPowerOnHours                                :
MaxSpeed                                         :
OtherPortType                                    :
PortType                                         :
RequestedSpeed                                   :
Speed                                            : 1215752192
UsageRestriction                                 :
ActiveMaximumTransmissionUnit                    : 1500
AutoSense                                        :
FullDuplex                                       : True
LinkTechnology                                   :
NetworkAddresses                                 : {02004C4F4F50}
OtherLinkTechnology                              :
OtherNetworkPortType                             :
PermanentAddress                                 : 02004C4F4F50
PortNumber                                       : 0
SupportedMaximumTransmissionUnit                 :
AdminLocked                                      : False
ComponentID                                      : *msloop
ConnectorPresent                                 : True
DeviceName                                       : \Device\{261F7440-064F-45A1-AB31-9442C55E4FC9}
DeviceWakeUpEnable                               : False
DriverDate                                       : 2006-06-21
DriverDateData                                   : 127953216000000000
DriverDescription                                : Microsoft KM-TEST Loopback Adapter
DriverMajorNdisVersion                           : 6
DriverMinorNdisVersion                           : 30
DriverName                                       : \SystemRoot\System32\drivers\loop.sys
DriverProvider                                   : Microsoft
DriverVersionString                              : 10.0.15063.0
EndPointInterface                                : True
HardwareInterface                                : True
Hidden                                           : False
HigherLayerInterfaceIndices                      : {18}
IMFilter                                         : False
InterfaceAdminStatus                             : 1
InterfaceDescription                             : Npcap Loopback Adapter
InterfaceGuid                                    : {261F7440-064F-45A1-AB31-9442C55E4FC9}
InterfaceIndex                                   : 4
InterfaceName                                    : ethernet_32775
InterfaceOperationalStatus                       : 1
InterfaceType                                    : 6
iSCSIInterface                                   : False
LowerLayerInterfaceIndices                       :
MajorDriverVersion                               : 6
MediaConnectState                                : 1
MediaDuplexState                                 : 2
MinorDriverVersion                               : 0
MtuSize                                          : 1500
NdisMedium                                       : 0
NdisPhysicalMedium                               : 0
NetLuid                                          : 1689399733518336
NetLuidIndex                                     : 32775
NotUserRemovable                                 : False
OperationalStatusDownDefaultPortNotAuthenticated : False
OperationalStatusDownInterfacePaused             : False
OperationalStatusDownLowPowerState               : False
OperationalStatusDownMediaDisconnected           : False
PnPDeviceID                                      : ROOT\NET\0001
PromiscuousMode                                  : False
ReceiveLinkSpeed                                 : 1215752192
State                                            : 2
TransmitLinkSpeed                                : 1215752192
Virtual                                          : False
VlanID                                           :
WdmInterface                                     : False
PSComputerName                                   :
CimClass                                         : ROOT/StandardCimv2:MSFT_NetAdapter
CimInstanceProperties                            : {Caption, Description, ElementName, InstanceID...}
CimSystemProperties                              : Microsoft.Management.Infrastructure.CimSystemProperties

MacAddress                                       : 7A-79-19-2A-9D-7F
Status                                           : Up
LinkSpeed                                        : 10 Gbps
MediaType                                        : 802.3
PhysicalMediaType                                : Unspecified
AdminStatus                                      : Up
MediaConnectionState                             : Connected
DriverInformation                                : Driver Date 2015-03-30 Version 15.28.40.464 NDIS 6.0
DriverFileName                                   : Hamdrv.sys
NdisVersion                                      : 6.0
ifOperStatus                                     : Up
ifAlias                                          : Ethernet 2
InterfaceAlias                                   : Ethernet 2
ifIndex                                          : 9
ifDesc                                           : LogMeIn Hamachi Virtual Ethernet Adapter
ifName                                           : ethernet_32769
DriverVersion                                    : 15.28.40.464
LinkLayerAddress                                 : 7A-79-19-2A-9D-7F
Caption                                          :
Description                                      :
ElementName                                      :
InstanceID                                       : {803C1BD5-D466-4309-8BC0-F7DCA52C1BC3}
CommunicationStatus                              :
DetailedStatus                                   :
HealthState                                      :
InstallDate                                      :
Name                                             : Ethernet 2
OperatingStatus                                  :
OperationalStatus                                :
PrimaryStatus                                    :
StatusDescriptions                               :
AvailableRequestedStates                         :
EnabledDefault                                   : 2
EnabledState                                     : 5
OtherEnabledState                                :
RequestedState                                   : 12
TimeOfLastStateChange                            :
TransitioningToState                             : 12
AdditionalAvailability                           :
Availability                                     :
CreationClassName                                : MSFT_NetAdapter
DeviceID                                         : {803C1BD5-D466-4309-8BC0-F7DCA52C1BC3}
ErrorCleared                                     :
ErrorDescription                                 :
IdentifyingDescriptions                          :
LastErrorCode                                    :
MaxQuiesceTime                                   :
OtherIdentifyingInfo                             :
PowerManagementCapabilities                      :
PowerManagementSupported                         :
PowerOnHours                                     :
StatusInfo                                       :
SystemCreationClassName                          : CIM_NetworkPort
SystemName                                       : Grunfeld5
TotalPowerOnHours                                :
MaxSpeed                                         :
OtherPortType                                    :
PortType                                         :
RequestedSpeed                                   :
Speed                                            : 10000000000
UsageRestriction                                 :
ActiveMaximumTransmissionUnit                    : 1500
AutoSense                                        :
FullDuplex                                       : True
LinkTechnology                                   :
NetworkAddresses                                 : {7A79192A9D7F}
OtherLinkTechnology                              :
OtherNetworkPortType                             :
PermanentAddress                                 : 0250F2919604
PortNumber                                       : 0
SupportedMaximumTransmissionUnit                 :
AdminLocked                                      : False
ComponentID                                      : hamachi
ConnectorPresent                                 : False
DeviceName                                       : \Device\{803C1BD5-D466-4309-8BC0-F7DCA52C1BC3}
DeviceWakeUpEnable                               : False
DriverDate                                       : 2015-03-30
DriverDateData                                   : 130721472000000000
DriverDescription                                : LogMeIn Hamachi Virtual Ethernet Adapter
DriverMajorNdisVersion                           : 6
DriverMinorNdisVersion                           : 0
DriverName                                       : \SystemRoot\System32\drivers\Hamdrv.sys
DriverProvider                                   : LogMeIn Inc.
DriverVersionString                              : 15.28.40.464
EndPointInterface                                : False
HardwareInterface                                : False
Hidden                                           : False
HigherLayerInterfaceIndices                      : {16}
IMFilter                                         : False
InterfaceAdminStatus                             : 1
InterfaceDescription                             : LogMeIn Hamachi Virtual Ethernet Adapter
InterfaceGuid                                    : {803C1BD5-D466-4309-8BC0-F7DCA52C1BC3}
InterfaceIndex                                   : 9
InterfaceName                                    : ethernet_32769
InterfaceOperationalStatus                       : 1
InterfaceType                                    : 6
iSCSIInterface                                   : False
LowerLayerInterfaceIndices                       :
MajorDriverVersion                               : 128
MediaConnectState                                : 1
MediaDuplexState                                 : 2
MinorDriverVersion                               : 22
MtuSize                                          : 1500
NdisMedium                                       : 0
NdisPhysicalMedium                               : 0
NetLuid                                          : 1689399632855040
NetLuidIndex                                     : 32769
NotUserRemovable                                 : False
OperationalStatusDownDefaultPortNotAuthenticated : False
OperationalStatusDownInterfacePaused             : False
OperationalStatusDownLowPowerState               : False
OperationalStatusDownMediaDisconnected           : False
PnPDeviceID                                      : ROOT\NET\0000
PromiscuousMode                                  : False
ReceiveLinkSpeed                                 : 10000000000
State                                            : 2
TransmitLinkSpeed                                : 10000000000
Virtual                                          : True
VlanID                                           :
WdmInterface                                     : True
PSComputerName                                   :
CimClass                                         : ROOT/StandardCimv2:MSFT_NetAdapter
CimInstanceProperties                            : {Caption, Description, ElementName, InstanceID...}
CimSystemProperties                              : Microsoft.Management.Infrastructure.CimSystemProperties
```

**Comment by gpotter2** [comment]
@amirgreen Thanks a lot for your help!
Should be fixed in https://github.com/secdev/scapy/pull/915
Could you please check that it's the case ?
