### ISSUE TITLE
scapy import fail: NameError: name 'get_working_if' is not defined

### ISSUE THREAD

**Issue by commial** [secdev/scapy#921]
Hello,

On an Ubuntu 16.04.3 LTS, when launching `scapy` CLI or importing `scapy.route` without any interface in use, I got the following error:
```Python
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 25, in <module>
    interact()
  File "tools/scapy/scapy/main.py", line 421, in interact
    init_session(session_name, mydict)
  File "tools/scapy/scapy/main.py", line 293, in init_session
    scapy_builtins = {k: v for k, v in six.iteritems(importlib.import_module(".all", "scapy").__dict__) if _validate_local(k)}
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "tools/scapy/scapy/all.py", line 25, in <module>
    from scapy.route import *
  File "tools/scapy/scapy/route.py", line 195, in <module>
    conf.iface = get_working_if()
NameError: name 'get_working_if' is not defined
```

A bisect leads to the recent commit fd50b349263256e0aaa69780937ae02d4f4ee46c, more likely to [this code](https://github.com/secdev/scapy/commit/fd50b349263256e0aaa69780937ae02d4f4ee46c#diff-3fc486d3e1085d11c80c20bab07375f2R194)

I'm not sure to correctly understand for this code snippet and how it works on the different OS. This is why I prefer opening an issue :smiley:

**Comment by gpotter2** [comment]
How about
```
diff --git a/scapy/route.py b/scapy/route.py
index 580fe012..986b00d4 100644
--- a/scapy/route.py
+++ b/scapy/route.py
@@ -11,7 +11,7 @@ from __future__ import absolute_import
 from scapy.utils import atol, ltoa, itom, pretty_routes
 from scapy.config import conf
 from scapy.error import Scapy_Exception, warning
-from scapy.arch import WINDOWS
+from scapy.arch import WINDOWS, get_working_if
 import scapy.consts
 import scapy.modules.six as six
```

**Comment by commial** [comment]
The fix is working, I've opened the corresponding PR #924 .
