### ISSUE TITLE
Python 3: TLS, None > int issues

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#945]
@mtury @p-l- 
Hi,

There still are some `None > int` issues in the TLS modules.
There were fixed for SSLv2 not a long time ago, but some remain... Latest scapy version performing tls tests:

```
>>> raw(TLS())
Traceback (most recent call last):
  File "Z:\Coding\github\scapy\scapy\compat.py", line 90, in raw
    return bytes(x)
  File "Z:\Coding\github\scapy\scapy\layers\tls\session.py", line 886, in __bytes__
    built_packet = super(_GenericTLSSessionInheritance, self).__bytes__()
  File "Z:\Coding\github\scapy\scapy\packet.py", line 338, in __bytes__
    return self.build()
  File "Z:\Coding\github\scapy\scapy\packet.py", line 436, in build
    p = self.do_build()
  File "Z:\Coding\github\scapy\scapy\packet.py", line 418, in do_build
    pkt = self.self_build()
  File "Z:\Coding\github\scapy\scapy\packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "Z:\Coding\github\scapy\scapy\layers\tls\record.py", line 185, in addfield
    pkt.tls_session.tls_version >= 0x0304 and
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

and

```
>>> a = TLS(b'\x00\x03\x03\x00\x03data')
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "Z:\Coding\github\scapy\scapy\base_classes.py", line 231, in __call__
    i.__init__(*args, **kargs)
  File "Z:\Coding\github\scapy\scapy\layers\tls\record_sslv2.py", line 81, in __init__
    super(SSLv2, self).__init__(*args, **kargs)
  File "Z:\Coding\github\scapy\scapy\layers\tls\record.py", line 261, in __init__
    super(TLS, self).__init__(*args, **kargs)
  File "Z:\Coding\github\scapy\scapy\layers\tls\session.py", line 828, in __init__
    **fields)
  File "Z:\Coding\github\scapy\scapy\packet.py", line 127, in __init__
    self.dissect(_pkt)
  File "Z:\Coding\github\scapy\scapy\packet.py", line 734, in dissect
    s = self.do_dissect(s)
  File "Z:\Coding\github\scapy\scapy\packet.py", line 697, in do_dissect
    s, fval = f.getfield(self, s)
  File "Z:\Coding\github\scapy\scapy\layers\tls\record.py", line 122, in getfield
    if pkt.tls_session.tls_version > 0x0200 and pkt.type == 23:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Thanks a lot @mtury if you could have a look at this

**Comment by gpotter2** [comment]
Fixed by https://github.com/secdev/scapy/pull/948
