### ISSUE TITLE
struct error for large Dot11 packet: struct.error: ubyte format requires 0 <= number <= 255

### ISSUE THREAD

**Issue by puru1761** [secdev/scapy#977]
I have written a python program to transmit data of approximately 950 bytes in the RSNinfo field of a scapy Dot11 type 2 packet (data). It is also a beacon. I am doing this for experimental purposes, sorry. When i try to send it through sendp, I get the following traceback:

Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/root/Desktop/ADSB-Dot11/ADSB/ADSB_lib.py", line 82, in run
self.startBroadcast(self.interface, "ADSB", json.dumps(adsb_message))
File "/root/Desktop/ADSB-Dot11/ADSB/ADSB_lib.py", line 112, in startBroadcast
sendp(frame, iface=interface, inter=0.10, loop=0, verbose=False)
File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 263, in sendp
__gen_send(conf.L2socket(iface=iface, *args, **kargs), x, inter=inter, loop=loop, count=count, verbose=verbose, realtime=realtime)
File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 238, in __gen_send
s.send(p)
File "/usr/local/lib/python3.6/dist-packages/scapy/supersocket.py", line 31, in send
sx = bytes(x)
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 291, in bytes
return self.build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 359, in build
p = self.do_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 351, in do_build
pay = self.do_build_payload()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 343, in do_build_payload
return self.payload.do_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 351, in do_build
pay = self.do_build_payload()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 343, in do_build_payload
return self.payload.do_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 351, in do_build
pay = self.do_build_payload()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 343, in do_build_payload
return self.payload.do_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 351, in do_build
pay = self.do_build_payload()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 343, in do_build_payload
return self.payload.do_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 348, in do_build
pkt = self.self_build()
File "/usr/local/lib/python3.6/dist-packages/scapy/packet.py", line 339, in self_build
p = f.addfield(self, p, val)
File "/usr/local/lib/python3.6/dist-packages/scapy/fields.py", line 79, in addfield
return s+struct.pack(self.fmt, self.i2m(pkt,val))
struct.error: ubyte format requires 0 <= number <= 255

I really need to be able to do this for a project. Any help would be greatly appreciated.

Regards,
Puru

**Comment by guedou** [comment]
Could you provide a more specific description of your issue (small example, Scapy version, Pythin version, OS version, ...) ? We cannot fix what we cannot reproduce ...

**Comment by wirelessice** [comment]
from scapy.all import Dot11,Dot11Beacon,Dot11Elt,RadioTap,sendp,hexdump

netSSID = '''AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'''    #Network name here
iface = 'mon0'         #Interface name here

dot11 = Dot11(type=0, subtype=8, addr1='11:22:33:33:55:66',
addr2='22:22:22:22:22:22', addr3='11:11:22:33:44:55:')
beacon = Dot11Beacon(cap='ESS+privacy')
essid = Dot11Elt(ID='SSID',info=netSSID, len=len(netSSID))
rsn = Dot11Elt(ID='RSNinfo', info=(
'\x01\x00'                 #RSN Version 1
'\x00\x0f\xac\x02'         #Group Cipher Suite : 00-0f-ac TKIP
'\x02\x00'                 #2 Pairwise Cipher Suites (next two lines)
'\x00\x0f\xac\x04'         #AES Cipher
'\x00\x0f\xac\x02'         #TKIP Cipher
'\x01\x00'                 #1 Authentication Key Managment Suite (line below)
'\x00\x0f\xac\x02'         #Pre-Shared Key
'\x00\x00'))               #RSN Capabilities (no extra capabilities)

frame = RadioTap()/dot11/beacon/essid/rsn

frame.show()
print("\nHexdump of frame:")
hexdump(frame)
raw_input("\nPress enter to start\n")

sendp(frame, iface=iface, inter=0.100, loop=1)
---------------------------------------------
This script can reproduce his problems, I happen to have the same problem, you can break 255 bytes limit it?

**Comment by guedou** [comment]
By definition, it is not possible to store more than 255 bytes in a `Dot11Elt` : 
```
>>> raw(Dot11Elt(len=255))
'\x00\xff'
>>> raw(Dot11Elt(len=256))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/compat.py", line 66, in raw
    return x.__bytes__()
  File "scapy/packet.py", line 338, in __bytes__
    return self.build()
  File "scapy/packet.py", line 436, in build
    p = self.do_build()
  File "scapy/packet.py", line 418, in do_build
    pkt = self.self_build()
  File "scapy/packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
error: ubyte format requires 0 <= number <= 255
```
